- docs/G-Codes.md
- klippy/extruder.py
Allows setting `pressure_advance` and `pressure_advance_lookahead_time` from g-code. Not sure whether it's a good idea to respond with the new values, but I added that anyway. Let me know if I should change anything.
Fixes issue #247.
Signed-off-by: Michael Barbour <barbour.michael.0@gmail.com>
> extruder: Add SET_PRESSURE_ADVANCE command.

- config/example-extras.cfg
- klippy/extras/temperature_fan.py
Perhaps we could unify the temperature controlled fans and add more `control`s to support other scenarios?
This acts like a heater but in reverse adding more fan when cooling is needed.  Two modes are available `BangBang` and `Pid`. 
`min_speed` refers to the minimum speed the fan can spin when on as many fans will not spin unless sufficient power is applied.
Thought? Suggestions to improve?
Signed-off-by Douglas Hammond  <wizhippo@gmail.com>
> Add  pid temp controlled fan

- klippy/extras/probe.py
This change will make the "PROBE" command actually reply with the
z-position where the probe triggers. As this command is called
internally for the BED_TILT_CALIBRATE and Z_TILT_ADJUST those commands
will also give a response while probing, which I see as advantage over
the silent operation.
This change also lets one define some gcode for a repeatable probing
test to meassure the quality of the sensor and overall probing accuracy.
Signed-off-by: Hans Raaf <hr-klipper@oderwat.de>
> Extras: Probing does reply with the z position where the probe triggers.

- config/generic-re-arm.cfg
- klippy/extras/display.py
Re-Arm is a Smoothie LPC1768 replacement for the Arduino Mega. Due to this the pinout is slightly different to the smoothieboard. [Board]( https://bit.ly/2lcv3ts) & [Pinout](https://bit.ly/2JKaseW)
Pinout tested in personal config file - see log file in issue #405. LCD does not work currently, but pinout is there for when and if it is resolved. 
Note: Smoothie based LPC176* boards do not work with the 2004 style display only the st7920 Full Graphic Controller
Signed-off-by: Ax Smith-Laffin (ax@darknetweb.co.uk)
> Add Generic Configuration File for Re-Arm (LPC1768) / Modify Display delay to work with Re-Arm

- src/stm32f1/gpio.c
For some reason, the upper two pin definitions were missing. Found while
writing the port documentation.
Signed-off-by: Grigori Goronzy <greg@chown.ath.cx>
> stm32f1: fix ADC pin list

- config/printer-anycubic-kossel-plus-2017.cfg
Pretty much the same as the non plus config. But it is adjusted and tested with my actual printer. The angles are defined in a way the the coordinates make sense when watching the printer from the side where the display panel is located. I did DELTA_CALIBRATE starting with these settings and the result came really close again.
Signed-off-by: Hans Raaf <hr-klipper@oderwat.de>
> Added config for my Anycubic Kossel Plus Delta Printer.

- klippy/gcode.py
I ran into this when testing mesh leveling against Klipper's latest code.  This fix simply fetches the rails from Kinematics, then concatenates the stepper lists.  
> gcode: fix for GET_POSITION

- docs/stm32f1.md
- src/stm32f1/Kconfig
- src/stm32f1/gpio.c
- src/stm32f1/gpio.h
- src/stm32f1/main.c
Add basic SPI support and associated documentation.
Note: I only did some basic loopback testing - connected MISO and MOSI and then did:
allocate_oids count=1
config_spi oid=0 bus=0 pin=PA8 mode=3 rate=1000000 shutdown_msg=
spi_transfer oid=0 data=30313233343536373839
Which resulted in this response:
spi_transfer_response oid=0 response='0123456789'
> stm32f1: add SPI support

- src/avr/Kconfig
Add choice between UART0 or UART1 to KConfig for atmega1284p
> atmega1284p: Add choice between UART0 or UART1 to Kconfig

- config/example-extras.cfg
- klippy/extras/bed_mesh.py
- klippy/extras/bed_tilt.py
- klippy/extras/delta_calibrate.py
- klippy/extras/probe.py
- klippy/extras/z_tilt.py
* Only warn user about a difference in probe z_offset vs the z position_endstop if stepper_z is using the probe as a virtual endstop
* Move x_offset and y_offset parameters to [probe]
* Update configuration to reflect these changes.  Also made some minor formatting changes to make bed_mesh consistent with the rest of confg_extras, and briefly documented manual_probe which should also work for bed_mesh.
I currently fetch the x and y probe offsets directly from the config in bed_mesh, however I considered sending all of the offsets back in finalize() in place of the z_offset.  I think that is the cleanest way to do it, but considering it would require changes to bed_tilt and delta_calibrate I thought it best to get your input first.
> bed_mesh: minor updates

- config/example-extras.cfg
- config/example-menu.cfg
- klippy/extras/display/display.py
- klippy/extras/display/menu.cfg
- klippy/extras/display/menu.py
It's a text based menu system and requires working display.
The menu structure is fully configurable via config file. 
It can be used as alternative info/status screen.
Please check `example-menu.cfg` for more info.
Menu will working with different screen sizes (4x16, 4x20).
Module has menu and buttons related attributes also in config `display` section. 
Please check `example-extras.cfg` `display` section for more info.
Example menu related attributes in `display` section
```
menu_timeout: 60
menu_root: main
encoder_pins: ^!ar31, ^!ar33
click_pin: ^!ar35
kill_pin: ^!ar41
```
> Flexible menu system for klipper

- docs/Bootloaders.md
- docs/Debugging.md
- docs/Features.md
For some reason the benchmarks for 3 steppers caved in. The numbers are still good, just not as good. Also added flashing and benchmarking instructions to match the existing documentation.
> Update sam4e8e docs and benchmarks

- src/sam4e8e/Makefile
- src/sam4e8e/gpio.c
The bank_id was calculated erroneously. Also unify gpio_in_setup and gpio_out_setup a bit.
Signed-off-by: Florian Heilmann Florian.Heilmann@gmx.net
> Fix bug in sam4e gpio.c

- config/printer-anycubic-kossel-2016.cfg
I added click pin, encoder pins and kill pin in order to be able to be able to use the menu in the printer and to stop the printer in case of emergency
Signed-off-by: Alejandro alemorbel@alemorbel.es
> Add display buttons pins for anycubic kossel pulley 2016

- config/example-extras.cfg
- klippy/extras/tmc2660.py
In order to get some feedback on the implementation, here is my current work on getting the TMC2660 (used on the Duet Wifi/Ethernet 2 boards) supported in klipper.
In addition to exposing all possible registers of the TMC2660, this extra adds the following functionality:
- Set current via the `SET_CURRENT STEPPER=driver_name CURRENT=[100-2400]`
- Allow the driver to reduce the motor current to `idle_curent_percent` after `idle_timeout` seconds and raise it back up to full current if the toolhead needs to move again. **WARNING make sure this is high enough so the steppers don't lose position and can make sure the first move is not a super-fast one because there is up to .1 second delay until the current is raised again.**
This implementation does NOT support sensorless homing, since not …
> [Feedback requested] TMC 2660 support

- klippy/extras/display/menu.cfg
Added a new submenu `Tune` to the default menu.
It's visible during the print time and has 3 real-time inputs
`Speed` - Set speed factor override
`Flow` - Set extrude factor override
`Offset Z` - Set a positional offset to the Z axis
> New Tune submenu

- config/example-menu.cfg
- klippy/extras/display/menu.cfg
- klippy/extras/display/menu.py
There's a new menu feature.
For the input items, it's possible to set 2 different step values.
One value for normal `input_step:` and other for fast `input_step2:` step rate.
If the fast rate is not set then it's all the time using normal step value.
Currently, the fast rate starts when encoder speed is equal to or below 0.03sec
I have also changed default menu both hotend and hotbed target items to use this feature.
Example.
```ini
[menu __temp __hotend0_target]
type: input
enable: extruder0.is_enabled
name: "{0:4.0f}"
parameter: extruder0.target
input_min: 0
input_max: 250
input_step: 1
input_step2: 10
gcode: M104 T0 S{0:.0f}
```
Please test.
> New menu feature: input fast stepping rate

- klippy/extras/display/menu.cfg
- klippy/extras/display/menu.py
Long filename scrolling option for `vsdcard` menu item.
It adds `scroll_long_filenames` boolean attribute to `vsdcard` config.
The default value is false.
I turned it on for klippers default menu.
```ini
...
[menu __sdcard]
type: vsdcard
name: SD Card
scroll_long_filenames: true
items:
...
```
> menu: vsdcard - scroll long filenames

- klippy/extras/gcode_macro.py
This dev makes possible to use g-code parameters inside a macro script.
It should be backwards compatible with existing user macros.
All parameter values are passed as they are (strings) and by name. 
It's internally using python advanced string formatting with params as kwargs.
Example macro
```ini
[gcode_macro M355]
gcode:
SET_PIN PIN=caselight VALUE={S}
```
When calling the macro with parameter `M355 S1`
then available options for formatting are:
```
S → 1
M → 355
```
**NB!** Extended G-Code Command style macros will only accept params in form of `KEY=VAL`
Example call `CASE_LIGHT STATE=1`
```ini
[gcode_macro CASE_LIGHT]
gcode:
SET_PIN PIN=caselight VALUE={STATE}
```
> gcode_macro: macro improvement with parameters

- config/example-delta.cfg
- config/example-extras.cfg
- config/sample-bltouch.cfg
- docs/Delta_Calibrate.md
- docs/G-Codes.md
- klippy/extras/bed_mesh.py
- klippy/extras/bed_tilt.py
- klippy/extras/delta_calibrate.py
- klippy/extras/probe.py
- klippy/extras/quad_gantry_level.py
- klippy/extras/z_tilt.py
- klippy/homing.py
- klippy/stepper.py
- test/klippy/z_virtual_endstop.cfg
- test/klippy/z_virtual_endstop.test
This is a notice that I plan to make some non-backwards compatible changes to the config file:
* Configs that use probe:z_virtual_endstop will no longer specify a position_endstop in the stepper_z config section.  The position_endstop will now automatically be set from the probe's z_offset parameter.
* The manual_probe config option has been removed from the delta_calibrate, bed_tilt, and bed_mesh config sections.  Instead, the DELTA_CALIBRATE, BED_TILT_CALIBRATE, and BED_MESH_CALIBRATE commands have been extended to support a "METHOD=manual" parameter.
In addition to the above changes, this series adds a number of cleanups to the probing code that will hopefully make the probing code more robust.
cd ~/klipper ; git fetch ; git checkout origin/work-probe-20180926 ; sudo service klipper …
> Probe improvements

- config/example-extras.cfg
The comment for the algorithm setting had a spelling error, it said:
`May be either "langrange"`
Removed the n.
Signed-off-by: Victor Lazaro <lazarofilm@gmail.com>
> Spelling error corrected in bed mesh comment

- config/example.cfg
- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/delta.py
- klippy/stepper.py
Allows a second homing_speed_slow parameter to be defined in the config file so that the approach after initial endstop trigger can be slowed down more then the old default of homing_speed/2.0.
Code maintains the existing default if this new parameter is not configured in the config file.
Signed-off-by: Chris Whiteford <chris@chrisandtennille.com>
> Adding support for a homing_speed_slow parameter

- config/example-extras.cfg
- klippy/extras/servo.py
- klippy/mcu.py
This allows for a startup angle or pulse-width to be defined in the config file.  Keeps servos from moving around randomly when power is re-applied to them.
Presently only supports softpwm as the servo stuff is hard coded to use that.
Signed-off-by: Chris Whiteford <github@chrisandtennille.com>
> Adding support for startup value for servos

- klippy/chelper/__init__.py
I'm writing packaging for Arch Linux for Klipper, and I would like to build the C modules while packaging. As such I've added a very simple `__main__` in the `chelper/__init__.py` which will ensure it gets compiled if it hasn't been already.
> packaging: Add a quick __main__ to compile c helper

- src/sam4e8e/main.c
Hi @FHeilmann ,
I was looking at performance on the ARM chips recently.  When you submitted the latest benchmarks (pr #562 ) you indicated a recent degradation in performance.  I think this may have been due to gcc no longer inlining the try_shutdown() method.  If you get a chance, I'd be curious if the latest code (specifically commit fb798e3c) improves the performance on the SAM4 chip?  I suspect it will, as it fixed regressions on several of my test chips.
Also, I noticed that the SAM4 controller has a cache.  (I was able to dramatically improve SAM3 performance by tuning the build to the SAM3 instruction fetch mechanics.)  The docs seem to indicate that the cache is disabled on startup.  Do you know if that is correct?  If so, does explicitly enabling the cache (as is done in this PR) …
> Is SAM4 cache on by default?

- config/example-extras.cfg
- docs/Endstop_Phase.md
- klippy/extras/endstop_phase.py
- klippy/extras/tmc2660.py
This adds the required functions for endstop phase detection to the TMC2660 extra.
> Add endstop phase detection functionality to TMC2660 extra

- config/example-extras.cfg
- klippy/extras/tmc2660.py
This removes the custom timeout code in favor of the new event system to detect ready and printing states.
While I'm at it I also added the DUMP_TMC command to the TMC2660 extra.
> Implement idle event and DUMP_TMC support to the TMC2660 extra

- config/example-extras.cfg
- klippy/extras/sx1509.py
- src/Kconfig
- src/Makefile
- src/i2ccmds.c
- src/sam4e8e/Kconfig
- src/sam4e8e/Makefile
- src/sam4e8e/gpio.h
- src/sam4e8e/i2c.c
- src/sam4e8e/internal.h
This is my recent work to extend klipper to support i2c devices in a generic way and add an additional i2c device to the mix: The SX1509 I2C-to-16GPIO expander found on the duex5 and duex2 generation of boards.
I split the contribution into 3 commits to make bisecting the whole thing easier. Please let me know about any feedback you might have.
One thing that is definitely missing is to align the implementations of the mcp4451 extra and the lpc176x i2c implementation to use this more universal approach. Since I don't have a lpc176x myself, I think it would be best if someone else dealt with that. I can, of course, try and offer up my findings for review.
Bests,
Florian
> Full i2c support and SX1509 I2C-to-GPIO expander

- .gitignore
- docs/Packaging.md
- klippy/util.py
- scripts/make_version.py
The gitdir previously could be absent and produce a version of "" in
spite of checks for it.
Parent directories with shlex-interpreted characters in their names
could be misinterpreted, potentially causing shell injection (but more likely just confusion). Removed shlex parsing of user supplied strings.
Packagers may want to remove the git history to slim down the package
size, so add an option for using a file 'version' in the klippy
directory to set version without using git.
> util: Fix versioning when gitdir is absent

- klippy/extras/tmc2660.py
Somehow a typo was left uncaught when I rebased the commit.
I'm sorry. This PR fixes it.
Bests,
Florian
> Fix typo in TMC2660 extra

- klippy/extras/sx1509.py
This allows SX1509 pins to be used as temperature fans and heater fans. Heaters are still disallowed.
> Relax restrictions on SX1509 pins

- config/generic-duet2.cfg
- test/klippy/printers.test
This PR adds a pinmap for the popular duet2 wifi and ethernet boards. It exports the most important pins as they are marked on the silkscreen of the board. There are two varieties: 
`pin_map: duet2`
which maps all pins on the board and all stepper and heater relevant pins on the expansion connector, and
`pins_map: duet2+duex`
which remaps some pins as intended when a duex is connected (replace E2_STOP through E5_STOP with the chip-selects the duex uses instead).
Further, this PR adds a generic duet configuration showcasing how to configure all steppers available on a duet2+duex combo (resulting in a quad-z quad-extruder setup) and adds this configuration as a test config. This test covers both previously untested SX1509 and TMC2660 extras.
Bests,
Florian
> Add a generic duet2 config and enable tests for it

- klippy/extras/bed_mesh.py
@Arksine
https://github.com/KevinOConnor/klipper/blob/24bbc43fd04033decde51097f6194db6cb54fda9/klippy/extras/bed_mesh.py#L295
I noticed while poking around on LGTM's static analysis (intriguing tool, seems to bring up some potentially-valid issues) that there were some identity comparisons between strings in the bed_mesh code. These are probably safe and functional right now because the compiler will put them in the same constant slot due to the comparison being in the same method as the assignment, thus they would have the same identity, but they would be really fragile if the code were ever refactored.
This pull request updates them to equality comparisons.
> bed_mesh: Fix some fragile identity comparisons

- config/example-extras.cfg
- docs/G-Codes.md
- klippy/extras/servo.py
This patch create ability to enable/disable attached servo. 
Cheap mechanical servos have small flickering. When this servo stay on one position, this flickering slowly destroy internal potentiometer and make servo unusable.  Many mechanisms need servo only to change position. Therefore I create this minor path to enable/disable servo. It stop pulses for this servo, that's all.
Corresponding G-code is:
SET_SERVO SERVO=config_name [WIDTH=<seconds>] [ENABLE=<0|1>]
SET_SERVO SERVO=config_name [ANGLE=<degrees>] [ENABLE=<0|1>]
For example:
SET_SERVO SERVO=touch ANGLE=80 ENABLE=1 ; enable servo and set position
G4 P200 ; wait 200ms
SET_SERVO SERVO=touch ENABLE=0 ; disable servo
This patch add one option to servo configuration:
enable: <False/True> # default True
It not have impact to user code …
> Add servo enable/disable support

- config/example-extras.cfg
- klippy/extras/bed_mesh.py
This pull addresses mesh fade concerns referenced in issue #926 .  Fade is now disabled by default.  Also included is a new option, fade_target, to help mitigate the z scaling affect when fade is enabled.  The fade_target is the value in which fade should converge.   A fade_target of 0.0 will exhibit previous behavior, where adjustment is phased out completely.   By default this value will be calculated as the average z position within the mesh.
If the fade_target is non-zero and lies outside of the mesh then an error will be generated, as this would add additional and likely unwanted adjustment to the mesh.
> bed_mesh:  Address fade issues

- config/example-polar.cfg
- config/example-winch.cfg
- klippy/chelper/__init__.py
- klippy/chelper/kin_polar.c
- klippy/chelper/kin_winch.c
- klippy/kinematics/none.py
- klippy/kinematics/polar.py
- klippy/kinematics/winch.py
- test/klippy/move.gcode
- test/klippy/polar.test
- test/klippy/printers.test
Klipper has had experimental "polar" and "cable winch" kinematics on development branches for some time.  I plan to commit these experimental kinematics to the master branch - although they are not complete, I think they are sufficiently modular that they will not adversely impact the main cartesian/corexy/delta users.
-Kevin
> Experimental kinematics

- klippy/gcode.py
This makes M220 (change print speed) command effect the next move command (G0/G1).
Before it only made a difference once a G0/G1 command with an F parameter was executed.
Signed-off-by: Pontus Borg <liquidpontus@yahoo.se>
> Minor change to make M220 command take effect immediately

- klippy/extras/heater_bed.py
- klippy/gcode.py
- klippy/heater.py
- klippy/kinematics/extruder.py
Allow an arbitrary gcode_id to be supplied during heater setup. This allows future extras to register additional IDs beyond B, and T# for M105 temperature reporting.
My end goal is to create a new extra for an additional type of heater, so  based of some discussion with Kevin in PR 855, this should help keep the new code isolated.
Any feedback welcome.
> gcode_id parameter for setup_heater: take a gcode_id when setting up a heater

- config/example-extras.cfg
- docs/G-Codes.md
- klippy/extras/respond.py
- klippy/gcode.py
I have made one change to `gcode.py` to support quoted parameter
values.
I have added support for the basic `M118` command (see
https://reprap.org/wiki/G-code#M118:_Echo_message_on_host). I have
also added a `RESPOND` command that takes extended parameters.
`ECHO` might be a better name than `RESPOND` but is already defined
in `gcode.py`.
Signed-off-by: Alec B. Plumb <alec@etherwalker.com>
> respond: An extra for sending messages to the printer host.

- config/generic-ramps.cfg
I thought that this might come in handy if you're using a "RepRapDiscount 128x64 Full Graphic Smart Controller" type display as it becomes easier to halt a print if anything goes wrong.
Signed-off-by: Nils Friedchen <Nils.Friedchen@googlemail.com>
> config: Add default kill_pin to RAMPS' display-section

- config/generic-smoothieboard.cfg
- docs/Config_Changes.md
- docs/FAQ.md
- docs/Overview.md
- klippy/extras/bus.py
- klippy/extras/display/uc1701.py
- klippy/extras/mcp4451.py
- klippy/extras/sx1509.py
- src/avr/i2c.c
- src/i2ccmds.c
- src/lpc176x/i2c.c
- src/samd21/i2c.c
Unfortunately, some of the Klipper code was using 7-bit i2c addresses (sam4e8e, linux mcu, replicape.py, sx1509.py) while some code was using 8-bit addresses with the low bit always zero (avr, lpc176x, samd21, mcp4451.py, uc1701.py).  The 7-bit i2c addresses are preferable, so change all the code to use this address format.
Alas, this makes a non-backwards compatible change to the printer config file for Smoothieboard users.  This change also updates the mcp4451 to validate the i2c address so the user is alerted to the problem.
-Kevin
> Fix i2c addresses

- scripts/install-ubuntu-18.04.sh
takes the `install-octopi.sh` script and switches upstart for systemd (from the centos script)
tested on armbian bionic (18.04) for orangepi pc plus
tested both install and re-run after install
> ubuntu 18.04 install script

- docs/BLTouch.md
Added basic verification tests
Added proper instructions for calibrating the z-offset
Fixed some spelling mistakes
The previous z-offset calibration instructions did not make sense to me. I can't even see how they are supposed to work, since you can't run `PROBE` unless you have run `G28` before.
> Improve the BLTouch documentation

- config/example-extras.cfg
- config/sample-macros.cfg
- docs/G-Codes.md
- klippy/extras/pause_resume.py
- klippy/extras/virtual_sdcard.py
- klippy/gcode.py
This pull request implements an advanced version of Pause/Resume functionality.  Initially this was part of my filament sensor work, however I realized that it would be useful for other situations.  For example, it can be used to implement the M600 Filament Change gcode for manual color changes during a print, as illustrated in sample-macros.cfg.
The module determines if the source gcode is printing from virtual sd or octoprint, then calls the appropriate handler to pause and resume.  It can optionally capture the current toolhead position on pause, then move back to that position on resume.  Position data is captured and restored using the toolhead directly to avoid any potential conflict with absolute vs relative coordinate movement or a change in the base position.
Signed-off-by:  Eric …
> pause_resume: advanced pause resume functionality for Klipper

- klippy/extras/idle_timeout.py
I noticed Octoprint was disconnecting after a while, and after reading the logs, I came across this error:
```
Unhandled exception during run
File "/home/pi/klipper/klippy/klippy.py", line 171, in run
self.reactor.run()
File "/home/pi/klipper/klippy/reactor.py", line 176, in run
g_next.switch()
File "/home/pi/klipper/klippy/reactor.py", line 203, in _dispatch_loop
timeout = self._check_timers(eventtime)
File "/home/pi/klipper/klippy/reactor.py", line 82, in _check_timers
t.waketime = t.callback(eventtime)
File "/home/pi/klipper/klippy/extras/idle_timeout.py", line 62, in timeout_handler
return self.check_idle_timeout(eventtime)
File "/home/pi/klipper/klippy/extras/idle_timeout.py", line 59, in check_idle_timeout
return …
```
> idle_timeout: Added a missing logging import

- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
Report decimal values for some of the TMC2208 register fields in
DUMP_TMC command if DECODE parameter is given. This helps in tuning and
diagnostics.
Sample output:
```
Send: DUMP_TMC STEPPER=stepper_a DECODE=1
Recv: // GCONF:          000001c4
Recv: // - I_scale_analog(ext VREF): 0
Recv: // - internal_Rsense:          0
Recv: // - en_spreadCycle:           1
Recv: // - shaft (inverse rot dir):  0
Recv: // - index_otpw:               0
Recv: // - index_step:               0
Recv: // - pdn_disable:              1
Recv: // - mstep_reg_select:         1
Recv: // - multistep_filt:           1
Recv: // - test_mode:                0
Recv: // GSTAT:          00000001
Recv: // - reset (driver was reset): 1
Recv: // - drv_err (error shutdown): 0
Recv: // - uv_cp (undervoltage):     0
Recv: // …
```
> tmc2208: Decode register fields in DUMP_TMC

- klippy/extras/pause_resume.py
- klippy/gcode.py
When a gcode is sliced using absolute extrusion the E axis gcode position needs to be captured after a pause so the offset can be correctly restored using G92.
@Hywelmartin @numanair, would you like to test these changes?  If so, slice an object using absolute extrusion, move the E-axis to unload during a pause, and make sure that it properly resumes extrusion. It works as it should in my tests.
Also included is a get_status() function that returns the paused state, it may be useful in combination with the status wrapper work.
> pause_resume: correctly handle absolute extrusion

- src/atsamd/Kconfig
- src/atsamd/adc.c
- src/atsamd/gpio.h
This enables ADC support on the samd51 port.
> adc: Enable ADC support for samd51 devices

- klippy/serialhdl.py
module: klippy/serialhdl.py
Set exclusive=True in serial.Serial commands to ensure they are opened in exclusive mode on Posix systems. This will help prevent misconfigurations when setting up multiple printers on the same host. Exclusive access is the default behavior on windows, and adding this flag won't affect them ( it is ignored ).
Resolves #1210 
Signed-off-by: Daniel Joyce <daniel.a.joyce@gmail.com>
> Enforce exclusive access on POSIX, this is default behavior on windows.

- docs/Debugging.md
- docs/Features.md
Latest benchmark with the armcm timer and sram matrix improvements.
> docs: Update duet2 benchmarks

- config/example-extras.cfg
- docs/G-Codes.md
- klippy/extras/heater_generic.py
- klippy/heater.py
Adds the ability to register a custom/generic heater through a new extra called heater_generic.
This takes a gcode_id that is reported by M105. Adds a new command to set the temperature for any heater using the syntax:
SET_HEATER_TEMPERATURE HEATER=<heater_name> TARGET=<target_temp>
Signed-off-by: John Jardine <john@gprime.net>
> Generic Heater Support

- config/example-extras.cfg
- docs/Config_Changes.md
- klippy/extras/bed_mesh.py
This request is separated into 3 commits:
* The first commit refactors how the fade_target is applied.  Rather than apply it to each lookup, its applied to the entire mesh after generation.  This made the math more tolerable when applying the fix for get_position()
* The second commit applies the fix for #1234 and #1252.   The factor in get_position() is now correctly calculated when fade is enabled.    Also included is an additional check in set_mesh to make sure that the maximum z adjustment applied is smaller than the fade distance.  This prevents a potential divide by zero when calculating the factor in get_position().
* The last commit applies config changes previously recommended.  I did not update config_changes.md, however if necessary I will do so.
Signed-off-by:  Eric Callahan …
> bed_mesh: fix get_position() when fade is enabled

- config/example-extras.cfg
- docs/G-Codes.md
- klippy/extras/filament_switch_sensor.py
- klippy/extras/pause_resume.py
- klippy/extras/virtual_sdcard.py
This PR contains an advanced implementation for filament detection.  Features include:
* Runout and insert detection.  By default the sensor module monitors the current print status and enables the correct detection mechanism based on the status (runout while printing, otherwise insert).
* Executes a user configured gcode script when an event is detected.  If the gcode is not configured the event is disabled.
* Allows for multiple underlying sensor implementations.  Includes a default switch based implementation.
* Will not allow multiple events to execute concurrently.
* Does not call a gcode handler from inside a reactor callback or button event.
* Allows the user to specify a minimum event delay time.  This is desirable to keep multiple events from executing too close together.
* …
> filament_sensor: advanced filament detection

- config/generic-duet2.cfg
Using the Duet2 config as a base for your own config will no longer turn
on all heaters and fans at full power during the (almost inevitable) MCU
shutdown that will occur during initial Klipper setup.
Signed-off-by: Benoit Miller <github@benoitmiller.ca>
> config: Fixed reversed heater/fan output pins

- config/example-extras.cfg
- config/generic-duet2.cfg
- docs/G-Codes.md
- klippy/extras/tmc2660.py
These two commits are aimed to bring the tmc2660 code more in line with the TMC2130 code.
- The mandatory sense_resistor configuration parameter is added, duet2 users should use 0.051 for this parameter
- Current calculation is changed to use that new sense_resistor value
- The code now uses the tmc2130 helper functions for register access.
~~I refrained from using `set_config_field` because it would cause incomaptibilities for a large portion of the tmc2660 config (since set_config_field does not support `get_choice`).~~
- During the implementation of this I also found the source of the bug that I was seing (drivers raising the current too late when coming out of idle). This bug should be gone now.
- This PR also implements INIT_TMC for the tmc2660 and adds SET_TMC_FIELD to set arbitrary …
> TMC2660 Updates

- config/example-delta.cfg
- config/example-extras.cfg
- docs/G-Codes.md
- docs/Manual_Level.md
- klippy/extras/probe.py
- klippy/extras/screws_tilt_adjust.py
- test/klippy/screws_tilt_adjust.cfg
- test/klippy/screws_tilt_adjust.test
SCREWS_TILT_ADJUST: Tool to help adjust bed screws tilt using Z probe
The following commands are available when the "screws_tilt_adjust" config
section is enabled:
SCREWS_TILT_CALCULATE: This command will invoke the bed screws
adjustment tool. It will command the nozzle to different locations
(as defined in the config file) probing the z height and calculate
the number of knob turns to adjust the bed level.
To enable this feature, one would determine the additional nozzle
coordinates near the screws and add them to the config file. For example,
it might look like:
[screws_tilt_adjust]
screw1: -5,30
screw1_name: front left screw
screw2: 155,30
screw2_name: front right screw
screw3: 155,190
screw3_name: rear right screw
screw4: -5,190
screw4_name: rear left screw
horizontal_move_z: 10. …
> "screws_tilt_adjust" extra tool to help adjust bed screws tilt using Z probe

- klippy/extras/display/menu.cfg
Currently, `input_min`/`input_max` settings in menu for moving toolhead are different for 10mm, 1mm and 0.1mm moves. Propose change to same 200.0 `input_max` value of the 10mm XYZ move option. Also update extruder move `input_min` and `input_max` settings to -250 to 250 of 10mm setting.
One should be able to access the same range regardless of the step value. Also current settings can cause unexpected toolhead movement. For example, you can move x to 200 via the 10mm step menu, then if you decide to adjust position via 1mm menu, previous `input_max` setting will move head at least 100mm down to 100.
Reported in issue: https://github.com/KevinOConnor/klipper/issues/1334
Signed-off-by: Frank Kang <amblidex@outlook.com>
> menu: set input ranges for moving toolhead to same value

- klippy/extras/display/menu.cfg
- klippy/gcode.py
Changes the move menus to show current position based on gcode
position. This allows gcode offsets and bed leveling offsets
to be taken into account, and prevents unexpected toolhead
movements when moving it using the menu.
Signed-off-by: Robert Konklewski <nythil@gmail.com>
> menu: Show current positions based on gcode positions

- config/example-extras.cfg
- klippy/extras/bed_mesh.py
Adds parameter for bed meshes to be adjusted relative to a probed point
during calibration. This allows the probe z offset to be ignored for
probes that are not stable over time (for example, the thermal drift of
inductive probes). An endstop other than the probe is then necessary to
determine the bed-nozzle offset.
> bed_mesh: enable relative offset bed meshes

- klippy/configfile.py
Allows configuration files to include other configuration files using `[include filename.cfg]` syntax.  Klippy loads include files in the position of the include header; subsequent definitions override included values.
Supports wildcards (e.g. `[include macros/*.cfg]`).  Allows included files to include other files but blocks recursion.
Resolves #1145
Example `printer.cfg`:
```ini
[include klipper/config/avrsim.cfg]
[printer]
max_velocity: 750
max_accel: 4500
[include macros/*.cfg]
```
Signed-off-by: Greg Lauckhart <greg@lauckhart.com>
> configfile: Add "include" support

- docs/G-Codes.md
- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
Port over the SET_TMC_CURRENT and SET_TMC_FIELD commands from the tmc2660 driver for better feature parity across TMC drivers
Signed-off-by: Frank Kang <amblidex@outlook.com>
> tmc2130, tmc2208: add SET_TMC_CURRENT and SET_TMC_FIELD commands

- config/example-extras.cfg
- docs/Config_Changes.md
- klippy/extras/temperature_fan.py
min_speed should be the minimum speed.  at the moment if below min_speed the speed will be set to 0 instead of the specified min.
Signed-off-by: Douglas Hammond wizhippo@gmail.com
> Fix.  Temperature fan min speed should be used

- docs/Benchmarks.md
Pretty strange results for more than one stepper, but I've run tests few times and results the same.
> STM32F0 benchmarks

- src/stm32f1/adc.c
The sampling time of the ADC was too slow (239 ADC clock cycles), causing the reading of the next ADC channel to have cross talk as per issue #1261. Sampling time updated to 41 ADC clock cycles.
Signed-off-by: Marco D'Alessio <marco@wrecklab.com>
> module: STM32F1 - ADC

- config/example-extras.cfg
- klippy/extras/display/uc1701.py
Some users report UC1701 displays that are barely visible using the default initialization sequence.  This pull request makes the electronic volume (contrast) register configurable.
> uc1701:  make contrast configurable

- config/generic-replicape.cfg
- klippy/extras/replicape.py
The servo pins (P9_14/P9_16) are muxed as hardware pwm and can't be controlled by the PRU. Implement support for hardware pwm in the linux host mcu via sysfs. Verified to to work with a genuine BLTouch smart v3.0.
> extras/replicape: support servos with linux host hardware PWM

- src/lpc176x/internal.h
- src/lpc176x/main.c
- src/lpc176x/usbserial.c
Fixes GitHub Issue #1499. Resolves USB hang by forcing a minimum
USB disconnection time at boot.
lpc176x: refactor usbserial to use udelay helper.
>  lpc176x: force minimum usb disconnect time

- config/example-extras.cfg
- klippy/extras/buttons.py
- klippy/extras/display/menu.py
Development for #898
This is **work in progress**
Tried to make initial support for ADC buttons.
In `[display]` section you can specify pins for the menu.
Now it supports the following format for analog (ADC) buttons.
`up_pin: analog15(100,200)`
`up_pin: pin_name(min, max)`
`min` and `max` are concrete button adc value range.
These are always integers.
The max ADC range can be set `adc_range: 1024` attribute (default is 1024).
Internally klipper has ADC value range from 0.0 to 1.0 and this will convert the value to an integer. 
Only these pins allow ADC input
```ini
#click_pin:
#back_pin:
#up_pin:
#down_pin:
#kill_pin:
```
It's not fully tested. 
@KevinOConnor Could you check `buttons.py` ADC part.
Maybe you have some comments or suggestions.
Signed-off-by: Janar Sööt …
> initial support for adc buttons

- config/example-extras.cfg
- klippy/extras/virtual_sdcard.py
more virtual sd options as requested in #1304 
also added some further filtering to ensure only `.gcode` files are listed somewhat in response to discussion of gcode not really handling directories in #1303
> virtual_sdcard: consistent sorting, further filtering to workable types.

- klippy/extras/tsl1401cl_filament_width_sensor.py
The parameter to the M221 command should be the ratio of the nominal to
measured filament *area*, rather than the ratio of the *diameter*. Since we
are taking the ratio, most of the area calculation cancels out. Fixes #1535.
(Note: I don't actually have one of these sensors, I just noticed it was wrong)
Signed-off-by: Len Trigg <lenbok@gmail.com>
> tsl1401cl_filament_width_sensor: Fix incorrect flow adjustment calculation

- klippy/extras/quad_gantry_level.py
In particular trying to keep the output from a single quad_gantry_level
so that it fits in the octoprint terminal window without the need to
scroll
in short this PR simply collapses 10 lines of output  down to 4 lines: 
```
Recv: // Gantry-relative probe points:
Recv: // 0: 2.605000 1: 2.605000 2: 2.605000 3: 2.610000
Recv: // Actuator Positions:
Recv: // z: 2.598669 z1: 2.608424 z2: 2.597621 z3: 2.618644
```
> quad_gantry_level: More compact info messages

- config/example-extras.cfg
- klippy/extras/quad_gantry_level.py
Idea from @doowrednu: 
safety feature that prevents quad_gantry_level from trying to do a
correction that might break things - if your probe fires early for
whatever reason and tries to do an 8mm correction in one corner instead
we abort if a correction is over a configurable limit by default 4mm
configurable via `max_adjust` parameter in the config
> quad_gantry_level: Limit maximum adjustment

- config/printer-creality-ender5-2019.cfg
This config is based on the existing Ender 3 example config but some of the directions for the steppers have been reversed and XY homing has been slowed down. It works for me so far, but feel free to modify.
Might resolve Issue #1591
Signed-off-by: Billy Jones <billyajones@gmail.com>
> config: Add Creality Ender 5 2019

- src/spi_software.c
Fixes software spi mode by properly storing config setting.
> spi_software: save mode setting in config structure.

- klippy/extras/display/menu.cfg
"Feed Filament" menu item value was off-screen that made this item useless. So I changed its name to just "Feed". Users shall easily guess that this item is for filament feeding because this item is located in "Filament" menu.
Signed-off-by: Alexander Fadeev <alfsoft@gmail.com>
> Changed Menu item "Feed Filament" name

- klippy/extras/bed_mesh.py
- klippy/extras/bed_tilt.py
- klippy/extras/delta_calibrate.py
- klippy/extras/probe.py
- klippy/extras/quad_gantry_level.py
- klippy/extras/screws_tilt_adjust.py
- klippy/extras/z_tilt.py
- quad-gantry level require 4 probe points exactly instead of minimum of 3. 
- z-tilt minimum points set to 2 instead of 3. 
"The z_tilt_adjust was coded to require 3 points because the original
intent was for railcore-xl and voron.  Since then, a number of users
have started using z_tilt_adjust for prusa i3 style printers with dual z
steppers.  That's fine, but we just haven't gotten around to removing
the superfluous check in the code." -- Kevin O'Connor
Quad Gantry level, the code expects 4.
> Adjust some minimum points assertions for ProbePointsHelper 

- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
This avoids crashing clipper if user entered invalid field name.
Signed-off-by: Artem Belevich <artemb@gmail.com>
> SET_TMC_FIELD: Check field name validity.

- klippy/extras/pause_resume.py
Use the new SAVE_GCODE_STATE and RESTORE_GCODE_STATE gcodes to move back to the correct position after resuming from a pause.  Also use Octoprint's "action:paused" and "action:resumed" action commands.  These commands prevent Octoprint from sending additional gcodes such as M0.
> pause_resume: Use built in gcodes for saving and restoring state.

- docs/G-Codes.md
- klippy/extras/idle_timeout.py
This helps resolve issues where the idle timeout turns off heater/motors during a long PAUSE or while a chamber is heating.  The user can temporarily increase the idle_timeout in a macro then restore the original idle timeout when ready.
> idle_timeout: Add SET_IDLE_TIMEOUT gcode

- config/example-delta.cfg
- config/example-extras.cfg
- config/kit-voron2-250mm.cfg
- config/kit-zav3d-2019.cfg
- config/printer-tevo-flash-2018.cfg
- docs/Delta_Calibrate.md
- docs/Probe_Calibrate.md
- klippy/extras/bed_screws.py
- klippy/extras/bltouch.py
- klippy/extras/manual_probe.py
- klippy/extras/manual_stepper.py
- klippy/extras/probe.py
- klippy/gcode.py
- klippy/homing.py
- test/klippy/screws_tilt_adjust.cfg
This series moves the "samples" config option (and similar) from the DELTA_CALIBRATE, BED_MESH_CALIBRATE, etc. commands into the main Probe class.  Thus, all probe commands (eg, PROBE and PROBE_CALIBRATE) gain the ability to perform multi-sampling.
Unfortunately, this changes the config file layout, so anyone that was using the multi-sampling capability will need to modify their config files on an upgrade.
@rmcbc, @arksine, @sprk-nl - FYI.
-Kevin
> Move probe multi-sampling capability into main PROBE handling

- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
- test/klippy/tmc.cfg
- test/klippy/tmc.test
This is a large series intended to refactor the code in tmc2130.py, tmc2208.py, tmc2660.py, and tmc5160.py.  The goal is to make it easier to support future drivers (such as the tmc2209) and to make it easier to support other types of communication methods (such as tmc5160 uart mode, tmc2208 via analog mux).
@FHeilmann , @Stephan3 - would you be able to verify that the tmc5160, tmc2660, and tmc2130 continue to work properly?
Thanks.
-Kevin
> Refactor tmc drivers

- klippy/extras/quad_gantry_level.py
- klippy/extras/z_tilt.py
This pulls out the two patches to unify the low-level z steppers that was discussed in PR #1658.
-Kevin
> Use the same low-level Z adjustment code in z-tilt and quad-gantry-level

- config/example-extras.cfg
- klippy/extras/probe.py
- klippy/extras/quad_gantry_level.py
- klippy/extras/z_tilt.py
Support retrying QUAD_GANTRY_LEVEL and Z_TILT_ADJUST a configurable number of times to a configurable tolerance both in the config or as parameters. 
By default keeps original behavior of no retries.
Adds parameters RETRIES and RETRY_TOLERANCE to Z_TILT_ADJUST and QUAD_GANTRY_LEVEL gcode. 
Adds config options retries and retry_tolerance to `[z_tilt]` and `[quad_gantry_level]`
Issues an error if we are getting worse intead of approaching tolerance
Issues an error if retries were requested but we did not reach the tolerance in the specified number of retries
> Automatic retry for QUAD_GANTRY_LEVEL and Z_TILT_ADJUST

- docs/G-Codes.md
- klippy/extras/pause_resume.py
This pull request adds  a `CLEAR_PAUSE` gcode which clears the paused state without restoring the saved gcode state.  This is useful in the event that a user decides to cancel a print after a PAUSE.
> pause_resume:  Add CLEAR_PAUSE gcode

- config/example-extras.cfg
- docs/Config_Changes.md
- docs/G-Codes.md
- docs/skew_correction.md
- klippy/extras/skew_correction.py
As previously discussed, all configuration options have been removed from printer.cfg and are now available via a SET_SKEW gcode:
```
SET_SKEW XY=ac,bd,ad XZ=ac,bd,ad YZ=ac,bd,ad CLEAR=0|1
```
I added the CLEAR parameter to make zeroing the skew settings easier and more forthright.
I also added profile management similar to [bed_mesh]:
```
SKEW_PROFILE LOAD=name SAVE=name REMOVE=name
```
My thought was that it would be easier for users to load a saved profile their start gcode. 
> skew_correction:  move configuration to gcode

- klippy/extras/gcode_macro.py
This makes possible to dump all `printer` variables to the log and host.
It goes thru all the printer object variables and in case of a function, it tries to show the content of `__doc__` as a description.
The output shows variables as they can be used  in `gcode_macro`
_The `do` aka jinja2 expression-statement extension adds a simple do tag to the template engine that works like a variable expression but ignores the return value._
It can be used in `gcode_macro` as jinja2 statement by using `do` tag
```ini
[gcode_macro DUMP]
gcode:
{% do printer.action_dump() %}
```
or like jinja2 expression, then it returns empty string for gcode
```ini
[gcode_macro DUMP]
gcode:
{printer.action_dump()}
```
> gcode_macro: dump all variables

- config/example-extras.cfg
- docs/Command_Templates.md
- docs/G-Codes.md
- klippy/extras/delayed_gcode.py
This PR adds the aforementioned [delayed_gcode] module.  Apart from the standard docs, I added detailed documentation to Command_Templates.md.  I thought that this would be a better location for it rather than creating a new markdown file.
> delayed_gcode: Support for non-blocking delayed gcode execution

- klippy/extras/buttons.py
- src/buttons.c
This should solve the issue where inverted buttons are not properly initialized on the host when the pin is low at startup.
> buttons: initialize mcu buttons based on inverted state

- docs/G-Codes.md
- klippy/extras/filament_switch_sensor.py
This pr includes several small fixes to the filament_switch_sensor module:
- The first patch removes a stale toolhead attribute in the BaseSensor class.  Since the toolhead is no longer required by the BaseSensor, its entire handle_ready function could be removed.
- The second a patch appends M400 to the event gcode.  This keeps the BaseSensor's "event_running" attribute set to true until all moves are complete, preventing an additional event from triggering while the printer is responding to the previous event.
- The last patch adds a "TOGGLE_FILAMENT_SENSOR" gcode.  Some users prefer to unload/remove filament while the extruder gears are still moving.   To prevent a runout event from triggering it is necessary that the user manually toggle the sensor off at the  beginning of the unload …
> filament_switch_sensor:  misc fixes

- klippy/chelper/__init__.py
- klippy/chelper/stepcompress.c
- klippy/chelper/stepcompress.h
- klippy/extras/bltouch.py
- klippy/extras/probe.py
- klippy/extras/query_endstops.py
- klippy/extras/tmc.py
- klippy/homing.py
- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/delta.py
- klippy/kinematics/polar.py
- klippy/mcu.py
- klippy/reactor.py
- klippy/serialhdl.py
- klippy/toolhead.py
This series implements a new internal mechanism for homing and probing.
Currently, the Klipper code implements "homing moves" via a four step system: enable endstop checking, buffer the entire movement into the micro-controllers, start the movement, clear the mcu movement buffer on each endstop trigger.  This system is not particularly flexible - it causes problems when a movement exceeds the buffer space in the micro-controller and it causes problems on slower host machines (where the host may not be able to generate and compress all the steps for the movement before the movement is scheduled to start).
This pull request changes the homing system to use a new system: enable endstop checking, buffer the entire movement in the host look-ahead buffer, drip feed the moves to the …
> Rework homing code to use new host based "drip feed" system

- config/generic-duet2-duex.cfg
- config/generic-duet2.cfg
- test/klippy/printers.test
@FHeilmann - what do you think about separating out the Duex config from the main generic-duet2.cfg example config file?  For Duet2 Eth/Wifi users without a Duex, it could be a little overwhelming to get through such a large config.
-Kevin
> Breakout Duet2 Eth/Wifi and Duetx example config files

- klippy/extras/display/menu.cfg
use SET_GCODE_OFFSET's MOVE=1 parameter in the z offset menu.
Less confusing for people who think nothing happened.
> menu: use MOVE=1 for offset_z menu

- config/generic-duet2-duex.cfg
Due to some misreading of the Duet2 schematic and CoreNG code on my part, the pin assignments for the E6 drive on the duex were incorrect. This PR fixes them.
Sources used:
https://github.com/T3P3/Duet/blob/master/Duet2/Duet2v1.04/DuetWifiv1.04a_Schematic.pdf
http://ww1.microchip.com/downloads/en/devicedoc/atmel-11157-32-bit-cortex-m4-microcontroller-sam4e16-sam4e8_datasheet.pdf
https://github.com/dc42/CoreNG/blob/master/variants/duetNG/variant.cpp
Sorry about the inconvenience!
-Florian
> config: Fix pins for E6 in generic-duet2-duex.cfg

- config/example-extras.cfg
- klippy/extras/safe_z_home.py
- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/delta.py
- klippy/kinematics/none.py
- klippy/kinematics/polar.py
- klippy/kinematics/winch.py
My 2nd attempt at this extra. I removed the illegal peeks at private members, and added a `get_status()` call to all kinematics classes to pull the homed status for each axis, as well as the axis limits.
This is used to make sure the zhop does not get executed if we know that doing so would exceed the printer limits.
I tried to make sure the shape of `get_status()` is consistent across all kinematics. If this is not desired and, e.g. polar kinematics should only return 2 limits instead of 3, I can change it.
Bests,
Florian
> Add Safe Z Home extra (2nd attempt)

- config/example-extras.cfg
- config/generic-bigtreetech-skr-v1.3.cfg
- config/generic-duet2-maestro.cfg
- config/generic-rambo.cfg
- config/generic-ramps.cfg
- config/sample-lcd.cfg
- klippy/console.py
- klippy/extras/board_pins.py
- klippy/extras/bus.py
- klippy/extras/replicape.py
- klippy/mcu.py
- klippy/pins.py
This is a proposal to add a module for generic board specific pin aliases.  This also updates a few config files to use these aliases for defining the EXP1/EXP2 lcd display adapter plugs.
It's becoming increasingly difficult to track all the various LCD configurations.  It is hoped that adding aliases may make this a little easier.
@FHeilmann - FYI - this is very similar to your past PR #848.
Feedback welcome.
-Kevin
> Add support for board specific pin aliases

- klippy/configfile.py
module: CONFIGFILE, Fixes the error raised when including a missing file
**before:**
```python
Unhandled exception during connect
(...)
File "/home/pi/klipper/klippy/configfile.py", line 167, in _resolve_include
raise error("Include file '%s' does not exist", include_glob)
TypeError: __init__() takes at most 2 arguments (3 given)
Internal error during connect: __init__() takes at most 2 arguments (3 given)
```
**after:**
```
Config error
(...)
File "/home/pi/klipper-dev/klippy/configfile.py", line 167, in _resolve_include
raise error("Include file '%s' does not exist" % (include_glob,))
Error: Include file '/home/pi/missing_file.cfg' does not exist
```
Signed-off-by: Julien Lirochon <julien@lirochon.net>
> Fix the exception raised when an included file is missing

- config/example-extras.cfg
- klippy/extras/filament_switch_sensor.py
This patch adds a configurable delay between dispatch of the pause command and execution of the runout_gcode.  This delay should eliminate a possible race condition in the event that the switch is triggered just after Klipper acknowledges a move.
> filament_switch_sensor: Add delay after pause dispatch

- klippy/extras/samd_sercom.py
samd_sercom: fix pin enumeration error when mcu is specified
Previously, when a sercom pin specified the mcu (myname:PIN), it would result in a pin enumeration error.
Signed-off-by: John Jardine <john@gprime.net>
> samd_sercom: fix pin enumeration error when mcu is specified

- config/example-extras.cfg
- docs/Config_Changes.md
- klippy/extras/safe_z_home.py
This PR updates the feature introduced with PR #1866. It adds the possibility to move X and Y axis back to their previous positions and hops only when a hop is necessary.
I tested it on an AM8 with a bltouch probe. I don't know about other than cartesian kinematics so this probably needs some review from other users with more knowledge about those other kinematics.
Signed-off-by: Nils Friedchen <Nils.Friedchen@googlemail.com>
> Safe Z Home improvements

- config/generic-fysetc-f6.cfg
module: IMPROVED FYSETC F6 CONFIGURATION
Since the previous config file was laid out only for TMC2208 drivers and was missing most other pins, I made a comprehensive configuration file, with hardware names for all available functionality.
Signed-off-by: Tobias Weiß t.weiss@bk.ru
> IMPROVED FYSETC F6 CONFIGURATION

- docs/Probe_Calibrate.md
- klippy/extras/probe.py
The documentation recommends checking the distance between maximum and minimum values, and it was a bit tedious to calculate at the end of each result when you are tweaking your probe parameters.
If i am not mistaken the distance between the maximum and the minimum value of a series is called the range.
I added `range` to probe accuracy results and updated the documentation.
Signed-off-by: Julien Lirochon julien@lirochon.net
> Add range to probe accuracy results

- docs/G-Codes.md
- docs/prints/square_tower.scad
- docs/prints/square_tower.stl
- klippy/extras/tuning_tower.py
- klippy/toolhead.py
FYI, just something I've been looking at recently.  This series introduces a TEST_PRESSURE_ADVANCE command.  This command will setup the basic requirements for testing pressure advance (`SET_VELOCITY_LIMIT ACCEL=500 SQUARE_CORNER_VELOCITY=1` and `SET_PRESSURE_ADVANCE ADVANCE_LOOKAHEAD_TIME=0`) and then arrange to set a new pressure advance value for each Z layer.  So, one could issue a `TEST_PRESSURE_ADVANCE INCREMENT=0.05` command, print an object, and the resulting object would have the pressure advance setting changed such that every 1mm of the print had .05 additional pressure advance.  Thus a "pressure advance testing tower".
I've also added a docs/prints/square_tower.stl file to test with.
My opinion of this testing method is a little mixed.  It's certainly easier to run the test, …
> Pressure advance testing tower

- config/example.cfg
- klippy/extras/fan.py
Below min_power the fan will be turned off. When configured correctly this
can prevent stalling, which may lead to overheating and failed fans.
Signed-off-by: Nicholas Seckar <nseckar@gmail.com>
> Add min_power option for fans

- config/example-extras.cfg
- klippy/extras/safe_z_home.py
As discussed in #2020, PR #1970 introduced a new parameter, changing the default behavior of the safe_z_home-module. To avoid unexpected changes, the value of the `move_to_previous`-parameter is now defaulted to `False`.
@FHeilmann, @ezrec - FYI.
Signed-off-by: Nils Friedchen <Nils.Friedchen@googlemail.com>
> safe_z_home: Fix unintended change in default behavior

- klippy/extras/bed_mesh.py
A minor bug fix to correct the config errors raised in the parse_pair() helper.  Resolves #2080 and #2035.
> bed_mesh: configuration error bug fix

- scripts/install-ubuntu-18.04.sh
Set KLIPPER_USER to $USER instead of "octoprint".
Signed-off-by: Nathan Chiu <nhchiu2009@gmail.com>
> scripts: Use current username in install-ubuntu-18.04.sh

- klippy/chelper/__init__.py
- klippy/chelper/itersolve.c
- klippy/chelper/itersolve.h
- klippy/chelper/kin_cartesian.c
- klippy/chelper/kin_corexy.c
- klippy/chelper/kin_delta.c
- klippy/chelper/kin_extruder.c
- klippy/chelper/kin_polar.c
- klippy/chelper/kin_winch.c
- klippy/chelper/list.h
- klippy/chelper/trapq.c
- klippy/chelper/trapq.h
- klippy/extras/force_move.py
- klippy/extras/manual_stepper.py
- klippy/extras/z_tilt.py
- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/delta.py
- klippy/kinematics/extruder.py
- klippy/kinematics/none.py
- klippy/kinematics/polar.py
- klippy/kinematics/winch.py
- klippy/mcu.py
- klippy/stepper.py
- klippy/toolhead.py
This series is a large backend rework of the Klipper kinematics.  The current code generates the steps for each move, one move at a time.  This pull request changes the underlying step generation code to generate steps based on a time range.  Each host stepper object is associated with a list of moves, and steps are then generated from the moves on that list.  A step generation time range may be part of a move, multiple moves, or some combination.
This change should fix #1460.  It will also make it much easier to merging PR #1997.
-Kevin
> Rework step generation to use a C based trapezoidal velocity queue

- klippy/extras/tmc2130.py
- klippy/extras/tmc5160.py
This PR changes the behavior if a user attempts to set a `RUN_CURRENT` lower than the `HOLD_CURRENT` via `SET_TMC_CURRENT`.
In it's current state, the `get_float` call will cause an error if `run_current` is below `hold_current`, causing the printer to shut down and running print jobs to be canceled. With this PR, a warning is printed instead, and the GCode command is ignored.
> tmc2130,5160: warn if run current below hold current

- config/example.cfg
- klippy/extras/fan.py
Large increases in fan speed can suffer from acceleration lag, so this
change kick starts the fan for a change of 50% or more in the same way
that starting the fan from 0% does.
> FAN: Kick start fan when the increase is more than 50%

- config/printer-anycubic-kossel-plus-2017.cfg
Default parameters for Anycubic delta linear plus have to be changed. Current parameters are incorrect and during calibration may cause damage to the printer, so it is rather important to change them to correct values (copied from Marlin firmware and tested on my printer).
Also I uncommented "heather bed" because all currently sold printers have this feature. Pids are calculated on my printer - I believe that they will work well for others as starting values.
> fixes in anycubic delta plus default config file

- klippy/extras/tmc2130.py
TMC5160 configuration is using same MCU_TMC_SPI class as TMC2130. MCU_TMC_SPI should use defined register mapping instead of Registers globals variable when set_register is called.
> tmc2130: use local variable instead of global Registers in MCU_TMC_SPI

- config/example-extras.cfg
Update to example-extras.cfg
In the default_parameter description in _G-Code macros and events_ add instructions on how to call a macro containing a default parameter with a different, non-default, parameter included in the command.
Signed-off-by: David Smith davidosmith@gmail.com
> Add example for including a parameter in a macro call

- config/example-extras.cfg
- config/sample-idex.cfg
- config/sample-multi-extruder.cfg
- docs/Config_Changes.md
- docs/G-Codes.md
- klippy/gcode.py
- klippy/kinematics/extruder.py
- test/klippy/dual_carriage.cfg
This is a proposal to remove the built-in `T0`, `T1`, ... G-Code commands.  This would require users with multiple extruders to update their configs to add `[gcode_macro T1]` macros that call a new `ACTIVATE_EXTRUDER EXTRUDER=extruder1` command.
There are two main reasons for this proposal:
* The current `T1` style support is not flexible enough to handle the requirements of some printers.  In particular, there is a desire to create "virtual extruders" that alter the behaviour of an existing extruder.  For example, the "mmu2" could be thought of as having several virtual extruders (eg, `T1`, `T2`, `T3`, `T4`) that switch filaments on a single hardware extruder.  Implementing this functionality via individual `T1` macros is notably easier than working with the existing `Tn` g-code support. …
> Remove multi-extruder T0/T1/... commands

- docs/Command_Templates.md
- klippy/extras/temperature_sensor.py
- klippy/heater.py
This gives access to a list of available heater names in gcode macros as printer.heater.available_heaters (Edited after change of implementation, see conversation below)
Signed-off-by: Simon Kühling <mail@simonkuehling.de>
> heater: Add get_status() function

- config/generic-fysetc-s6.cfg
- src/lpc176x/Kconfig
- src/stm32/Kconfig
Version 2.
Does not include the pins for the UART and I2C connectors.
Also fixed the "Mhz" spelling in two files, though I wanted that to go into a seperate pull request.
Signed-off-by: Tobias Weiß t.weiss@bk.ru
> Fysetc S6 generic configuration

- config/example-extras.cfg
- docs/Command_Templates.md
Documentation
Add statements about restriction in numbers used in G-Code Macro Names.  Add statement about restriction of character case in variable names.  Added example of updating variable from other macros.
See issue #2307 and #2249 
Signed-off-by: David O Smith <davidosmith@gmail.com>
> Docs update macro naming, variable naming and usage

- config/example-extras.cfg
- config/sample-macros.cfg
- klippy/extras/bme280.py
- klippy/heater.py
- src/avr/i2c.c
- src/i2ccmds.c
- src/linux/Kconfig
- src/linux/Makefile
- src/linux/gpio.h
- src/linux/i2c.c
In addition to support for the BME280, this PR contains i2c read support for AVR platforms and i2c support for the linux mcu.  The sensor implementation has been tested using the above platforms as well as the SAM3X with an Arduino Due.
Below is the example configuration I used to test the sensor connected to a Raspberry Pi:
```
[temperature_sensor chamber]
sensor_type: BME280
i2c_mcu: linux
i2c_bus: i2c.1
gcode_id: AMB
[gcode_macro query_bme280]
default_parameter_SENSOR: bme280 chamber
gcode:
{printer.gcode.action_respond_info(
"Temperature: %.2f C\n"
"Pressure: %.2f hPa\n"
"Humidity: %.2f%%" % (
printer[SENSOR].temperature,
printer[SENSOR].pressure,
printer[SENSOR].humidity))}
```
The temperature will show up in responses to M105 and the above macro can be used to query humidity and …
> bme280:  Add support for BME280 environmental sensor

- src/lpc176x/Kconfig
- src/lpc176x/gpio.h
- src/lpc176x/internal.h
- src/lpc176x/spi.c
lpc176x: Add ssp1 SPI
Makerbase MKS SGEN L board uses ssp1 on pins P0.8, P0.9 and P0.7 for display connection.
Signed-off-by: Andrey Kovalev <aka@pxe.ru>
> Lpc176x ssp1

- config/generic-bigtreetech-skr-v1.4.cfg
Added a configuration for latest skr v1.4 board from bigtreetech.
Configuration is tested based on skr v1.4 turbo on ender 5 with bmg extruder, tmc2208.
Signed-off-by: John Yan john.yan1019@gmail.com
Signed-off-by: Kevin O'Connor kevin@koconnor.net
> config: Add Skr v1.4 configuration

- klippy/extras/delayed_gcode.py
the define for UPDATE_DELAYED_GCODE had a misdirected definition and was showing code base instead of help text when "help" typed in terminal
signed off by: David Smith <davidosmith@gmail.com>
> Fix definition reference for UPDATE_DELAYED_GCODE

- docs/G-Codes.md
- klippy/extras/stepper_enable.py
STEPPER_DISABLE extended G-Code for individual stepper disabling
Using command `STEPPER_DISABLE STEPPER=<config_name>` individual steppers can be disabled
Signed-off-by: David Smith <davidosmith@gmail.com>
> Add STEPPER_DISABLE gcode command to disable individual steppers

- config/example-extras.cfg
- klippy/extras/homing_heaters.py
- klippy/heater.py
- klippy/homing.py
This is **part1** of the **BLTOUCH-HIGH-SPEED** PR split (see #2309).
**OVERVIEW**
For those that choose to home or probe with any heaters (either nozzle(s) or bed) **turned on**, any power-supply or wiring situation or a probe that is sensitive to the heater PWM causing any kind of noise or supply variations can profit from having the heaters **turned off for the duration of the homing or probing movement**. As soon as the endstop/probe is triggered, the heaters will be turned on again.
**COMMENTS**
Alternatively, one could use GCODE macros to surround the relevant commands by heaters-off and heaters-on commands. The adavantage of this PR is that during a bed level, for example, there would be at least some heating in between the probing movements to keep the bed at the desired …
> BLTHS PART1 HEATERS (turn off heaters during homing/probing)

- config/example.cfg
- klippy/homing.py
- klippy/stepper.py
This is **part2** of the **BLTOUCH-HIGH-SPEED** PR split (see #2309).
**OVERVIEW**
Similarly to the `lift-speed` parameter for probe related config-sections, this enables the speed of the retract-move between homing moves to be configurable.
**COMMENTS**
The speed gain to be achieved here is minimal. For a BLTouch in HIGH-SPEED-MODE, though, it is advantageous to lift up as fast as possible after a homing trigger, even if the downward movement on homing is slow.
**CONFIG**
Add `homing-retract-speed: nnn` to the `[stepper-...]` section of `printer.cfg`
Note: This works for any axis, but typically it would be used for stepper-z
```
[stepper-z]
homing-retract-speed: nnn
```
Note: for a BLTouch type probe being used for Z-axis homing, a high upward retract speed is advantageous. This value is …
> BLTHS PART2 HOMING RETRACT (Ability to set retract speed between homing moves)

- config/printer-wanhao-duplicator-9-2018.cfg
- config/printer-wanhao-duplicator-9.cfg
Also applies to the Monoprice Maker Pro MK1.
This config is based on the version from Chris Barnes (https://www.facebook.com/Jarannis)
found on https://pastebin.com/raw/wm8PQezy. This config was mostly working and I
only had to change a few things:
- updated key names for min_point and max_point to mesh_min and mesh_max
- enabled PID control
- tweaked bounds to allow movement during mesh leveling
- removed all comments
- decreased homing speed slightly
- sane bed mesh sample defaults
Signed-off-by: Matt Shirley <mdshw5@gmail.com>
> config: Add Wanhao Duplicator 9 MK1

- klippy/extras/filament_switch_sensor.py
As suggested in #2505, the BaseSensor has been replaced with a RunoutHelper.  Filament Sensor implementations may instantiate a RunoutHelper object and call its "note_filament_present" method with the filament state (True if present, False otherwise).  To initialize filament state the first call to note_filament_present should be no later than 2 seconds after the printer enters the "Ready" state.
This PR has no impact on configuration or behavior of the filament_switch_sensor.
> filament_switch_sensor:  Replace BaseSensor with RunoutHelper

- klippy/extras/display/menu.cfg
Issue:
Navigate to the move menu (LCD Menu).
Select and deselect axis e
From this point all movements are performed only with F240
Solution:
Define a fixed F Value for all other axis. F2400 for X and Y, F240 for Z appears with as a good value
Signed-off-by: Christian Schnellrieder schnellrieder.cs@gmail.com
> Set force for move actions

- config/printer-wanhao-duplicator-9-2018.cfg
This is a small change I forgot to make when copying my config to this template. Ready to merge if tests are passing.
Signed-off-by: Matt Shirley <mdshw5@gmail.com>
> config: add missing bed_mesh mesh_min coordinates

- config/printer-lulzbot-taz6-2017.cfg
Support probing the corner washers for the bed tilt using G29, flesh out the rest of the configuration for the display, and add support for the Aerostruder (commented out by default).
> config: Update TAZ6 configuration

- klippy/chelper/__init__.py
- klippy/chelper/serialqueue.c
- klippy/chelper/serialqueue.h
- klippy/extras/bus.py
- klippy/extras/tmc_uart.py
- klippy/mcu.py
- klippy/serialhdl.py
- klippy/stepper.py
- src/basecmd.c
This change updates the low-level communication code to support notifying the main host code on the successful acknowledgement of a command sent to the micro-controller.  This is most useful to eliminate two low-level timing issues causing errors on the BL-Touch as described at: https://github.com/KevinOConnor/klipper/issues/1938#issuecomment-529736513
`cd ~/klipper ; git fetch ; git checkout origin/work-cmdnotify-20200216 ; sudo service klipper restart`
The current Klipper code is using the timing of messages to determine if a response to a query was received or not.  In some rare situations, this leads to false positives and the code retransmits the query, which delays the processing of the response.  The new code on this branch uses the ordering of message responses and message …
> Improvements to low-level message response detection

- config/example-extras.cfg
- docs/BLTouch.md
- docs/G-Codes.md
- klippy/extras/bltouch.py
**Revised version of this header see below**
**the following is outdated:**
**BTLOUCH V3.0/V3.1 Enable 5V/OD mode set commands**
Not urgent - I wanted to submit this in case it is ever needed
A BLTouch Smart V3.0 or V3.1(+) supports selection of an output mode, 5V or OPEN DRAIN. A V3.1 can even store this setting in its internal EEPROM. These probes start up in OPEN DRAIN mode by default (for safety). 
If a controller board **NEEDs** 5V mode **AND** it is **5V tolerant** on its input signal line, one can make use of this feature. Otherwise one should **not** use this feature. _This is for the experts only._
So there are some new `BLTOUCH_DEBUG` commands, and a new printer config paramter to select (and store) the desired output mode.
The new `BLTOUCH_DEBUG' commands would then be:
``` …
```
> BTLOUCH V3.0/V3.1 Enable 5V/OD mode set commands

- klippy/chelper/itersolve.c
- klippy/chelper/itersolve.h
- klippy/chelper/stepcompress.c
- klippy/chelper/stepcompress.h
- klippy/toolhead.py
It is not currently valid to run the tmc2208 drivers in "standalone mode" with Klipper due to what appears to be an issue in how the tmc2208 handles direction changes.  It is believed that a step followed by a direction change followed by a step in the opposite direction can cause it to experience an "over current" event if the two step pulses occur in a small time period.  This is described in the FAQ at https://www.klipper3d.org/FAQ.html#my-tmc-motor-driver-turns-off-in-the-middle-of-a-print .
This PR adds code to filter out rapid step+dir+step sequences.  This should, ideally, prevent issues with the tmc2208 - both when they are in standalone mode and in a "stealthchop" mode configured via the uart interface.  Some other stepper drivers have been observed to not handle rapid direction …
> Implement tmc2208 step+dir+step filter

- config/generic-mks-sgenl.cfg
Hi, I corrected the diag1_pin logic (using pullups and invert) for the config template for MKS SGEN L board, and also used pull up for the endstops. This is a reopen PR since I didn't include `Signed-off-by` section in my original commit. #2601
> Pin logic on MKS SGEN L generic config

- docs/Config_Changes.md
- klippy/extras/display/display.cfg
In PR #2581 the layout of lcd screens was made configurable.  The default layout was unchanged, however.  The 16x4 default screen layout actually included the two different screen layouts - one for single extruder printers and one for multiple extruders.
I'm not sure it is a good idea to automatically use a different lcd screen layout just because the printer has multiple extruders.  This PR changes Klipper to use the same default layout for all 16x4 screens.  The default extruder shown, however, is changed to be the currently active extruder.
For those users that wish to continue using the alternate "multi-extruder" screen layout, they can enable it by adding `display_group: _multiextruder_16x4` to their printer.cfg file.  Or, of course, one can build a completely custom screen layout …
> Use default layout for 16x4 lcd screens even with multiple extruders

- config/generic-bigtreetech-gtr.cfg
This config was not yet available - I have updated all the pin defines, starting with the BTT SKR PRO board which is the most similar board + tested it on my printer which is currently working with the TMC5160 drivers using software SPI. I have not tested it with other drivers etc but the config should work for them.
Signed-off-by: Chester Lowrey <hilo90mhz@gmail.com>
> Add BigTreeTech GTR board generic config file

- docs/G-Codes.md
- klippy/kinematics/extruder.py
- klippy/stepper.py
Add GET_E_STEP_DISTANCE and SET_E_STEP_DISTANCE to available g-codes. Implemented in response to request for a tunable step_distance to account for difference in hardness levels of filament materials.
Signed off by: David Smith <davidosmith@gmail.com>
> Extruder: Add g-codes for get and set extruder step_distance

- klippy/extras/bltouch.py
In the event that a "raise probe" operation fails, the current code will issue a "reset" command to attempt to clear the error state.  However, the "reset" command is only sent for 100ms.  It appears a longer time is needed ( see https://github.com/KevinOConnor/klipper/issues/2267#issuecomment-567044957 ).  This update reworks the code so the existing RETRY_RESET_TIME delay time of 1 second is now done while the "reset" command is being issued.  This should hopefully give the BL-Touch more time to update its internal state.
@FanDjango - does this change look okay to you?
-Kevin
> Give more time to reset the BL-Touch after a failure to raise the probe

- config/example.cfg
- config/generic-fysetc-cheetah-v1.2.cfg
- klippy/mcu.py
- klippy/serialhdl.py
Fixes restart problems on Fysetc Cheetah boards. This changes how the RTS signal is used, so it might make sense to test it on various other boards. Or maybe a configuration toggle should be added?
> Fysetc Cheetah fixes

- scripts/Dockerfile
This also moves the base image to Ubuntu, which includes an (older) version of Python 3, as well as Python 2. This maybe useful for the future with the eventual migration to Python 3.
Signed-off-by: Trent Davis <tgh@sillyfrog.com>
> Update example Docker file for current Klipper version

- klippy/extras/bed_mesh.py
This PR fixes the typo in the error message.
Signed-off-by: Piotr Usewicz <piotr@layer22.com>
/cc @KevinOConnor
> bed_mesh: Fix typo in the error

- src/linux/Kconfig
Allow configure timer resolution for linux mcu.
With gpio implementation need more precise timings for some hardware.
> linux: change clock frequency

- klippy/extras/replicape.py
- src/linux/hard_pwm.c
More pwmchips are exported in the sysfs and the correct one is now
pwmchip4. The corect device for the servo pwm channels is
/sys/bus/platform/devices/48302200.pwm
The beagleboard kernel 4.14 and 4.19 contain in addition a commit
which chnages the pwm control directories from 'pwmX' to 'pwm-Y:X'.
Since the commit is not in upstream Linux a config option for the
sysfs path is added. Since beaglebone+replicape is the main user
of the linux PWM support the config defaults to the non-standard
path. Fixes #2514.
Signed-off-by: Janne Grunau <janne-gh@jannau.net>
> replicape: adapt servo0 channels for beagleboard lernel 4.14.108-ti

- klippy/extras/adc_temperature.py
- klippy/extras/bme280.py
- klippy/extras/buttons.py
- klippy/extras/controller_fan.py
- klippy/extras/delayed_gcode.py
- klippy/extras/display/display.py
- klippy/extras/display/menu.py
- klippy/extras/endstop_phase.py
- klippy/extras/filament_switch_sensor.py
- klippy/extras/gcode_button.py
- klippy/extras/gcode_macro.py
- klippy/extras/heater_bed.py
- klippy/extras/heater_fan.py
- klippy/extras/heater_generic.py
- klippy/extras/heaters.py
- klippy/extras/homing_heaters.py
- klippy/extras/homing_override.py
- klippy/extras/idle_timeout.py
- klippy/extras/probe.py
- klippy/extras/spi_temperature.py
- klippy/extras/temperature_fan.py
- klippy/extras/temperature_sensor.py
- klippy/extras/thermistor.py
- klippy/kinematics/extruder.py
- klippy/klippy.py
- klippy/stepper.py
- klippy/toolhead.py
This is an internal function renaming change.  There should be no user visible impact to this.  It fixes a minor development issue where an incorrect try_load_module() call does not properly raise an error.
-Kevin
> Rename try_load_module() to load_object()

- config/example-extras.cfg
- docs/BLTouch.md
- klippy/extras/bltouch.py
The BL-Touch timing optimization in commit 5c8d15bb had to be reverted (as of commit a028aeaf).  Here's another attempt at it, which also tries to simplify the overall handling of command timing.  Unfortunately, I don't have a good way to test this, so consider it a bit risky.
@FanDjango - FYI.
-Kevin
> Simplify handling of BL-Touch command timing

- .travis.yml
- src/linux/Kconfig
- src/linux/Makefile
- src/linux/analog.c
- src/linux/console.c
- src/linux/gpio.c
- src/linux/gpio.h
- src/linux/hard_pwm.c
- src/linux/internal.h
- src/linux/spidev.c
Allow use host GPIO pins for non-realtime purposes. In my setup HD44780 display connected directly to Raspberry-pi zero. Multi-mcu configuration with linux host-mcu and stm32f4 custom board for printing. I use my own lightweight print server, and now use Klipper. For build with GPIO support need libgpiod headers and library. (libgpiod-dev on Debian). It is early implementation: only one gpiochip, dnt implement pullup/pulldown for input (dnt supported by 4.x kernels). It is can be rewritten directly to gpiod ioctrls for remove library dependency.
At compare to PR #2781 use gpiod interface instead of (deprecated) sysfs gpio interface get code cleanly, faster and possibly extend to digital-buses (bulk gpios). At near future I work on implement events on input pins, encoder too connected to …
> linux: userspace GPIO control via libgpiod

- klippy/extras/tuning_tower.py
Tuning tower helper now takes care of printer z-offset.
This pull request fixes #2511
> extras: Tuning tower compensate z-offset

- src/Kconfig
- src/atsam/Kconfig
- src/atsamd/Kconfig
- src/avr/Kconfig
- src/lcd_hd44780.c
- src/lcd_st7920.c
- src/lpc176x/Kconfig
- src/pru/Kconfig
- src/stepper.c
- src/stm32/Kconfig
The Linux mcu code does not have "strict timing".  That is, the same code executed twice may have very different execution time.  That makes a few minor optimizations in the code not valid on the Linux mcu.  This series adds a new HAVE_STRICT_TIMING build symbol and it uses that to disable these optimizations for Linux mcu builds (at least for the code I'm aware of).
@dianlight , @andryblack - FYI.
-Kevin
> Disable some minor timing optimizations on the Linux mcu that are not valid there

- config/generic-bigtreetech-skr-mini-e3-v2.0.cfg
module: Config example for a SKR Mini E3 v2.0
This is a basic config example for a SKR Mini E3 v2.0, the pinouts are different than the 1.2 and requires different compile options, so worth having an example
Signed-off-by: Paul Greidanus paul@majestik.org
> Adding example configuration for a SKR Mini E3 v2.0

- config/example-extras.cfg
- docs/HallFilamentWidthSensor.md
- klippy/extras/hall_filament_width_sensor.py
I have a very long Bowden after the sensor (about 700mm) and I am using filament which isn't varying very much but every spool is different. 
So for me, the more exact guess of the current width in the melting area is the current reading of the sensor, therefore I added an option that enables the use of the current width while the first reading isn't in place.
> HallFilamentWidthSensor: Use current width instead of nomal width while delay is not over

- klippy/extras/display/uc1701.py
The current code always renders the final column of the glyph black, causing gaps between glyphs that are placed right next to each other:
This change makes the glyphs be displayed properly on uc1701 based displays.
> Possible fix for glyph rendering on uc1701 display variants

- docs/G-Codes.md
- klippy/extras/display/display.py
Add a new extended gcode to change the active display group of the display.
This allows switching between multiple display groups (e.g. to show a splashscreen, or move between different overview displays)
> display: add SET_DISPLAY_GROUP command

- klippy/extras/bme280.py
This allows the temperature_fan module to work correctly when a bme280 is selected as its sensor.
> bme280: fix reported measured time

- src/stm32/Kconfig
This change will allow Klipper to run on **MKS Robin E3D** and **E3** boards.
Micro-controller Architecture: **STMicroelectronics STM32**
Processor model: **STM32F103**
Bootloader offset: **20KiB bootloader**
Clock Reference: **8 MHz crystal**
Serial Port: **USART1**
Baud rate: **250000**
The compiled firmware has still to be "signed" with the **update_mks_robin.py** script before uploading to the board. 
Signed-off-by: Kianusch Sayah Karadji <kianusch@gmail.com>
> Support for 20KiB bootloader offset.

- klippy/extras/pause_resume.py
- klippy/extras/query_endstops.py
- klippy/gcode.py
- klippy/klippy.py
- klippy/webhooks.py
This is the initial implementation of the webhooks module.  The module handles endpoint registration and communication with the Moonraker API server over a Unix Domain Socket.  If the server is not available then the module will not attempt to register endpoints with the server or communicate with it in any way.
Endpoints should be registered in the format `<module_name>/<action>`.  In most cases a callback should be provided, however it is valid to provide `None` in some instances (such as registering an endpoint to serve a file where no intervention from Klippy is necessary).  The "methods" argument takes a list of methods that the server will accept for the given endpoint, the default being ['GET'].   'GET' , 'POST', and 'DELETE' methods are available.   The optional "params" argument …
> webhooks:  register remote API hooks

- config/example-extras.cfg
- docs/G-Codes.md
- klippy/chelper/__init__.py
- klippy/chelper/kin_shaper.c
- klippy/extras/input_shaper.py
Input shaping can help to reduce printer vibrations due to resonances
and eliminate or reduce ghosting in prints.
> input_shaper: Initial support of input shaping

- config/generic-bigtreetech-skr-mini-e3-v2.0.cfg
Y and Z were flipped as per: https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/V2.0/Marlin-2.0.x-SKR-mini-E3-V2.0/Marlin/Configuration_adv.h#L2204-L2212
thanks to Vael#9090 on Discord for pointing this out
Signed-off-by: Paul Greidanus <paul@majestik.org>
> Fix for SKR Mini-e3 v2.0 UART addresses

- klippy/webhooks.py
This fixes a bug where pending requests would be dropped when the ServerConnection is "busy".  The "emergency_stop" request is now checked out of order and will be processed if it is properly decoded and validated.
> webhooks:  Fix reentrant protection

- klippy/chelper/kin_shaper.c
For example, Raspbian GNU/Linux 8 (jessie) uses an old GCC version 4.9.2
which uses -std=gnu90 by default.
> input_shaper: Fixed C module compilation on older gnu90 compilers

- klippy/webhooks.py
This fixes a bug where multiple calls to `_process_request()` are passed the same "web_request" if the for loop that decodes and processes incoming requests contains more than one item.
> webhooks:  fix lambda wrapper around _process_request

- config/example-extras.cfg
- klippy/extras/display/uc1701.py
This adds configuration options for a few of the initialization commands on SSD1306/SH1106 type displays.
Contrast is self-explanatory. Vcomh is used to adjust what appears as a sort of "smearing" that certain cheap OLEDs exhibit (seems to be most prevalent on the 1.3" SH1106 type displays). Invert allows the user to invert the display for black text on lit background.
This is my first time contributing so apologies if I missed anything
-James
> Add configuration options for OLED displays

- config/example-extras.cfg
- docs/Config_Changes.md
- docs/G-Codes.md
- klippy/extras/servo.py
- klippy/mcu.py
- klippy/stepper.py
This change ensures all digital output pins get reset to their initial values on a host restart (even if the micro-controller is not restarted).  This avoids some rare cases where the host and micro-controller state may get out of sync.
The change also improves the servo initialization so that it directly sets the new state once during startup.  This should help with #2821. (@szeker - FYI.) 
The change also removes the explicit servo ENABLE parameter - one can use `SET_SERVO WIDTH=0` to disable the servo instead.  (@dobryj - FYI.)
-Kevin
> Reset output pins on a restart and improve initial servo settings

- klippy/extras/bed_mesh.py
This series of patches adds a "get_status()" method to bed_mesh and refactors some code to streamline the BedMeshCalibrate class  As a result,  issue #3085 is resolved.
The ZMesh class now keeps a reference to the probed_matrix, along with all other mesh data.  This is now the only class that stores that data, other classes that need access to it may access it through various "getters".  
Profile management has been moved to its own class.   The BedMeshCalibrate class is now only responsible for mesh configuration and processing the result from a probing procedure.  This should make it easier add future functionality, such as the ability to configure the mesh at runtime.  
> bed_mesh:  Add get_status(), refactoring

- klippy/extras/safe_z_home.py
In it's current behavior, safe_z_home will attempt to home Z if it thinks the toolhead is above the z endstop even if the motors have since been disabled and the toolhead was moved to another position.
To fix this, the homed status of X and Y is checked immediately before Z is homed. If either of the axes is not homed, an Exception is raised.
The reason this check is done so late, is to cover cases such as:
```
G28 X0
G28 Y0 Z0
```
or
```
G28 Y0
G28 X0 Z0
```
which (with an earily check) would raise the exception even though this sequence of gcodes would yield correct behavior. This does mean, however, that the zlift will always be executed.
> safe_z_home: Make sure X and Y are homed before homing Z

- docs/Config_Changes.md
- docs/G-Codes.md
- klippy/extras/print_stats.py
- klippy/extras/virtual_sdcard.py
This request proposes the following changes to the virtual_sdcard module:
- Add a RESET_SD gcode.  This allows users to clear the virtual_sdcard's state in the event that they want to cancel a print.
- Walk through subdirectories when populating the file list, allowing Klipper to load these files via `M23 subdir/myfile.gcode` or  `M23 /subdir/myfile.gcode`
- Report print progress while the virtual_sdcard is paused.  The current behavior resets progress to 0.  In addition, report "is_active" and "file_position"  via get_status()
-  Add a PrintStats class that tracks the total time elapsed since the print has started, the total time spent printing  (not paused), and the total filament used based based on the gcode position.  These stats, along with the currently loaded file's name, are …
> virtual_sdcard:  various additions

- klippy/extras/gcode_arcs.py
Arc travel was working but extrusion in absolute mode seemed not to be happening at all. This was because the E coord being sent with each G1 segment of the arc was not incrementing, effectively the same value was being sent over and over so the total extrusion for the whole arc was the amount for just one segment which is an extremely tiny amount.
My change increments e_base by e_per_move for each subsequent coord when in absolute extrude mode which results in the correct absolute E value being sent for each segment. 
Signed-off-by: Toby Harper toby@fuith.org
> fix for gcode_arcs absolute extrusion mode

- config/example-extras.cfg
- docs/Sensorless_Homing.md
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2209.py
- klippy/extras/tmc5160.py
- klippy/extras/tmc_uart.py
Follow up to and closes #3150 
Here is my first pass at it. I figured pushing the diag_pin lookup into the tmc_spi is a reasonable place to limit duplication and minimize impact on the 2209/uart code.
I wasn't sure what the best place to document was so I just added that small note to the sensorless homing page. If the
assumption holds, that the diag0 only hardware is uncommon I don't expect much more would be necessary?
~My machine with with the 5160's just finished as I was typing this PR up, so I am headed to test it now.~
One silly mistake on my part and it seems to be working as expected.
> TMC5160 diag0 support

- lib/README
- lib/fast-hash/fasthash.c
- lib/fast-hash/fasthash.h
- src/stm32/Makefile
- src/stm32/can.c
There were ID collision in the CAN bus unique ID generation. 
I found a small and fast little hash library that solved that problem.
> Improvements to CAN bus ID generation. And added a small fast hash library

- config/printer-creality-ender3-2018.cfg
By homing the y axis before the x axis, the nozzle will not touch the plastic cover of the bed heater cable.
The printer would not hit the cover during normal operation, but the y axis has a lot of extra travel that allows the nozzle to reach behind the print surface. When it is in a low z height and the x axis is homed first, it will collide with the plastic cover.
> config: Fix homing order of Ender 3

- klippy/extras/virtual_sdcard.py
- klippy/webhooks.py
This changes Klippy's role from a client to a  uds server.  It is possible for Klippy to host simultaneous clients, where the response to a web request is sent only to the requesting client.  Currently data pushed from Klippy (such as status updates and gcode responses) will be sent to all connected clients.  We may wish to look at that behavior in the future, perhaps though an endpoint that allows clients to register an identity and the methods they accept.  
Also implemented in this PR:
- Calls to `ClientConnection.send()` write to a buffer and do not block, resolving potential reentrancy issues
- webhooks registers a "gcode_respond_callback" that forwards gcode responses to all client sockets
- webhooks calls the "set_klippy_shutdown" remote method when it receives a shutdown event
- …
> webhooks: implement a unix domain socket server

- klippy/extras/display/menu.py
Fix for #3187
In case of an overwriting existing menu item, there was a bug,
The new item was added additionally to the end of the items list.
> menu: fix for #3187

- klippy/extras/pause_resume.py
- klippy/extras/query_endstops.py
- klippy/extras/virtual_sdcard.py
- klippy/gcode.py
- klippy/klippy.py
- klippy/webhooks.py
- scripts/whconsole.py
@Arksine - as discussed, I'm putting together a proposal for some changes to the "webhooks" interface.
The primary change is to convert the interface to a format that is more similar to json-rpc (though it does not stringently follow json-rpc).  So, requests now look like: `{"id":14, "method": "api_server/info", "params": {}}`.  The `id` and `params` fields are optional.  Responses now look like `{"id": 14, "result": {}}`.
This branch also adds a new `./scripts/whconsole.py` script that one can use to send in queries to the klippy server.  So, one can send in the above command and see the response.
Another notable change is that the server never sends unsolicited messages to the client.  The client must subscribe to get_status() updates and/or gcode output messages.  Such a subscription …
> This is a proposal for updates to the "webhooks" interface

- klippy/extras/display/menu.py
- optimize container `populate` method
- don't populate all items at the menu start
- populate container items when a container is pushed to the stack
- pre create List back-item, don't do class instantiation inside `populate` method.
- don't update items inside `populate` method
> Menu optimizations

- docs/HallFilamentWidthSensor.md
- klippy/extras/hall_filament_width_sensor.py
After reading the first item of self.filament_array, filament_width is updated back to self.nominal_filament_dia or self.diameter instead of keeping the value until the next pending_position.
Signed-off-by: Nicola Falciani <nicola.fal@gmail.com>
> hall_filament_width_sensor.py: Fix Flow update before next pending_position #3184

- config/printer-tevo-tarantula-pro-2020.cfg
Thanks to @Kollimolli for pointing out the potential for confusion, I totally missed the re-branding of Tevo -> Homers.
The following parameters have been tweaked:
- X endstop position has been set to -2, as per original marlin cofig
- Second Z axis disabled by default (this must be purchased as an
add-on)
- Enable print-head fan only when extruder reaches 50 degrees
The comment at the top of this file has also been modified to describe
the difference between this (old) model and the new (rebranded) Tevo
Tarantula pro.
Signed-off-by: Oliver Fawcett-Griffiths <olly@ollyfg.com>
> config: Tarantula Pro - Multiple tweaks and description change

- klippy/queuelogger.py
- klippy/webhooks.py
@Arksine - What would you think about allowing (and encouraging) webhook clients to send their version info to klipper via the "info" endpoint?  That is, allow clients to issue something like:
```
{"id":14, "method": "info", "params": {
"client_info": {"program": "mainsail", "version": "123.3.5"}
}
}
```
Klipper could then log that information, which could be helpful during troubleshooting.
-Kevin
> Add client_info parameter to "info" webhook

- config/generic-replicape.cfg
As was discussed in #3128 the board_pins section for gpio access by the linux host is being provided here.
Also a sample filament switch sensor section that makes use of it.
> Replicape config updates with pin aliases

- config/example-extras.cfg
- docs/G-Codes.md
- klippy/extras/adxl345.py
- scripts/graph_accelerometer.py
- src/Makefile
- src/sensor_adxl345.c
This adds support for querying an ADXL345 accelerometer using Klipper's micro-controller SPI interface.  It's been in discussion in issue #3027 .  This has been tested with an ADXL345 wired to a Raspberry Pi that has been setup to use Klipper's "linux mcu" support.  However, it should work on any micro-controller that Klipper supports.
This PR only adds support for bulk reading of accelerometer data.  It is expected that resonance testing and analysis will be added at a later date.
The current code adds an ACCELEROMETER_MEASURE command.  However, I don't much like the current command name, current command format, nor resulting file format.  I don't have any better ideas right now.  I expect we'll tweak the command and formats prior to merging.
To test this setup:
`cd ~/klipper ; git fetch …
> Add support for querying ADXL345 accelerometers via SPI

- config/example-extras.cfg
- klippy/extras/display/uc1701.py
module: Display, add x_offset config
Fix for https://github.com/KevinOConnor/klipper/issues/3091
Adds a horizontal offset config for fixing displays that are cutoff
in Voron v0 printers.
Detail explanation here:
https://github.com/KevinOConnor/klipper/issues/3091#issuecomment-657923777
Signed-off-by: RJ Patawaran <rjpatawaran@me.com>
> config: Add x_offset (Used to add horizontal offset on SSD1306/SH1106 displays)

- docs/Command_Templates.md
- klippy/extras/probe.py
module: Probe - Add get_status wrapper with last_query status for macros
It is sometimes useful to determine the state of the probe from a macro. If
the probe is connected to an endstop pin, the results can be obtained via
QUERY_ENDSTOPS but if a physical endstop is in use in addition to the probe
the probe state cannot be obtained. This change allows one to use QUERY_PROBE 
and then access the printer.probe.last_query object to obtain the state.
Signed-off-by: Paul McGowan <mental405@gmail.com>
> add get_status wrapper to probe for last_query from query_probe command

- scripts/avrsim.py
Note that the latest simulavr 1.1.0 does not support Python 2 anymore.
> avrsim: migrated to Python 3

- docs/Bed_Mesh.md
- docs/G-Codes.md
- klippy/extras/bed_mesh.py
- klippy/extras/probe.py
This adds a `BED_MESH_CONFIG` gcode, which allows users to modify the configuration at runtime.  The gcode can accept parameters matching all available config options, sans `speed` and `horizontal_move_z`. This did require a modification to the ProbePointsHelper so that its "probe_points" attribute could be changed.
> bed_mesh:  add support for runtime configuration

- config/sample-macros.cfg
- config/sample-raspberry-pi.cfg
Two sample config files still had the old syntax.
-Florian
> Fix sample macros that use old action_respond_info syntax

- klippy/extras/display_status.py
The M117 command parser discards the last character of the message
whenever the M117 command does not begin the line and there is no *xx
checksum, e.g.
`N0 M117 Look at me`
causes the banner area of the printer screen to display "Look at m".
This patch only trims the checksum when one is found to trim.
> display_status: fix M117 checksum trimming

- docs/Delta_Calibrate.md
- docs/Manual_Level.md
- docs/Probe_Calibrate.md
Any hardware change to the hotend or probe, change to the kinematics,
or change to the bed tilt is likely to invalidate the results of
PROBE_CALIBRATE.  Try to warn the user of that.
@Arksine - this mentions bed mesh a few times, so it would be great if you could review this as well.
Thanks,
-Kevin
> Note PROBE_CALIBRATE results invalidated on motion system update

- src/atsam/adc.c
- src/atsam/sam4e_afec.c
- src/atsamd/adc.c
- src/stm32/adc.c
- src/stm32/stm32f0_adc.c
This PR adds support for reading the temperature from built in micro-controller sensors.  The ATSAM91 chips (Due and Duet boards), SAMD chips, and STM32 chips all have temperature sensors built in.  (The AVR chips and LPC176x chips do not appear to have this hardware.)
This is just the micro-controller code for the support.  At some point in the future, I'd like to add in streamlined host support.  For those that wish to test, though, it is possible to manually read these temperatures sensors with a config snippet similar to:
```
[adc_temperature sam3_mcu]
temperature1: 27
voltage1: 0.800
temperature2: 127
voltage2: 1.065 # voltage1 + 100 * .002650
[adc_temperature sam4_mcu]
temperature1: 27
voltage1: 1.44
temperature2: 127
voltage2: 1.910 # voltage1 + 100 * .004700
[adc_temperature …
```
> Support for micro-controller on-chip temperature sensors

- config/example-extras.cfg
Document the previously undocumented menu_root parameter in the [display] section
> Document menu_root

- docs/API_Server.md
- docs/Command_Templates.md
- klippy/extras/gcode_macro.py
- klippy/webhooks.py
This adds the ability for webhooks clients to register methods that may be called from within a template.  The current implementation will allow for multiple clients to register the same method.  When invoked, the method is executed on all clients.
> gcode_macro: add "register_remote_method" endpoint

- config/printer-wanhao-duplicator-6-2016.cfg
The Monoprice Maker Ultimate / Wanhao Duplicator 6 has case lights wired to PH5, this PR creates an `output_pin` named `CASE_LED_LIGHTS` to replace the Marlin `M355` functionality
> Wanhao Duplicator 6: Add output_pin for case lights

- docs/Config_Changes.md
- klippy/extras/print_stats.py
As previously discussed, this excludes time spent prior to the first extrusion from `print_stats.print_duration`.  The result is a more accurate representation of the print duration in comparison to the time estimates generated by slicers.
> print_stats:  exclude initialization time from "print_duration"

- config/printer-monoprice-select-mini-v2-2018.cfg
- config/printer-monoprice-select-mini-v2.cfg
Adds config for the Monoprice Select Mini v2 cartesian printer. I have
successfully tested the configuration.
Signed-off-by: Kilian Neuner <github@9-r.net>
> config: add config for Monoprice Select Mini v2 printer

- config/printer-sunlu-s8-2020.cfg
Adds SUNLU S8 printer config  (successfully tested).
> config: Add printer-sunlu-s8-2020.cfg printer config

- docs/G-Codes.md
- klippy/extras/heaters.py
This adds a new g-code command to "wait for a minimum temperature" on a sensor.
This might be useful, for example, if one uses a bed heater to heat a chamber and wishes to wait for the chamber to reach a minimum temperature.  Such a command might look like: `wait_temperature sensor="temperature_sensor chamber" minimum=40`
-Kevin
> Add a WAIT_TEMPERATURE command

- docs/BLTouch.md
- docs/Config_Reference.md
@FanDjango - I've seen a few Klipper issues where users get confusing results because they fail to set a pullup on the bltouch sensor_pin.  My general understanding is that it is safe to always define the sensor_pin with a pullup.  (And in some cases it is required.)  However, given the large number of bltouch revisions and clones, I'm not a 100% sure of this, so I've been reluctant to change the documentation to state it.  Would you know if it's safe to recommend always setting the pullup?
Thanks,
-Kevin
> bltouch: Recommend using a pullup on the sensor_pin

- config/printer-twotrees-sapphire-plus-2020.cfg
- test/klippy/printers.test
Based on config for Sapphire Pro but adapted for Sapphire Plus.
> config: Add example printer-twotrees-sapphire-plus-2020.cfg config

- docs/Command_Templates.md
- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/corexz.py
- klippy/kinematics/delta.py
- klippy/kinematics/none.py
- klippy/kinematics/polar.py
- klippy/kinematics/rotary_delta.py
- klippy/kinematics/winch.py
Extend kinematic classes for reporting XYZ-axis min/max values.
These values can be used in the movement menu.
Example output:
```
printer['toolhead'].max_accel = 2000.0
printer['toolhead'].homed_axes =
printer['toolhead'].axis_max = {'y': 128.52, 'x': 128.52, 'z': 231.47}
printer['toolhead'].estimated_print_time = 3157.17333085
printer['toolhead'].max_velocity = 500.0
printer['toolhead'].print_time = 0.001
printer['toolhead'].axis_min = {'y': -128.52, 'x': -128.52, 'z': -5.0}
printer['toolhead'].max_accel_to_decel = 1000.0
printer['toolhead'].position = Coord(x=0.0, y=0.0, z=0.0, e=0.0)
```
> Extend kinematics for reporting xyz-axis min/max

- config/printer-lulzbot-taz6-2017.cfg
config: Fix TAZ6 homing and bed tilt probing
This configuration adjusts the Y position for Z homing, and the bed_tilt calibration points to match the factory Marlin firmware, and has been tested by me on an unmodified Lulzbot TAZ6 /w single extruder.
The factory Marlin firmware [(link to relevant lines](https://gitlab.com/lulzbot3d/marlin/-/blob/TAZ_6.0_Single_Extruder_v2.1/Marlin/Configuration.h#L458)) uses X=-19, Y=258 as the homing position. Klipper's configuration for this printer uses X=-19, Y=265 which causes the problem as the button isn't big enough to accommodate 7mm of error from center -- though it's close!
The bed tilt homing points in the existent Klipper config didn't and don't quite line up. This new configuration updates the left/right front/back values to match up with …
> Fix TAZ6 single-extruder homing and bed tilt probing

- klippy/extras/bed_mesh.py
- klippy/webhooks.py
I've been using the rebased Python 3 branch for few months now. No problems encountered so far, except that setting invalid values with gcode commands through webhooks triggers a shutdown. After I learned that this shouldn't happen, I found the problem:
In some exception handling situations, `Exception.message` is used to get the message. This attribute is [deprecated](https://www.python.org/dev/peps/pep-0352/) since Python 2.6 and removed in Python 3. This raises an `AttributeError` exception in the exception handling code and prevent recovery.
This PR replaces the occurrences of `e.message` with `str(e)`. (`e.args[0]` is another possibility)
I did set this PR for the master branch since it fixes a deprecation on python 2.6/2.7 (it should emit a notice with `warnings.warn()`), but feel …
> Fix deprecated usage of Exception.message attribute

- klippy/extras/display/menu.cfg
Changed the movement limits to the new available printer variables (thank you for adding mcmatrix ) 
printer.toolhead.axis_minimum.(x/y/z)
printer.toolhead.axis_maximim.(x/y/z) 
That will work now for all printers and reduce to user involvement for customising there menus .
Signed-off-by: Alex Zellner alexander.zellner@googlemail.com
> Change move min/max limits menu.cfg to the new priner variables

- docs/Command_Templates.md
- klippy/configfile.py
- klippy/extras/gcode_macro.py
- klippy/extras/heaters.py
- klippy/extras/query_endstops.py
- klippy/extras/save_variables.py
It's currently possible to obtain the raw values from the Klipper config file by accessing values like `{printer.configfile.config.printer.max_z_velocity}`.  However, doing so can be tedious because the value is always returned as a string and it may not be present if the user is relying on a default value.
This PR adds new exports such as `{printer.configfile.settings.printer.max_z_velocity}` which report the "parsed" value that Klipper uses - or the default value if the user did not specify a value.
This method isn't always assured to report accurate default values (it's possible the code will have a default, but not internally obtain the default using the common `config.get()` method), but it's going to be accurate for most settings.
@Arksine @mcmatrix @meteyou @cadriel - do you have …
> Export a "parsed" version of the config file to command templates and api server

- klippy/extras/hall_filament_width_sensor.py
- klippy/extras/tsl1401cl_filament_width_sensor.py
I noticed that switching off the hall filament width sensor mid-print does not always switch off the active flow rate modifier.
With this fix, this problem did not occur to me again.
> Fix race condition of filament width sensor

- docs/Measuring_Resonances.md
Added some clarifications around how to refer to adxl345 sensors when there are more than one.
> Docs: resonance testing fixup

- src/stm32/stm32f1.c
Running the STM32F1 at 72MHz with a 16MHz external crystal requires a 4.5x frequency multiplier which the current code does not allow for.  With this change it instead calculates the multiplier required for half the crystal frequency and sets the RCC_CFGR_PLLXTPRE_HSE_DIV2 if the multiplier would not exceed the maximum of 16.
Signed-off-by: Matt Shepcar <matt@shepcar.co.uk>
> stm32f1: Fix for using 16MHz external crystal

- klippy/extras/display/menu.cfg
Re-submit of  #3737 because I don't remember to put <code> signed-off-by </code> in to the commits.
- Change the SD card enable condition from using <code>printer.idle_timeout.state</code> to <code>printer.print_stats.state</code> because of the following reasons  
*  When paused, the "Resume" option does not show up because at that time printer.idle_timeout.state == "Ready"  
*  When paused, only "Start" option is available, it should be "Resume" (i known they use the same Gcode, but its confusing).  
* The "Resume" option show up even when printing.  
- Added <code>Cancel printing</code> option.
> Re: Change SD card menu enable condition

- docs/CONTRIBUTING.md
- docs/Contact.md
- docs/issue_template.md
This Pull Request is a proposal to stop using github for support queries and to update the Klipper Contact.md document to make that clear.
I currently estimate that at least 95% of new github issues are really "support queries" - tickets from users looking for assistance.  Unfortunately, I don't think github is a good tool to provide user support, and I fear these queries are making github "noisy" to the point that it is making it harder to use github for what it is useful at - tracking defects and providing a forum for those working on improving Klipper.
The new Contact.md document in this Pull Request would make it clear that github is not a place to go when looking for support.  Along with the change to Contact.md, as part of this proposal, I would also close any new github issue that …
> Proposal to stop using github for support

- docs/Config_Reference.md
- klippy/extras/display/hd44780.py
The LDO OLED needs a different init.
Fixes: #3722
Signed-off-by: Thomas Kroll <t.kroll@outlook.com>
> hd44780: Add hd44780 LDO OLED protocol init

- docs/G-Codes.md
- klippy/extras/temperature_fan.py
This PR adds a command to change temperature_fan `max_speed` and `min_speed` at runtime. 
My use case:
Exhaust fan needs to both run at a minimum speed during a print, and maintain chamber temperature. Setting min_speed to zero means that it does not run until chamber target has been reached. Setting min_speed to a low value makes the fan run even when not printing. 
This allows me to leave `min_speed: 0` in the config and have a completely silent printer while idle. When starting a print, I set the fan minimum to 15%, while still allowing temperature-based PID control of the fan speed within the set limits.
Usage:
`SET_TEMPERATURE_FAN_LIMIT temperature_fan=chamber MIN=0.15 MAX=0.75`
> Add MAX_SPEED and MIN_SPEED to SET_TEMPERATURE_FAN_TARGET command

- config/printer-creality-ender3max-2021.cfg
Added Ender 3 Max config. Based off the configs from ender6, ender3-v2, and ender3. Also contains optional BLTouch parameters.
Signed-off-by: Chad Schwieterman <chad.devops@gmail.com>
> config: Add printer config for the Ender 3 Max by Creality3D

- docs/Command_Templates.md
- klippy/extras/probe.py
Code provided by @jornada812
The essence of the changes - a variable has been added, in which the Z of the sensor triggering is written and this value can now be returned and used in a macro.
Signed-off-by Christian Schnellrieder
> Add last_z_min to last_z_result to get the latest z result in an Macro

- klippy/extras/display/display.py
- klippy/extras/display/menu.py
Redesigned the menu scroller and rendering functionality. 
Now it allows using the glyphs placeholders in menu names like `name: Temp: 25~degrees~ ` etc.
The placeholder rendering in menu item names is not working correctly when scrolling is used.
For example `name: "This ~degrees~ is a very long name for menu item"`. When the name starts to shift to 
the left then after reaching to placeholder marking it will break the placeholder rendering. 
Unfortunately, I didn't find a solution for this and therefore to make it work correctly the long name scrolling is disabled for standard menu items. The long name scrolling is enabled only for `virtual_sdcard` filenames.
Tested following LCDs: uc1701,  st7920,  hd44780
Looked okay but need to run a few more test rounds.
All ideas and tests are …
> menu: redesigned name scroller & menu rendering

- klippy/extras/display/menu.cfg
For the menu hotend targets, also check available heaters.
It'll solve a crash when using shared heaters.
> menu: fix for #3968

- docs/Config_Reference.md
The sensor BME280 must be capitalised in the printer.cfg.
> typo in sensor_type: BME280

- klippy/extras/virtual_sdcard.py
currently, if there are 2 files on the virtual sd card whose names differ only in
case (eg. MyFile.gcode vs myfile.gcode) the actual file that gets loaded is at
best unpredictable.  this patch checks for an exact match before attempting a
case-insensitive one.
Signed-off-by: Andre LeBlanc <andrepleblanc@gmail.com>
> virtual_sdcard: exact filename match before case insensitive one

- docs/Config_Changes.md
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2209.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
- klippy/mcu.py
There are several high-level changes in this PR:
1. Every enabled TMC stepper is now polled once per second to see if the driver reports an error (eg, over-current or over-temp).  If the driver reports an error (or can not be contacted) then a shutdown is invoked.
2. TMC temperature warnings are also checked once per second.  Warnings are written to the log.
3. The full initialization sequence is now sent every time the driver is enabled.
4. It is no longer an error if a TMC2208/TMC2209 driver is not available on startup.  This may simplify setups where motor power is externally controlled.  If the software cant contact the driver when it is actually enabled, then a shutdown will be invoked.
5. The SET_TMC_CURRENT command has been refactored.
The above changes apply to all of the tmc …
> Periodically check TMC drivers for errors

- config/generic-mks-robin-nano-v3.cfg
According to [Robin Nano v3 pinout](https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/blob/main/hardware/MKS%20Robin%20Nano%20V3.0_003/MKS%20Robin%20Nano%20V3.0_003%20PIN.pdf) the correct pins for:
- EXP2_4 is PE10
- EXP2_6 is PA7
Signed-off-by: Oleksii Zelivianskyi <alexeyzel@gmail.com>
> config: EXP2 header pin correction for Robin Nano 3 config example

- config/generic-mks-robin-nano-v3.cfg
There are two fan pins on Robin Nano 3 and the fan1 pin is PC14, not PB1.
PB1 pin that was in config example is used for the fan2 output.
Signed-off-by: Oleksii Zelivianskyi alexeyzel@gmail.com
> config: fan pin number correction for Robin Nano 3

- klippy/chelper/serialqueue.c
When `klippy` requests a `FIRMWARE_RESTART` from `klipper_mcu` the open pseudo-TTY between them is closed and a `SIGHUP` gets sent to `klippy` which subsequently kills it. This is the cause of #3981.
Here I've added a `SIGHUP` handler that simply ignores the signal, but that seems like throwing the baby out with the bathwater, as it will stop `klippy` from dying if run from e.g. a terminal which is then closed(instead of properly killed e.g. with `Ctrl-C`/`SIGINT`). I'd love suggestions on how to better handle this, if relevant, before merging this.
I've been scouring over the kernel code for `devpts` and from I've been able to tell it's not possible to disable this behavior of sending a `SIGHUP` so we need to somehow handle this situation ourselves.
I also did a quick change in …
> Fix klipper_mcu causing klippy to die

- docs/Config_Reference.md
- klippy/extras/fan.py
- klippy/extras/pulse_counter.py
- src/Makefile
- src/pulse_counter.c
In response to https://github.com/KevinOConnor/klipper/issues/3771
This adds two new config options for fans: 'tachometer_pin' to specify
the GPIO pin, and 'min_rpm' to ensure that the fan is spinning fast
enough (and shutdown otherwise). The rpm is also exposed in get_status
for command templates and the api server.
There is a new mcu object for a generic edge counter, which repeatedly
polls a GPIO pin and periodically reports the count to the host.
> fan: Add tachometer support

- src/stm32/i2c.c
- src/stm32/stm32f1.c
This adds support for the alternate pin mapping of I2C1 on PB8/9 in STM32F1 devices
> Add support for STM32F1 I2C1 alternate pin mapping

- klippy/extras/idle_timeout.py
When using klipper with a machine without heaters (e.g. a plotter) there is an error when the idle timeout is applied: (Unknown command:"TURN_OFF_HEATERS")
This PR fixes this by checking if there are any heaters to turn off.
I tested this with a normal printer and with a machine without heaters.
--fleinze
> changed standard timout gcode

- config/printer-hiprecy-leo-2019.cfg
A working configuration example for Hiprecy Leo printer (https://www.hiprecy.com/product/402/) with no Touchscreen funcionalities because separated LCD firmware needed.
TMC2130 SPI drivers.
The Self-levelling plate sensor is PINDA probe type
Direct Drive is a BMG "50:17" (3:1) gear ratio
Signed-off-by: Morgan Barresi <morganfw@gmail.com>
> New configuration printer-hiprecy-leo-2019.cfg

- src/generic/armcm_boot.c
Resets stack value in a way that doesn't add hazards in vendor specific main functions.
Resets all user interrupt enables, pending interrupts and interrupt priorities.
First instruction after the reset vector compiles to `CPSID i` to disable interrupts.
May want to consider only compiling in the manual interrupt resets when a bootloader is specified in the `menuconfig`. On M3 and M4 there are 240 interrupt priority registers.
If interrupts are not enabled before jumping to the F0 system bootloader it doesn't work correctly, which is why they are turned back on before calling `armcm_main` instead of letting the klipper system code eventually handle that. I assume other bootloaders may be similar. klipper appears to work fine without it.
> Improve ARM Cortex-M control transfer from bootloaders

- klippy/chelper/__init__.py
- klippy/chelper/stepcompress.c
- klippy/kinematics/extruder.py
- klippy/stepper.py
This extends the low-level step compression code to keep a history of `queue_step` commands sent to the micro-controller.  The host can use this information to calculate the position of the stepper motor given a recent time.
This will be useful for filament sensors, as it should allow the host code to obtain the extruder position at the time of a signal from the filament sensor.
This support will also be needed for multi-mcu homing.
@Arksine , @TheJoshW, @mattshepcar - FYI.
-Kevin
> Add support for host tracking of the history of stepper motion

- config/sample-macros.cfg
- docs/Command_Templates.md
- docs/Config_Reference.md
- klippy/extras/bme280.py
This adds support for BMP280 and BME680 sensor ICs,
along with fixing calibration data readout for BME280.
Gas sensor readout for the BME680 is just the raw compensated value.
To get actual meaningful values, more research is needed.
Signed-off-by: Michael Kurz <michi.kurz@gmail.com>
> Add support for BMP280 and BME680 sensors

- klippy/extras/htu21d.py
HTU21D sensor class lacked the method `get_report_time_delta` invoked
during watermark control loops. This short fix simply adds that method
in, calling the `self.report_time` attribute created during class
construction.
Fixes issue #4074
Signed-off-by: Jon Sanders <jonsan@gmail.com>
> module: HTU21D sensor definition fix

- src/linux/sensor_ds18b20.c
Fixes
```
Program received signal SIGSEGV, Segmentation fault.
#0  __memchr_generic () at ../sysdeps/aarch64/multiarch/../memchr.S:89
#1  0x0000aaaaaaaac7f0 in command_config_ds18b20 (args=0xffffffffcd30, args@entry=<error reading variable: Cannot access memory at address 0xb692a5472eb6a570>) at src/linux/sensor_ds18b20.c:142
#2  0x0000aaaaaaab2d84 in command_dispatch (msglen=29 '\035', buf=<optimized out>) at src/command.c:322
#3  command_find_and_dispatch (buf_len=<optimized out>, pop_count=<synthetic pointer>, buf=<optimized out>) at src/command.c:340
#4  command_find_and_dispatch (pop_count=<synthetic pointer>, buf_len=29 '\035', buf=<optimized out>) at src/command.c:335
#5  console_task () at src/linux/console.c:165
#6  ctr_run_taskfuncs () at out/compile_time_request.c:74
#7 …
```
> ds18b20: Segmentation fault on 64bit Raspbery PI.

- config/generic-mks-robin-nano-v2.cfg
extruder1 `step_pin` was set incorrectly in MKS Robin Nano V2 example config.
Complete pin map can be found [here](https://github.com/makerbase-mks/MKS-Robin-Nano-V2.X/wiki/Wiring_Pinout_and_Size#pin-map).
> Fix extruder1 step_pin in Robin Nano V2 example

- klippy/extras/display/menu.cfg
- Set 1% as input minimum for speed and flow
- Increase speed maximum from 200% to 500%
> Changes in tune menu according to #4023

- docs/Config_Reference.md
- docs/TMC_Drivers.md
I've been tuning sensorless homing on my Voron 2.4 machine.  As part of that process, I've come up with a revised guide to tuning sensorless homing.  The main changes are: there are now tmc2209 and tmc2660 examples, the guide now recommends a procedure for finding a "minimum homing sensitivity" / "maximum homing sensitivity", and there are additional notes on selecting homing speed, currents, macros, etc.
I've only tested this procedure on tmc2209 drivers.  Feedback on users of tmc2660, tmc2130, and tmc5160 drivers would be great.
The new guide can be found in: https://github.com/KevinOConnor/klipper/blob/work-tmcdoc-20210311/docs/TMC_Drivers.md
@yschroeder @Schnilz @trevjonez - FYI.
-Kevin
> Revised sensorless homing configuration guide

- klippy/extras/bed_mesh.py
This is a bugfix that resolves #4129.
> bed_mesh:  lookup the toolhead object in "handle_connect"

- klippy/extras/bltouch.py
When probing, the current bltouch code will detect a trigger signal, acknowledge the mcu homing event, and then send a pin_up command.  The "mcu acknowledge" stage may require a few messages to be sent to the micro-controller which normally takes a few milliseconds.  However, in the event of communication errors or delays, it's possible for that process to delay the pin_up command.  As we work on multi-mcu homing (PR #3956) the "mcu acknowledgement" becomes more complex and it increases the risk of a delay.
This PR alters the bltouch code so that it can send the pin_up immediately after a trigger signal.  This should reduce the risk of a delayed pin_up command.
I don't actually own a bltouch, so I can't directly test this code.  Testers would be welcome.  Basic verification that probing …
> Faster "pinup" on BL-Touch

- src/stm32/stm32f1.c
Hi Kevin, as previously discussed this patch resets the peripheral in `enable_pcclock`.  This fixes hardware SPI on the BTT SKR Mini (and its derivatives), where the stock bootloader does not properly disable SPI after use.
SIgned-off-by:  Eric Callahan <arksine.code@gmail.com>
> stm32f1: reset peripherals in enable_pcclock()

- src/stm32/Kconfig
- src/stm32/can.c
Fixed simple typo in the Kconfig and can.c. stm32f4 CAN Pins
causing the build of stm32f4 with CAN pins PI9 and PH13 to fail.
Signed-off-by: Oliver Walter <oli1111@web.de>
> stm32: CAN Kconfig typo

- config/generic-mightyboard.cfg
- docs/Config_Reference.md
- klippy/extras/pca9533.py
Add support for the pca9533 led driver ic.
Signed-off-by: Marc-André Denis marcadenis@msn.com
> RGB support for the mightyboard

- klippy/extras/palette2.py
Quick fix for a missing null check in `get_status` should address the issue reported here: https://github.com/KevinOConnor/klipper/pull/4057#issuecomment-820093695
Signed-off-by: Clifford Roche <clifford.roche@gmail.com>
> Palette2, Fix get_status

- docs/Benchmarks.md
- docs/Config_Changes.md
- docs/G-Codes.md
- docs/MCU_Commands.md
- klippy/extras/extruder_stepper.py
- klippy/extras/manual_stepper.py
- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/corexz.py
- klippy/kinematics/delta.py
- klippy/kinematics/extruder.py
- klippy/kinematics/polar.py
- klippy/kinematics/rotary_delta.py
- klippy/kinematics/winch.py
- klippy/mcu.py
- klippy/stepper.py
- klippy/toolhead.py
- src/stepper.c
The min_stop_interval check was designed to check if the host communication was lost in the middle of a series of stepper moves.  The high-level idea to the check was that the host would never stop moving a stepper while the stepper is moving at a high speed.  If that did occur, it was likely the result of a loss in communication.
However, this check has proved troublesome.  It's not easy to predict the maximum halt velocity for many steppers.  It makes it difficult to tune acceleration, velocity, and cornering speeds at runtime.  There are cases during direction changes that complicate the check.  Etc.  
The end result is that the check has been steadily diluted over the years and I suspect it is now just a burden.
This PR removes the check entirely.  It also changes the toolhead code so …
> Remove the min_stop_interval check from the micro-controller code

- docs/Config_Changes.md
- docs/Config_Reference.md
The `default_parameter_NAME` system has always been a bit goofy.  It's a holdover from gcode macros from before the introduction of Jinja2.  The Jinja2 "set" directive is more flexible and easier to understand.
This PR deprecates those config options and encourages using "set" as a replacement.  The change now is just to the documentation - actual support would be removed in around 6 months.
-Kevin
> Deprecate gcode_macro default_parameter_<name> config

- config/example-hybrid-corexy.cfg
- config/example-hybrid-corexz.cfg
- docs/Config_Reference.md
- klippy/kinematics/hybrid_corexy.py
- klippy/kinematics/hybrid_corexz.py
- test/klippy/printers.test
Add hybrid-corexy kinematics.
Add hybrid-corexz kinematics.
Both are simple carriage version of the kinematics also known as Markforged kinematics.
This follows the issue #3391 and is a revamp of pull request #3609
Signed-off-by: Fabrice GALLET tircown@gmail.com
> kinematics: Add hybrid-corexy and hybrid-corexz

- config/generic-fysetc-s6-v2.cfg
- config/generic-fysetc-s6.cfg
- scripts/spi_flash/board_defs.py
- src/stm32/Kconfig
The Fysetc S6 and Spider come with an SDCard bootloader. This PR updates Kconfig to allow configuring the correct offset on an STM32F446 to prevent Klipper from overwriting the bootloader. Also new board definitions for `flash-sdcard.sh` are introduced.
This has been tested with an S6 v2 and a Spider v1.
> SDCard update and compilation support for Fysetc S6 and Spider

- config/generic-creality-v4.2.10.cfg
- config/printer-creality-cr30-2021.cfg
- test/klippy/printers.test
Add support for CoreXY belt printers, specifically the
Creality CR-30. The corexy_belt kinematic simply overrides
the corexy's home() function such that Z axis homing resets
the toolhead Z position, instead of performing a home on the
Z rail.
Additionally, an example configuration for the Creality CR-30
is added as a working demonstration of the feature.
Signed-off-by: Jason S. McMullan <jason.mcmullan@gmail.com>
> config: Add Creality CR-30 PrintMill support

- klippy/extras/display/menu.cfg
As you can reference in https://github.com/KevinOConnor/klipper/blob/master/klippy/extras/print_stats.py
The state that is set is "paused" not "pause" causing some of the submenus to not show up.
> Fixed typo in when comparing `print_stats.state` causing menus to not show up

- config/generic-ruramps-v1.3.cfg
To use this config, the firmware should be compiled for the Arduino Due.
This configuration is also compatible with RuRamps V1.1.
Signed-off-by: Marco Robustini <robustinimarco@gmail.com>
> Configuration file for RuRamps V1.3 boards

- config/printer-fokoos-odin5-f3-2021.cfg
Signed-off-by: Matthew Lloyd <github@matthewlloyd.net>
I neither hear nor see mechanical relays and PWM control seems to be working well.
> config: Enable PID for bed heater in printer-fokoos-odin5-f3-2021.cfg

- docs/Config_Reference.md
- klippy/extras/safe_z_home.py
This change causes the z boundary check to always be performed, regardless of the homed status of the Z axis. 
As described in #4249, not doing this can lead to errors if the motors were disabled near z-max (in this case, the zhop is currently performed, which causes out-of-bounds errors and (possibly worse) leaves the z axis in a homed state).
> safe_z_home: Always perform z limit checks (fixes #4249)

- klippy/extras/gcode_macro.py
This change disallows additional spaces in `gcode_macro` names.
Specifying a gcode macro block like `[gcode_macro MACRO NAME]` does not cause errors or warnings, until the user attempts to use the macro, (at which point the macro will be available under `MACRO` instead). This change simply checks whether the section header contains additional spaces, and raises an error if it does.
Signed-off-by: Florian Heilmann <Florian.Heilmann@gmx.net
> gcode_macro: Disallow whitespace in macro name

- docs/Command_Templates.md
- docs/Config_Reference.md
- klippy/extras/gcode_macro.py
This add a description property to gcode_macro in the same way as used for klipper internal macros. That should help to identify the function of a own macro while using help or the autocomplete function in an console
Signed-off-by: Alex Zellner alexander.zellner@googlemail.com
> gcode_macro: add description property

- docs/Status_Reference.md
- klippy/extras/quad_gantry_level.py
- klippy/extras/z_tilt.py
This is useful for macros that'd like to skip QUAD_GANTRY_LEVEL/Z_TILT_ADJUST if already leveled,
e.x.:
```
{% if not printer.quad_gantry_level.applied %}
QUAD_GANTRY_LEVEL
{% endif %}
```
```
{% if not printer z_tilt.applied %}
Z_TILT_ADJUST
{% endif %}
```
Signed-off-by: Michael Rose <elementation@gmail.com>
> qgl/z-tilt: expose an 'applied' status to allow macros to skip QGL/Z_TILT_ADJUST

- docs/Bed_Mesh.md
- docs/G-Codes.md
- klippy/extras/bed_mesh.py
This implements `BED_MESH_OFFSET`, which can be used to apply offsets to the mesh lookup for correct adjustment on printers with multiple extruders.  The offset should be relative to the primary extruder, so generally it should be the additive inverse of the gcode offset.
The first commit in this series contains a minor refactor of how the `fade_target` is handled. The initial offset is no longer pre-calculated when the mesh is set, instead the offset is applied when the final adjustment is calculated.  This made adding the X and Y offsets less confusing.
Signed-off-by:  Eric Callahan <arksine.code@gmail.com>.
> bed_mesh: add support for X/Y offsets

- docs/Config_Changes.md
- docs/Config_Reference.md
This is a proposal to deprecate the pid_integral_max config option.  I've never seen this option customized and I can't think of a situation where it would make sense to customize it.  So, I think it would be better to simplify the documentation by removing it.  (The feature would still be present, but it would always use its current default.)
-Kevin
> Deprecate pid_integral_max config option

- docs/TMC_Drivers.md
The TMC_Drivers.md document recommends a move of at least 2 seconds after a home attempt to ensure the stall flag is cleared in the driver.  However, in my recent tests I found that this was not always reliable - in particular on corexy.
I find that pausing for 2 seconds is more reliable.  I've been doing that for the last couple of months and have not seen a homing failure since making the change.  (This is on a Voron2 with tmc2209 drivers.)
This change updates the documentation accordingly.
-Kevin
> Recommend pause of 2 seconds during sensorless homing

- config/generic-buddy.cfg
- config/printer-prusa-mini-plus-2020.cfg
- src/stm32/Kconfig
- test/klippy/printers.test
The Buddy board will likely be used by the MK4, so has a separate generic config file.
> Add support for the Prusa Mini+ and the Prusa Buddy board

- docs/Status_Reference.md
- klippy/kinematics/extruder.py
Sometimes an automated filament load is implemented,
but extruder might not always extrude filament due to temperature constraints.
This adds a flag to check if this operation is possible.
Example usage:
```ini
[gcode_macro LOAD_FILAMENT]
gcode:
{% if printer.extruder.can_extrude %}
M117 Loading Filament...
SAVE_GCODE_STATE NAME=__filament__load
M83
G1 E70 F400
G1 E25 F200
M400
RESTORE_GCODE_STATE NAME=__filament__load
M117 Load Complete
{% else %}
M117 Cannot auto-load (MIN TEMP)
{% endif %}
UPDATE_DELAYED_GCODE ID=clear_display DURATION=5
```
> extruder: expose `can_extrude` flag based on temperature

- klippy/extras/pause_resume.py
- klippy/extras/print_stats.py
- klippy/extras/virtual_sdcard.py
Before this change, a `CANCEL_PRINT` would set a `print_stats` to `paused`
that would later be workaround-ed with `moonraker`/`fluidd`/`mainsail` to re-define
`CANCEL_PRINT` to transition to `standby` and forcefully unload file.
This adds a proper `canceled` state. This additonally closes a file
from a `virtual_sdcard` context for `canceled`/`error`, as such state is no longer
resumable from this point.
This removes workarounds needed by `fluidd`/`mainsail` as previously they would ask to:
- https://docs.fluidd.xyz/configuration/initial_setup#cancel_print
- https://docs.mainsail.xyz/necessary-configuration#for-pause--resume--cancel-functionality
- https://github.com/Arksine/moonraker/blob/master/moonraker/components/history.py#L191
- manually call `CLEAR_PAUSE` to mark `pause_resume` as …
> print_stats: add `cancelled` when `CANCEL_PRINT` used

- docs/Status_Reference.md
- klippy/extras/dotstar.py
- klippy/extras/neopixel.py
This request adds a get_status() method for both the neopixel and dotstar modules.  Status will return a `color_data` field that contains a list of RGB(W) values for each led in the chain.  For example, fetching the red value for the first led in a chain might look like the following:
```
printer["neopixel my_led"].colordata[0].R
```
This is primarily useful for clients that wish to provide a UI for changing LED settings, however it could have some use for templates as well.
> neopixel: add a get_status() method

- config/printer-prusa-mini-plus-2020.cfg
- docs/Config_Reference.md
Also clarifies the documentation for rotation_distance in the
stepper docs.
Signed-off-by: Matthew Lloyd <github@matthewlloyd.net>
> config: Specify gear_ratio for Prusa Mini+ extruder

- docs/Status_Reference.md
- klippy/extras/display/menu.cfg
- klippy/extras/virtual_sdcard.py
This provides a comprehensive information if currently we have a file loaded.
Previously:
- we used `print_stats` to know if something is loaded, which is not always correct nor true
- this provides a clear information if a `virtual-sdcard` file is loaded and currently printing
- provides a clear purpose of `v-sd` to track a file progress, `print_stats` to track print progress (which might be coming from manual stream of commands [not yet possible])
Signed-off-by: Kamil Trzcinski <ayufan@ayufan.eu>
> virtual_sdcard: add `file_path` and `file_size` to `status`

- docs/G-Codes.md
- docs/Manual_Level.md
- klippy/extras/screws_tilt_adjust.py
Found this useful when leveling a Prusa Mini+ using my silicone o-ring mod. Also adds docs and clarifies code where I found it confusing as a first-time user.
Example output:
```
$ G28
$ SCREWS_TILT_CALCULATE
// probe at 120.000,93.000 is z=1.737500
// probe at 120.000,8.000 is z=1.765000
// probe at 180.000,8.000 is z=1.763750
// probe at 180.000,93.000 is z=1.725000
// probe at 180.000,178.000 is z=1.736250
// probe at 120.000,178.000 is z=1.765000
// probe at 35.000,178.000 is z=1.810000
// probe at 35.000,93.000 is z=1.758750
// probe at 35.000,8.000 is z=1.777500
// 01:20 means 1 full turn and 20 minutes, CW=clockwise, CCW=counter-clockwise
// middle screw (base) : x=120.0, y=93.0, z=1.73750
// front middle screw : x=120.0, y=8.0, z=1.76500 : adjust CW 00:03
// front right screw : …
```
> screws_tilt_adjust: Add DIRECTION parameter to SCREWS_TILT_CALCULATE

- config/generic-mks-robin-e3.cfg
Z stepper was not working on my MKS Robin E3 new Klipper install. I reviewed the MKS documentation (https://github.com/makerbase-mks/MKS-Robin-E3-E3D/blob/master/hardware/MKS%20Robin%20E3%20V1.1_003/MKS%20Robin%20E3%20V1.1_003%20PIN.pdf) and noticed that the  z stepper pinout changed for board version 1.1. This config file update contains comments which note the change to future users. 
Signed-off-by: Eli Hyman eli.hyman@gmail.com
> MKS Robin e3 Config File Update

- docs/Config_Reference.md
- klippy/extras/duplicate_pin_override.py
- klippy/pins.py
Normally, if one uses the same pin multiple times in a config file it is the result of an error, and the Klipper code will report a "pin XXX used multiple times in config" error.  However, sometimes it is useful to use the same pin multiple times for debugging purposes.
This PR adds a new config option to override the default error check.
-Kevin
> Add debugging tool to permit a pin to be used multiple times in the config file

- klippy/extras/temperature_mcu.py
- scripts/flash_usb.py
- src/stm32/Kconfig
See https://github.com/henrikssn/TurboCAN
Temp compensation logic is common across STM32F0: https://techoverflow.net/2015/01/13/reading-stm32f0-internal-temperature-and-voltage-using-chibios/
> Add support for STM32F072 (used in the TurboCAN board)

- test/configs/stm32f446.config
- test/klippy/printers.test
Fixes 2 occurrences where the STM32F407 was in a place specific to the STM32F446
One commit was...
Signed-off-by: Charles Pickering <charles.pickering@live.com>
> workflows: Fix typos related to STM32F446

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/samd_sercom.py
The current setup doesn't make it possible to configure multiple samd sercom instances on multiple micro-controllers.  This updates the code to make it possible, but it does make a non-backwards compatible change (for those users using a samd_sercom config).
@FHeilmann - FYI.
-Kevin
> Specify ATSAMD sercom explicitly in a samd_sercom config option

- docs/Benchmarks.md
- src/stm32/Kconfig
W/o this patch, STM32F401 can't select bootloader offset. This is necessary for scripts/usb-flash.py use STM32 HID bootloader instead of DFU.
I use STM32F401CC board from WeAct Studio. It comes with preloaded HID bootloader. However, the preloaded bootloader is not compatible with HID Bootloader from Serasidis. If anyone else turns out at the same situation, I made some patch on WeAct bootloader so it compatible with klipper flashing mechanism. 
https://github.com/henkyprayoga/WeAct_HID_Bootloader_F4x1/releases/tag/v1.1-stm32-hid-bootloader
Just download the zip and flash it using DFU.
> Allow STM32F401 boards to use STM32 HID Bootloader

- src/rp2040/Kconfig
- src/rp2040/Makefile
- src/rp2040/gpio.h
- src/rp2040/hard_pwm.c
This implements hardware PWM support for the rp2040. The maximum value(100% duty) is set to 255 to match the other controllers. Cycle time is clamped automatically, and uses the full 8.4 fractional range of the rp2040 PWM block. This allows a maximum PWM frequency of 490kHz and a minimum frequency of 1915 Hz.
Because the rp2040 timer runs at only 12MHz and the PWM system runs at full 125 MHz, the `cycle_time` received from Klippy needs to be scaled up, not down as is the case with e.g. the LPC176x and STM32 targets. To maximize the precision of this step, a little bit of extra math is done. This is documented in the code.
/Lasse
> rp2040: hardware PWM support

- src/rp2040/Kconfig
- src/rp2040/Makefile
- src/rp2040/gpio.h
- src/rp2040/spi.c
This implements SPI for the rp2040 target. All output groupings of both SPI blocks are available for use.
Because each blocks has multiple outputs, I called the first output of each block `spi0a` and `spi1a`. If you prefer another naming scheme, let me know!
/Lasse
> rp2040: implement SPI

- src/stm32/Kconfig
The Eryone ER-20 is a STM32F103 based 3D printer which ships with a 16KiB bootloader. Their official version of Marlin starts at 0x08004000.
This can be seen here. https://github.com/Eryone/STM32/blob/master/Marlin_ER20/buildroot/share/PlatformIO/scripts/eryone_mini_STM32f103.py
Fixed signoff issue with previous pull request: https://github.com/KevinOConnor/klipper/pull/4476
> Add 16KiB bootloader option for STM32F103

- docs/Config_Reference.md
- klippy/extras/controller_fan.py
- klippy/extras/stepper_enable.py
Allows contoller_fan sections to monitor only certain steppers instead of
all of them, similar to how heaters are currently handled. The default is
to monitor all steppers except extruders for backwards compatibility. Note
that this module (accidentally?) never actually monitored extruder
steppers.
> controller_fan: Add "stepper" config option

- config/sample-macros.cfg
The M300 example macro now sets the PWM cycle time to generate the requested
frequency. 'scale' did not have the desired effect. Duty cycle is now
fixed at 0.5. All S parameter values less than 1 generate a 1Hz 'tone'
to avoid division-by-zero.
Signed-off-by: Stefan Holst <mail@s-holst.de>
> docs: Fix M300 beeper example.

- klippy/msgproto.py
- scripts/flash-sdcard.sh
- scripts/spi_flash/spi_flash.py
Updates firmware validation to use a dictionary if provided (or found
when updating from the default out/ directory).
Validation without a dictionary still checks the following (in order):
1. Active firmware's raw dictionary changed after update
2. Checksum of firmware.cur matches expected
This PR depends on #4381. Hopefully I did this right, since it's the first time I've stacked PRs. I would have expected the diff to be against the other PR, but the UI seems to display a much larger diff against master.
> spi_flash: Support firmware dictionary validation

- klippy/extras/tmc2209.py
- klippy/extras/tmc_uart.py
An investigation by @ReXT3d found that the tmc2209 UART behavior is greatly improved by setting SENDDELAY=2.  ( https://klipper.discourse.group/t/intermittent-tmc-uart-weirdness/454 ) As a guess, the additional delay helps the chips identify each others responses on shared UART lines - which may improve their ability to keep synchronized with the UART traffic.
This PR also increases the default UART baud rate to 40000 for 32bit MCUs.  There shouldn't be any harm in using a faster speed on more modern MCUs (the slower AVR chips will continue to use a baud of 9000).
-Kevin
> Trinamic stepper motor UART updates

- docs/G-Codes.md
- klippy/extras/manual_probe.py
- klippy/extras/probe.py
Created two new extended gcodes: PROBE_UPDATE_OFFSET, and Z_ENDSTOP_UPDATE_POSITION
These use the z gcode offset to revise the probe offset, or z endstop position
allowing users to make a frequently used babystepping value permanent without
manual config editing.
Signed-off-by: Ben Eastep <shifting@shifting.ca>
> Probe & manual_probe: add ability to save babystepping

- docs/RPi_microcontroller.md
Module: Documentation
Whilst this line is in Measuring_Resonances.md, it's causing some confusion for users and it should be in the RPi Microcontoller guide because not all RPi users are measuring resonances, and SPI appears to be a hard requirement for the RPi mcu
Signed-off-by: Rowland Straylight rowlandstraylight@gmail.com
> docs: Make sure SPI is enabeld

- klippy/extras/display/menu.cfg
This fixes the bug introduced by https://github.com/KevinOConnor/klipper/commit/f1091a484bfbf2cc5676e3a6fcd595172f123f67.
The problem is that condition was returning string which
could not be converted to boolean. We solve that by showing
`Start Printing` when `is_active`.
```
ERROR:root:Unhandled exception during run
...
File "/opt/klipper/klippy/extras/display/menu.py", line 117, in eval_enable
return bool(ast.literal_eval(self._enable_tpl.render(context)))
File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "/usr/lib/python2.7/ast.py", line 37, in parse
return compile(source, filename, mode, PyCF_ONLY_AST)
File "<unknown>", line 1
/opt/octoprint/uploads/wait_print.gcode
```
> menu: fix crash when opening SDCard menu while printing

- docs/_klipper3d/mkdocs.yml
Solves issue #4538 by disabling the `navigation.instant` feature of the mkdocs-material theme which does not work well with Safari.
> klipper3d : anchor links not working on Safari

- docs/Status_Reference.md
- klippy/chelper/__init__.py
- klippy/chelper/stepcompress.c
- klippy/chelper/stepcompress.h
- klippy/chelper/trapq.c
- klippy/chelper/trapq.h
- klippy/extras/force_move.py
- klippy/extras/manual_stepper.py
- klippy/extras/motion_report.py
- klippy/extras/stepper_enable.py
- klippy/kinematics/extruder.py
- klippy/mcu.py
- klippy/stepper.py
- klippy/toolhead.py
This adds a new module that adds diagnostic reporting on Klipper's motion system.  This initial PR adds support for dumping out the motion queues (the trapq history and the stepper queue_step history) on a shutdown event.
I plan to continue adding additional support to the module.  My goal is to make it possible to export the trapq and step queues in near real-time via the "api server" for analysis purposes.
Separately, I've also locally attempted to extend this new module to report the current "live" toolhead position (ie, the position of the toolhead at the current time - not the last requested gcode position).  Unfortunately, my current code produces misleading results after a `toolhead.set_position()` call.  If I get that working though, I'll push it in a separate PR.
-Kevin
> New motion_report module

- klippy/kinematics/idex_modes.py
Fix get_status to be called without eventtime parameter: https://github.com/KevinOConnor/klipper/pull/3956#issuecomment-890457812
Signed-off-by: Fabrice GALLET tircown@gmail.com
> idex_modes: fix get_status

- klippy/extras/probe.py
command was accessing the wrong variable for the existing z offset,
leading to bad behavior.
--signed-off-by: Ben Eastep <shifting@shifting.ca>
> Probe: bugfix to z_offset_apply_probe

- docs/Code_Overview.md
- klippy/extras/endstop_phase.py
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2209.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
- klippy/mcu.py
- klippy/stepper.py
This PR updates Klipper so that it always tracks the motor phase that the Trinamic drivers are using.  The motor phase corresponds with the amount of current going in each of the two motor coils, and thus provides information on the commanded angle of the stepper motor.
This information is useful for high level motion analysis.  It's also useful to help diagnose errors should the micro-controller and stepper driver become out of sync on the step position.
To implement this support, the code will attempt to query the driver's phase every time the Klipper host software starts, after every home/probe attempt, and after any detected stepper driver reset.  The code will log a warning if the driver and micro-controller get out of sync.
-Kevin
> Track Trinamic driver motor phase

- klippy/extras/bed_screws.py
It always bothered me that on my Ender 3 Pro with 4 bed screws I had to accept 7 times if I adjusted the first screw and after that screw every screw was fine. So I rewrote the code that it would finish the bed_screws_adjust command when you accepted all screws without a adjust in between no matter which screw you accepted first.
In the commit title I wrote 4 consecutive accepts but I meant as many as the printer has screws but just thought of my Ender 3.
I tested the code (except for the fine tuning) on my Ender 3 where it worked fine. 
This is my first contribution to a open-source project ever so please let me know if I did anything wrong.
> bed_screws: Finish bed_screws_adjust after 4 (corrected: n screws) consecutive accepts

- docs/Status_Reference.md
The example given for accessing the existing color values of a neopixel chain in the [status reference documentation](https://www.klipper3d.org/Status_Reference.html#neopixel-dotstar) is missing an underscore, so it doesn't work as expected (which confused me while trying to read the values from some neopixels). This change adds it in so the example works!
Hopefully I've submitted this change correctly — please let me know if there's anything I need to update 😊
> docs: Fix reference to neopixel color_data

- klippy/extras/output_pin.py
This fixes the time_difference calculation for rescheduling a resend-timer.
Previously, any `output_pin` with activated `maximum_mcu_duration` would trigger two set_pin messages.
> output_pin: fix time difference calculation

- config/generic-bigtreetech-e3-rrf-v1.1.cfg
- test/klippy/printers.test
Mostly based on existing configurations and official [pin docs](https://github.com/bigtreetech/BTT-E3-RRF/blob/master/BTT%20E3%20RRF%20V1.1/Hardware/BTT%20E3%20RRF%20V1.1-PIN.pdf), I've tested this in my own printer
> config: Adds generic config for BigTreeTech E3 RRF 1.1

- docs/Bed_Mesh.md
- klippy/extras/bed_mesh.py
Added an optional parameter to allow bed_mesh_calibrate directly into the named profile instead of `default`. If not provided, it will default to the current behavior of `default`.
A use case would be when a person creates a mesh for a different temperature or maybe a different build surface, they can specify the name then. Otherwise they have to remember to run bed_mesh_profile save=name when they are done and potentially overwrite their `default` mesh if they already have one.
> bed_mesh_calibrate: Added PROFILE name option

- klippy/extras/htu21d.py
module: htu21d.py
Just a quick fix for the humidity reading.
Line 202: should be self.humidity instead of self.temp
Signed-off-by: Dawid Murawski <dawid.m@gmx.net>
> Update htu21d.py: Fix humidity reading

- config/printer-creality-ender3max-2021.cfg
knob/clicker doesnt work with current values. Switching to values from printer-creality-ender3pro-2020.cfg work as expected. 
Signed-off-by: Shawn Foley shawnifoley@gmail.com
> correct pins for ender3max display

- docs/Config_Changes.md
- klippy/configfile.py
- klippy/extras/adxl345.py
- klippy/extras/bed_mesh.py
- klippy/extras/bed_screws.py
- klippy/extras/board_pins.py
- klippy/extras/controller_fan.py
- klippy/extras/delta_calibrate.py
- klippy/extras/display/menu_keys.py
- klippy/extras/duplicate_pin_override.py
- klippy/extras/endstop_phase.py
- klippy/extras/gcode_button.py
- klippy/extras/heater_fan.py
- klippy/extras/homing_heaters.py
- klippy/extras/multi_pin.py
- klippy/extras/probe.py
- klippy/extras/quad_gantry_level.py
- klippy/extras/resonance_tester.py
- klippy/extras/safe_z_home.py
- klippy/extras/screws_tilt_adjust.py
- klippy/extras/static_digital_output.py
- klippy/extras/tmc.py
- klippy/extras/tmc_uart.py
- klippy/extras/z_tilt.py
- klippy/stepper.py
This change adds new helper functions to the main `config` object for parsing out lists of numbers, lists of strings, and lists of lists.  I've also gone through and updated many places in the code that manually parse lists to use these new helper functions.
The main goal of this change is so that the `printer.configfile.settings` object will now contain lists for these existing config settings (instead of the encoded strings they currently have).  So, for example, where `printer.configfile.settings.extruder.gear_ratio` might have previously had something like `"50:17"`, it would now have `[[50.0, 17.0]]`.  This should make it easier for API clients to access the core configuration.
@Arksine , @cadriel, @meteyou - FYI, this PR changes the behaviour of `printer.configfile.settings`.  I …
> Add config reading helpers for parsing lists in the config file

- docs/Config_Reference.md
- docs/Multi_MCU_Homing.md
- docs/Overview.md
- docs/_klipper3d/mkdocs.yml
- klippy/mcu.py
This PR adds initial (currently incomplete) support for homing and probing when steppers and their endstops are on different micro-controllers.  As an example, this may be useful with "toolhead boards" that have a Z probe attached, but don't directly control the Z stepper motors.
The main challenge with multi-mcu homing is having a reliable way to stop the steppers, even if there is a communication fault during homing.  (Otherwise, if the mcu with the endstop is unable to communicate with the mcu controlling the steppers, the steppers may continue to move the carriage past the endstop, potentially causing significant damage.)  To account for this issue, the code in this PR uses a system where each micro-controller announces that it is still active every 10ms and requires that it receive a …
> Multi mcu homing

- docs/Status_Reference.md
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2209.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
This PR adds a `get_status()` method to the TMC driver objects.  The stepper phase information and recently queried DRV_STATUS information is reported there.
@Arksine , @meteyou , @cadriel - FYI, this allows access to the driver temperature warning flag (eg, `printer["tmc2209 stepper_x"].drv_status.otpw`).  I suspect that information may be of interest to the front-ends.
-Kevin
> Export tmc driver status

- klippy/stepper.py
This adds the ability to, for motors on a rail, specifying another motor to use as endstop, effectively 'linking' the motor to the endstop.
This is useful for printers with multiple motors per rail, e.g. if a machine has two belts for one axis, and two motors for each belt. Using linking, it's possible to, in software, let the motors that share belts, also share their endstop pin.
We've been testing this for some time on the Annex Engineering Tycho printer, which has 8 motors on the XY gantry in just such a configuration(4 belts, 2 motors per belt).
To allow the general case to work, where endstops from both higher and lower indexed rail steppers can be used on any other rail stepper, a two-pass approach is used. All steppers are added, and steppers with endstop pointers are then linked …
> Endstop linking

- docs/G-Codes.md
- klippy/extras/tuning_tower.py
This change is fully backwards compatible, and merely adds alternate syntax that is easier to configure for certain types of tuning tower. Proposed here: https://klipper.discourse.group/t/feedback-easier-tuning-tower-syntax/438
Signed-off-by: Matthew Lloyd <github@matthewlloyd.net>
> tuning_tower: Add STEP and SKIP parameters as alternate tuning tower syntax

- config/sample-pwm-tool.cfg
- docs/Using_PWM_Tools.md
This  PR adds the referenced PWM-Tool config example, which closes #4410.
> Add referenced config example

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/heaters.py
A larger smooth_time results in a slower reaction time for the PID.
This increased delay can cause temperature oscillations with high
power heaters.  Many boards produce good results without any
smoothing.  So, it seems a smooth_time of 1 second is a better
default.
Reported by @ReXT3D.
This was discussed at https://klipper.discourse.group/t/default-extruder-smooth-time-is-too-long-causing-temperature-oscillations/699 .
I'm inclined to further reduce the default `smooth_time` after the v0.10.0 release, as I get even better results on my printers with smoothing entirely disabled.
-Kevin
> Change default smooth_time from 2 seconds to 1 second

- scripts/update_chitu.py
This makes update_chitu a pure function: same file in — same file out.
That's something I need to make Nix builds for firmware itself reproducible.
Signed-off-by: Vladimir Serov <me@cab404.ru>
> scripts/update_chitu.py: generating update uuid based on file hash

- src/stm32/stm32h7_adc.c
- src/stm32/stm32h7_serial.c
This is a continuation of work on #3912
Set the adc to 12 bit mode, as promised.
I also merged the work-stm32h7-20210902 branch into my fork, and everything still works. So the changes should be fine (I cant easily test the work-stm32h7-20210902 branch without reinstalling on python2).
> stm32h7 port - set adc to 12bit mode

- config/generic-bigtreetech-skr-2.cfg
module: config/generic-bigtreetech-skr-2.cfg
This is just a short inline comment about Bigtreetech's implementation of the "anti-reversal stepper protection" and the way it should be handled in the Klipper printer configuration.
This was discussed in the Klipper discord around 8 to 9 AM UTC September 10, 2021.
Signed-off-by: Jerry Chapman <truckershitch@hambone.e4ward.com>
> Document motor_power pin

- docs/Status_Reference.md
- klippy/configfile.py
- klippy/extras/gcode_macro.py
- klippy/extras/heaters.py
- klippy/extras/temperature_host.py
- klippy/mcu.py
- klippy/stepper.py
This PR will add a new `printer.configfile.warnings` entry containing a string message reporting any deprecated config options.  This should be useful for warning users about needed config updates before they become errors.
@Arksine , @meteyou , @cadriel - it would be great if the frontends could prominently display this information.
-Kevin
> Export config file warnings for deprecated options

- docs/CONTRIBUTING.md
The Korean and French translations are growing fast, so we need to be prepared...
Signed-off-by: Yifei Ding <yifeiding@protonmail.com>
Additionally, I propose adding a Weblate link to each of the markdown file. The following format can be used:
raw:
```markdown
[Translate this document using Weblate](https://hosted.weblate.org/projects/klipper/<documentation>)
```
rendered:
[Translate this document using Weblate](https://hosted.weblate.org/projects/klipper/<documentation>)
> docs: add Translation Contributior Guide

- config/generic-bigtreetech-octopus.cfg
PB10 is definitely the Heater pin.
with reference from https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-V1.0/blob/master/Hardware/BIGTREETECH%20Octopus.pdf the Diag 0 1 2 pins have been added
Signed-off-by: Arne Schwarck <arneschwarck@gmail.com>
> Fix diag pins for BTT Octopus

- docs/BLTouch.md
module: BLTOUCH DOCUMENTATION
Klipper with Fluid complains about `position_endstop` line when `endstop_pin: probe:z_virtual_endstop` is used.
Signed-off-by: Ilia Rebane <Agilatosay@gmail.com>
> Update BLTouch.md to prevent position_endstop error

- klippy/extras/idle_timeout.py
This resolves an issue where the idle_timeout attempts to transition from "Ready" to "Idle" when the printer is shutdown.  Currently this will result in a failed attempt to run the idle gcode, which will repeat every second until Klippy is restarted.
The following steps can be taken to reproduce the issue:
1) Set the idle timeout to a low value: `SET_IDLE_TIMEOUT TIMEOUT=2`
2) Run a command to put the printer in the `Printing` state: `G4 P1000`
3) Emergency Stop
> idle_timeout: exit the timer if the printer is shutdown

- docs/Benchmarks.md
- docs/Config_Changes.md
- klippy/console.py
- klippy/extras/gcode_macro.py
- klippy/extras/heaters.py
- klippy/extras/temperature_host.py
- klippy/mcu.py
- klippy/pins.py
- klippy/stepper.py
There have been several options deprecated in late 2020 and in early 2021.  This change removes support for those options - anyone that has not yet converted their configs will receive an error after this change is applied.  I plan to commit this early next week (~20211102).
Several deprecated features have been removed.  The stepper
`step_distance` option has been removed (deprecated on 20201222).  The `rpi_temperature` sensor alias has been removed (deprecated on
20210219).  The mcu `pin_map` option has been removed (deprecated on 20210325).  The gcode_macro `default_parameter_<name>` and macro access to command parameters other than via the `params` pseudo-variable has been removed (deprecated on 20210503).  The heater `pid_integral_max` option has been removed (deprecated on …
> Remove deprecated features

- src/linux/Makefile
- src/linux/console.c
- src/linux/internal.h
- src/linux/sensor_ds18b20.c
- src/linux/timer.c
Use Unix signals in software timer implementation.  This makes the code a little more efficient.
This was part of work I did earlier in the year as part of the discussion on #4201 and #3387 .  It should be generally useful though, so I think it's worth merging.
@tntclaus - fyi.
-Kevin
> Use Unix signals in linux mcu code to notify when a timer is pending

- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/MCU_Commands.md
- klippy/extras/tmc.py
- klippy/extras/tmc2660.py
- klippy/stepper.py
- src/Kconfig
- src/atsam/Kconfig
- src/atsamd/Kconfig
- src/avr/Kconfig
- src/lpc176x/Kconfig
- src/rp2040/Kconfig
- src/stepper.c
- src/stm32/Kconfig
The current mcu build defaults to a 2us step pulse duration.  Changing this duration requires recompiling of the micro-controller code today and any change applies to all steppers on the given mcu.  This PR changes the code so that the pulse duration is no longer a compile-time setting and is instead configured for each stepper in a new `step_pulse_duration` option in the printer.cfg file.
Along with this change, TMC drivers configured via UART or SPI mode will automatically enable new optimizations for generating step pulses.  In particular, the `DEDGE=1` driver setting is enabled so that steps are taken on both rising and falling edges of the step gpio pin.  These optimizations make it possible for the default mcu build to obtain dramatically higher step rates on 32-bit …
> Support custom step pulse duration at run-time and optimize for tmc drivers

- src/stm32/stm32f4.c
This PR resets the peripheral clocks on init and performs a factory reset on the peripheral registers as they are enabled in `enable_pclock()`.  The implementation mimicks how it is handled with the STM32F1, with the FLITF and SRAM clocks enabled.
As bit 8 of APB2RSTR resets all 3 ADCs I thought it wise to avoid it.  My assumption is that it would cause an unwanted reset if multiple ADCs are enabled.
This should resolve #4838 and #4856.
> stm32f4: resolve bootloader issues

- config/generic-bigtreetech-skr-2.cfg
- config/generic-duet3-mini.cfg
- config/generic-mks-rumba32-v1.0.cfg
- config/generic-rumba.cfg
- config/kit-voron2-250mm.cfg
- config/printer-mtw-create-2015.cfg
- config/printer-wanhao-duplicator-i3-v2.1-2017.cfg
- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/heaters.py
- klippy/extras/temperature_sensors.cfg
- klippy/extras/thermistor.py
This PR moves the default thermistor definitions from thermistor.py to a new temperature_sensor.cfg file, introduces a new "Generic 3950" thermistor, and deprecates the "NTC 100K beta 3950" definition.
As discussed in #4054 , it seems most real-world "beta 3950" sensors don't actually follow a true "beta 3950" temperature curve, and instead follow a curve defined in the new "Generic 3950" table.  Deprecating the "NTC 100K beta 3950" definition seems like the best way to raise awareness and move printers over to a more accurate configuration.
-Kevin
Edit: Change name of new thermistor to "Generic 3950".
> Deprecate "NTC 100K beta 3950" thermistor

- docs/Benchmarks.md
- docs/Features.md
This PR updates the benchmarks after recent code changes.  There have been dramatic increases to the 32bit micro-controllers due to PR #4851 .
Unfortunately, I don't have access to the Duet2 Maestro nor the Duet2 Eth/wifi.  It would be great if someone with each of those boards could run through the steps at https://github.com/Klipper3d/klipper/blob/work-benchmarks-20211104/docs/Benchmarks.md and report the 1 stepper and 3 steppers benchmarks for each of those boards.
-Kevin
> Update benchmarks after stepper and scheduler changes

- docs/Config_Reference.md
- klippy/extras/temperature_sensors.cfg
module: extras/temperature_sensors.cfg
this thermistor is the 104NT-4 resold by Trianglelab (and others on Ali),
as well as the 300 degree resold by Slice Engineering, both of which use the
same RT table (TL even links to the ATC Semitec website)
see the 300 C tab on the Slice spreadsheet:
https://docs.google.com/spreadsheets/d/1904x5JK-Sup-cX5DqHiiZWaFVTK6_PQBFxgi_6yXEJw/edit#gid=934228925
as well as the TL product page:
https://www.aliexpress.com/item/32843785247.html
in addition to the RT table link provided in temperature_sensors.cfg
Signed-off-by: Geoffrey Young <geoffrey.young@gmail.com>
> temperature_sensors: add ATC Semitec 104NT-4-R025H42G thermistor

- klippy/extras/gcode_macro.py
This resolves an issue where subscriptions will not update because the `last_query` contains a reference to an object returned by `get_status()`.  Currently this is known to affect `gcode_macro` variables.
> webhooks: create a deep copy for status queries

- docs/HallFilamentWidthSensor.md
- docs/Manual_Level.md
- docs/Measuring_Resonances.md
- docs/Resonance_Compensation.md
- docs/Status_Reference.md
- docs/TMC_Drivers.md
- docs/TSL1401CL_Filament_Width_Sensor.md
- docs/Using_PWM_Tools.md
- docs/skew_correction.md
- Aligned some tables
- Added blank line to before and after some lists to match most lists
- Changed some bold text to titles
- Added blank line before and after some titles
- Removed some extra blank lines
- use fenced code block instead of the indented code block to match other docs
- Corrected some indentation errors on the title and lists
Signed-off-by: Yifei Ding <yifeiding@protonmail.com>
> docs:  List/Table/Title Indentation Correction

- src/stm32/stm32h7_serial.c
STM32H7 SERIAL
Add a UART4 definition. This allows UART4 to be used on stm32h7 processors. This UART exists on the BTT-SKR-SE-BX board.
Signed-off-by: Aaron DeLyser bluwolf@gmail.com
> STM32H7 - Add UART4

- docs/Command_Templates.md
- klippy/extras/display_status.py
- klippy/extras/gcode_macro.py
- klippy/extras/respond.py
- klippy/gcode.py
This adds a new `rawparams` pseudo-variable to the `gcode_macro` template context.
The main usage for this is to allow easier override of an existing G-Code like `M117`, where we don't have any parameters (so `params` is useless) but instead take the whole message after the gcode.
Here's an example of it:
```yaml
[gcode_macro M117]
rename_existing: M117.1
gcode:
M117.1 { rawparams }
M118 { rawparams }
```
In the above example, any message sent via `M117` would also be mirrored with `M118`.
> gcode_macro: Add "rawparams" pseudo-variable

- klippy/extras/print_stats.py
When executing `CANCEL_PRINT` (directly or as part of a macro) as the first G-code instruction Klipper crashes with the following:
```
File "/home/pi/klipper/klippy/klippy.py", line 201, in run
self.reactor.run()
File "/home/pi/klipper/klippy/reactor.py", line 269, in run
g_next.switch()
File "/home/pi/klipper/klippy/reactor.py", line 310, in _dispatch_loop
timeout = self._check_timers(eventtime, busy)
File "/home/pi/klipper/klippy/reactor.py", line 156, in _check_timers
t.waketime = waketime = t.callback(eventtime)
File "/home/pi/klipper/klippy/extras/virtual_sdcard.py", line 291, in work_handler
self.print_stats.note_complete()
File "/home/pi/klipper/klippy/extras/print_stats.py", line 45, in note_complete
self._note_finish("complete")
File …
```
> print_stats: Fix exception when canceling in/as first G-code

- config/generic-bigtreetech-skr-2.cfg
Updates for generic-bigtreetech-skr-2.cfg to include comment on newly shipped board with STM32F429 instead of the original STM32F407
Signed-off-by: James Hartley james@hartleyns.com
> add flash details for STM32F429

- klippy/gcode.py
﻿This PR allows now to use rename_existing at GCodes internally registered as register_mux_command
The changes where done by the discord user dalegaard.
At the tide integrated UIs like fluidd/mainsail you need to use the same GCode name as the base klipper. This was not possible for some of the GCodes. The user only sees an internal error with no explanation what the problem was. After the merge that problem would be gone.
I personally testet it with:
- SET_FILAMENT_SENSOR SENSOR
- SET_PIN
- SET_HEATER_TEMPERATURE
- ACTIVATE_EXTRUDER
Test Case looks like: 
```
[gcode_macro SET_PIN]
rename_existing: SET_PIN_BASE
gcode:
{% set get_params = [] %}
{% for key in params %}
{% set get_params = get_params.append(key + "=" + params[key])  %}
{% endfor %}
{action_respond_info(get_params|join(" "))} …
```
> gcode: Allow rename_existing also for register_mux_command

- docs/Resonance_Compensation.md
I believe I've found typo in docs
Signed-off-by: Joseph Vilimas 4to5@protonmail.com
> Fixed typo in config option name

- docs/CONTRIBUTING.md
I'm hopelessly behind on reviews of Klipper PRs, and the unfortunate reality is that I do not think I will be able to get through the backlog.  This PR is intended to start a discussion to see if we can get more people to help perform reviews.
I find that the majority of feedback I give on reviews are for "procedural items".  I find that I frequently make similar comments (eg, must have signed-off-by line, must follow documentation, must update documentation) on many reviews.  I think this work done to facilitate merging (while trying to keep a high-quality submission process) could be spread to many more people.
The proposed process is documented at https://github.com/Klipper3d/klipper/blob/work-review-20211116/docs/CONTRIBUTING.md .
This is a proposal and I'm looking for feedback on it. …
> Proposal for formalizing review process for PRs

- src/stm32/stm32h7.c
https://github.com/Klipper3d/klipper/commit/dc3ac2b424dc2f915f825227ac941ab1b982ed21 breaks the STM32H7 processor GPIO because it's using the incorrect register.
This PR fixes the issue.
Signed-off-by: Aaron DeLyser <bluwolf@gmail.com>
> BUGFIX: Fix the GPIO register for stm32h7

- src/stm32/Makefile
- src/stm32/clockline.c
- src/stm32/internal.h
- src/stm32/stm32f0.c
- src/stm32/stm32f1.c
- src/stm32/stm32f4.c
- src/stm32/stm32g0.c
- src/stm32/stm32h7.c
Unify the handling of the enable_pclock() and is_enabled_pclock() code
across all stm32 chips.  All chips will now perform a peripheral reset
on enable_pclock() (this is a change for stm32f0 and stm32h7).  The
enable_pclock() code will now also disable irqs during the enable.
It is hoped this will make the code a little simpler and a little easier to maintain.
-Kevin
> Unify enable_pclock() code on stm32

- docs/Config_Changes.md
- docs/Measuring_Resonances.md
- scripts/calibrate_shaper.py
- scripts/graph_accelerometer.py
Also updated instructions to install python3-numpy and
python3-matplotlib Python packages.
> scripts: Migrated shaper calibration scripts to Python3

- docs/BLTouch.md
There have been several reports of recent bltouch clones not supporting "touch_mode".  This PR updates the docs to alert users to this.
Reported by @XoBoR, @grantemsley, and @mortenmoulder.
-Kevin
> Note some BL-Touch clones do not support touch_mode in BLTouch.md

- lib/.gitignore
- lib/README
- lib/rp2040/boot/picoboot.h
- lib/rp2040/pico/platform.h
- lib/rp2040_flash/Makefile
- lib/rp2040_flash/main.c
- lib/rp2040_flash/picoboot_connection.c
- lib/rp2040_flash/picoboot_connection.h
- scripts/flash_usb.py
- src/rp2040/Makefile
This adds `make flash` support for the rp2040 target. Flashing is performed using `picotool` and doesn't require root.
The user specifies the serial of the rp2040 they wish to flash as the device. This device is looked for and reset into bootsel mode, after which picotool is invoked on the first rp2040 found. Sadly, an rp2040 in bootsel mode doesn't appear to expose its flash serial number in any way, which means we can't be more specific in which target we flash.
> rp2040: add make flash support

- config/generic-mellow-super-infinty-hv.cfg
TMC2130/5160 can make use of `spi3`, which is operated on the software SPI pins in the current configuration. The supplied defaults for software SPI do not currently work.
Signed-Off-By: Wijnand Modderman-Lenstra <maze@maze.io>
> Update generic-mellow-super-infinty-hv.cfg to use hardware SPI

- src/rp2040/Kconfig
- src/rp2040/Makefile
- src/rp2040/gpio.h
- src/rp2040/i2c.c
This implements I2C for the rp2040 target. All output groupings of both
I2C blocks are available for use.
> rp2040: implement I2C

- docs/Config_Reference.md
- klippy/extras/neopixel.py
Neopixel: Add "BRG" color order and documentation update
User "Lanman1#5094" on the Voron Discord discovered that their addressable RGB strip used the unusual "BRG" color order and this was verified using an WLED module to control them as well. Color order and documentation has been updated to support this obscure but still valid color order.
Signed-off-by: Timothy Abraham timothyabe93@gmail.com
> Update neopixel.py to add BRG color order

- klippy/extras/pause_resume.py
Previously accidentally used 'default' state name instead of the
stated one ('PAUSE_STATE'). This might collide with user usage of the
SAVE_GCODE_STATE macro.
> pause_resume: Do not klobber default state name by accident.

- config/printer-creality-cr6se-2021.cfg
The fan pin PA0 is not correct for the 2021 revision of the CR-6 SE using the
4.5.3 revision of the Creality board. Changed the pin to PB15 in order to
get it working
Signed-off-by: Filip Trplan <filip@trplan.si>
> Correct Fan Pin for the CR-6 SE 2021 Example Config

- docs/Config_Changes.md
- klippy/extras/tmc2130.py
- klippy/extras/tmc2660.py
It was possible for tmc2130/tmc2208/tmc2209 drivers to be programmed with an irun=16 or irun=17 when it was also possible to configure the driver with irun=31
and vsense=1 instead.  This would occur on tmc2130/tmc2208/tmc2209 drivers for run_current values around 0.900 to 1.000 amps (when using a typical sense_resistor settings of 0.110 Ohms).
Programming the driver with irun=16 or 17 is not ideal as it could result in reduced microstep precision.
A similar issue could impact tmc2660 drivers.
This change updates the code to improve the run_current programming to avoid the above issue.
If one was using one of the impacted run_current settings then it is possible this change may invalidate any previous sensorless homing or spreadcycle tuning.
-Kevin
> Rework tmc run_current selection to prefer vsense=1

- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/chelper/__init__.py
- klippy/chelper/kin_extruder.c
- klippy/extras/extruder_stepper.py
- klippy/kinematics/extruder.py
- test/klippy/extruders.test
This PR reworks the extruder stepper logic to make it more flexible.  In particular, it is now possible to use the SYNC_STEPPER_TO_EXTRUDER command on either an `extruder` object or an `extruder_stepper` object.  It is also now possible to call SET_PRESSURE_ADVANCE and SET_EXTRUDER_STEP_DISTANCE on `extruder_stepper` objects.
This may facilitate synchronizing of multiple extruders on idex printers (such that one can print multiple objects simultaneously).  As in #4489.
This may facilitate support for mixing extruders (as in #3920, #4082, #4566).
This PR also deprecates the `shared_heater` support in extruder config sections.  It is thought that one can now obtain the same support by using `extruder_stepper` config sections.
I do not have a good way to test this code.  Feedback and testers …
> Refactor extruder steppers and extruder_stepper

- klippy/extras/tmc.py
Found this error.
Also i tested a tmc261 chip with the tmc2660 code, it is fully compatible except for the lower current limit of 1.4A. Maybe this can be noted somewhere. The tmc261 is interesting because it supports up to 60v.
> extras/tmc.py: Fix number of arguments in phase endstop

- klippy/extras/gcode_arcs.py
The G2 / G3 command might be renamed using `gcode_macro` + `rename_existing`. This change allow detecting clockwise / anti-clockwise moves when the command gets renamed to G2.1, or anything else that uses G2 as prefix.
I chose this approach, because the documentation contains an example for renaming the M117 command, and it gets renamed to M117.1 . I've used renamed G0/G1/G2/G3 commands in the past to allow for extra debug information in the Klipper console. G0/G1/G3 work fine with this approach, but G2 breaks because of the way the clockwise detection works.
> arc_move: detect CW / CCW move with renamed G2/G3 command

- src/stm32/Kconfig
- src/stm32/stm32f1.c
Signed-off-by: Sergey Terentiev <sergey@terentiev.me>
> KCONFIG: Add remap CAN to PD0/PD1 for stm32f103

- config/printer-biqu-bx-2021.cfg
- test/configs/stm32h743.config
- test/klippy/printers.test
BIQU BX STM32H743
Add the BIQU BX printer config.
Signed-off-by: Aaron DeLyser bluwolf@gmail.com
> BIQU BX printer config

- scripts/flash_usb.py
- src/rp2040/Makefile
The rp2040 can be flashed without sudo when using udev rules to give the user permission, but in a standard configuration sudo is required.
Here we make it possible for flash_usb to use sudo for the rp2040 target, and make it the default when using `make flash` for the rp2040. As for other targets, one can set `NOSUDO=1` to not call through sudo.
When I did the `make flash` support I was using a machine with udev rules, and thus never noticed that root is required in the common case.
> flash_usb: use sudo for rp2040 flashing

- docs/Resonance_Compensation.md
I noticed that Resonance_Compensation.md was still recommending updating the printer.cfg file to set max_accel=7000.  It's simpler to make all those adjustments by issuing a `SET_VELOCITY_LIMIT` command.  This PR updates the document.
@dmbutyugin - FYI.
-Kevin
> Update Resonance_Compensation.md to recommend SET_VELOCITY_LIMIT

- klippy/extras/bme280.py
Incorrect math in bme280.py was causing issues when using Python 3. This fix should work with both python 3 and python 2.
Singed-off-by: Christopher Conroy <cbc02009@gmail.com>
> fix integer handling for python3 in bme280.py

- src/stm32/stm32h7_adc.c
module: STM32 ADC
Don't reset the ADC peripheral if the clock is already enabled.
Fixes #5236
Signed-off-by: Aaron DeLyser <bluwolf@gmail.com>
> BUG: Fix STM32H7 ADC reset

- docs/G-Codes.md
Diff may look a bit unintuitive, but previously there were two `[firmware_retraction]` sections in the G-Codes docs.
> docs: Drop duplicated firmware_retraction G-Codes section

- docs/Status_Reference.md
- klippy/extras/bed_mesh.py
This change was reduced to reporting the mesh profiles actually defined in bed_mesh.py via the status.  That way GUIs can correctly reflect the profiles that are available via BED_MESH_PROFILE commands.
> bed_mesh: Support reporting actual mesh profiles

- scripts/klippy-requirements.txt
Fixes #5284 
Markupsafe updated and the latest version no longer includes `soft_unicode`, so here I pin the transitive dependency
> Pin markupsafe < 2.1, to fix python3

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/extruder_stepper.py
- klippy/kinematics/extruder.py
- klippy/stepper.py
- test/klippy/extruders.cfg
This PR makes it possible to define an extruder config section without an extruder stepper motor.  This may be useful for dual hotend systems that share a single stepper motor.
A bit unrelated, but I'm also added a commit here that removes the default for the "extruder" parameter of `[extruder_stepper]` config sections.  With the recent extruder changes, I suspect that the default of synchronizing all extruder_stepper motors to the "extruder" motion queue is confusing.  So, after this PR, users will be required to specify the "extruder" parameter of `[extruder_stepper]` config sections (either by setting it to something like `extruder: extruder` to set the default motion queue or set it as `extruder: ` to not set a default motion queue at startup).
@drumclock - fyi.
-Kevin
> Support [extruder] sections without a stepper

- docs/Config_Changes.md
- klippy/extras/display_status.py
Following up on discussion in Discord, this PR is to ensure that an `M73` command with no `P` parameter does not set progress to 0 as it currently does.
This issue is easily reproducible in Prusa/SuperSlicer by enabling the "Firmware: Stealth mode" option together with "Firmware: Print remaining times" option:
After slicing, the g-code output will have 2 consecutive `M73` lines, but only the first line has a `P` param, and the second line will then set progress to 0.
Neither [Marlin](https://marlinfw.org/docs/gcode/M073.html) nor [RepRap](https://www.reprap.org/wiki/G-code#M73:_Set.2FGet_build_percentage) have any indication to assume `P0` if `P` is missing, so I believe this should be a safe fix to apply.
Issue was first reported here: https://github.com/fluidd-core/fluidd/issues/449 …
> display_status: stops M73 from setting progress to 0 if P missing

- src/stm32/stm32g0.c
* The USB clock source of `STM32G0B0` have not `HSI48` but only `PLLQ`, So we set the USB clock source to `PLLQ`. In this way, both `STM32G0B0` and `STM32G0B1` can use the same `firmware.bin` file
> stm32: set USB clock source to PLLQ for STM32G0B0

- docs/Config_Reference.md
The option `lift_speed` was listed in the documentation for `[probe]` but not in `[bltouch]`, so I missed it at first when searching for it.
> docs: Add missing lift_speed option to [bltouch]

- docs/Config_Reference.md
- klippy/extras/neopixel.py
Neopixel: Add BGR color order + documentation update
I discovered a problem with an other unusual color order for WS2812B 5050 SMD LED stripes. The stripe uses "BGR" color order. Color order and documentation has been updated.
Signed-off-by: Thomas Liebold electron2410@gmail.com
> Update neopixel.py to add BGR color order

- config/printer-creality-ender3-2018.cfg
Adding the bed_screws to Ender 3 by what I could measure mine.
This enables `BED_SCREWS_ADJUST`.
https://github.com/Klipper3d/klipper/blob/master/docs/Manual_Level.md#adjusting-bed-leveling-screws
Signed-off-by: Ofir Petrushka <ofir.petrushka@gmail.com>
> Adding bed_screws to Ender 3

- src/linux/i2c.c
Similarly to commit 8cf1b512 for SPI, the Rpi4 has more i2c busses to offer
This change allows klipper to use up to I2c bus 6
```
/boot/configtxt 
dtparam=i2c_arm=on
dtoverlay=i2c6
```
and 
```
pi@fluiddpi:~ $ ls -1 /dev/i2c*
/dev/i2c-1
/dev/i2c-6
```
> Update i2c.c to handle RPI 4 extra I2c busses

- config/printer-creality-ender2pro-2021.cfg
- test/klippy/printers.test
Adds a default config for ender 2 pro. See [previous pull request](https://github.com/Klipper3d/klipper/pull/5037) for additional details.
I've tested this and it works for me.
Signed-off-by: Spencer Owen <owenspencer@gmail.com>
> Adds Ender 2 Pro config

- docs/Config_Reference.md
Previously the section for stepper_bed was intertwined with printer. This commit makes it match (../config/example-polar.cfg).
Signed-off-by: Charles Pickering <me@charlespick.xyz>
> docs: Fix config snippet for polar

- docs/API_Server.md
- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Status_Reference.md
- klippy/extras/angle.py
- scripts/motan/data_logger.py
- scripts/motan/readlog.py
- src/Makefile
- src/sensor_angle.c
- src/spicmds.c
- src/spicmds.h
This PR add support for bulk querying of some popular SPI based magnetic hall angle sensors (a1333, as5047d, and tle5012b).  These sensors are typically deployed to the back of a stepper motor and they can then measure the stepper motor shaft angle (via a diametric magnet glued to the stepper motor shaft).
The focus of this code is on performing "motion analysis".  The code collects bulk angle measurements along with precise timing.  That data can then be collected and analyzed offline via the API Server using the existing "motion analysis" tools.  This support is similar to the adxl345 motion analysis support, and indeed one can simultaneously gather accelerometer and angle measurements.
I'm a little torn on merging this code into the main Klipper branch as there currently aren't that …
> Support for magnetic hall angle sensors (for motion analysis)

- docs/Config_Reference.md
module: Documentation
According to [resonance_tester.py](https://github.com/Klipper3d/klipper/blob/master/klippy/extras/resonance_tester.py#L54) the default value for max_freq is actually 133.3333... Hz and not 120 like the docs say. Updated the docs to match the code.
Signed-off-by: Christopher Conroy <cbc02009@gmail.com>
> Fix incorrect default value for max_freq in [resonance_tester] documentation

- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/extras/smart_effector.py
This PR adds support of programmable sensitivity for Smart Effector, if the effector control pin is wired to a GPIO pin,
as well as a few other features useful in combination with the custom sensitivity: probing acceleration and recovery time.
> extras: Smart Effector support

- klippy/extras/htu21d.py
This error was most probably caused by a copy/paste error. All vendor documentation for SI7021 (e.g. https://www.silabs.com/documents/public/data-sheets/Si7021-A20.pdf) points to 21 and it actually only works when adapted to 0x15 (=21).
This PR was tested in real production on a Raspberry Pico MCU.
> HTU21D - SI7021 is has id 0x15

- config/printer-creality-ender3pro-2020.cfg
Added flash info that some Ender 3 Pro's shipped in 2022 have the GD32F103 chip
> printer-creality-ender3pro-2020: Update info on chip types

- scripts/spi_flash/spi_flash.py
This patch should resolve the issues previously discussed.  Two changes are added:
1) The `spi_flash` module now validates that the MCU is configured after sending a configuration.
2) The SPI frequency is reduced to 400kHz, which is within the recommended guidelines for SD Card initialization.  While a typical sd card would increase the frequency after init, it isn't necessary for our application.
I have tested these changes on an SKR Pro v1.1 and SKR Mini E3 v1.2.   I plan to test on an SKR 1.3 and Flyboard Mini as well, however I wanted to get this PR up to give the opportunity for others to test.  In particular it would be good to make sure that the SPI frequency change doesn't negatively impact other boards, if necessary we can specify the frequency on a per-board basis. …
> spi_flash: resolve configuration issues

- config/generic-fysetc-s6-v2.cfg
- config/generic-fysetc-s6.cfg
- config/generic-fysetc-spider.cfg
My Fysetc S6 V2.1 (essentially the same as V2) needed software pull-ups to make the endstops work. After checking the schematics for S6 V1.2 and Spider, those boards need software pull-ups as well.
> config: Pull up endstop_pins on Fysetc S6/Spider

- docs/Features.md
There is concern that some users are interpreting the benchmark table in Features.md as a list of "supported boards" or possibly "recommended boards".  This was not the intent.
This is somewhat pronounced as the Features.md file is often one of the primary links new users start with when looking into Klipper.
This PR removes the board names from the list to make it more clear the intent is only to describe the benchmarks.
-Kevin
> List only micro-controller names in benchmarks table in Features.md

- klippy/klippy.py
The MCU protocol error message often confuses users, especially after getting bombarded with the config format error line. This PR tries to improve it and has the following goals:
- Put the technical error at the end to prevent confusion and avoid the immediate jump to help channels instead of continuing to read
- Inform the user first what the type of error is (In this case: MCU Protocol error) and not at the end of the long error message
- Give the users a clear instruction what to do (pretty much unchanged), but possibly more approachable because the user is not confused by the technical error anymore
- Shows the version numbers of Klipper separate from all MCU version numbers so that it is more obvious that this is the version of Klipper
- Separates the version numbers between …
> klippy: Reworked the MCU protocol error message

- docs/Installation.md
This PR reorganizes the main Installation.md document to start by recommending users obtain an example printer configuration file.
Much of the mcu configuration, flashing, and other steps are documented in the printer config file, so obtaining that file first makes the follow up steps more likely to succeed.
I also suspect that starting with a good printer config file will improve the likeliness of a successful Klipper installation.
-Kevin
> Update Installation.md to start with an example config

- docs/Config_Reference.md
The default z-hop speed is actually 15 mm/s according to the code in safe_z_home.py
> Update Config_Reference.md to correct default z-hop speed

- docs/G-Codes.md
- klippy/extras/resonance_tester.py
This PR adds `CHIP` and `POINT` arguments to `TEST_RESONANCES`. It was born out of a need to script generation of belt tension graphs for the upcoming V-Core IDEX printer, without having to edit the config between each test.
Example:
```properties
[gcode_macro GENERATE_IDEX_GRAPHS]
gcode:
{% if params.AXIS is defined %}
{% if params.AXIS|lower == 'x' %}
G28
TEST_RESONANCES AXIS=X CHIP="adxl345" OUTPUT=raw_data NAME=t0
T1
TEST_RESONANCES AXIS=X CHIP="rpi" OUTPUT=raw_data NAME=t1
G4 P5000
RUN_SHELL_COMMAND CMD=generate_tension_graphs PARAMS=x
RESPOND MSG="Belt tension graph generated for the X axis. You'll find it in the input_shaper folder in the machine tab!"
{% elif params.AXIS|lower == 'y' %}
G28
TEST_RESONANCES AXIS=Y CHIP="adxl345, rpi" OUTPUT=raw_data NAME=belt_tension …
```
> Support recording data from multiple ADXL345's in one run, and more.

- config/sample-huvud-v0_61.cfg
Pin information and basic flashing instructions for the Huvud CAN bus toolhead board. V0.61
Signed-off-by: Charles Pickering <me@charlespick.xyz>
> config: Huvud KlipperToolhead config

- klippy/extras/ds18b20.py
Unfortunately while applying https://github.com/Klipper3d/klipper/pull/5233 one change was missed, so klipper now fails to start.
> DS18B20: fix string conversion error on startup

- src/stm32/Kconfig
The CanBoot bootloader can often fit in 4KiB and that may be useful for some devices with small flash sizes.
In particular, I've found this useful on my stm32f042 device.
-Kevin
> Support 4KiB bootloader on stm32f1 and stm32f0

- config/printer-creality-ender3-s1-2021.cfg
- config/printer-creality-ender3-s1pro-2022.cfg
The display cable on my Ender 3 S1 is connected to `PA3/PA2` instead of `PA10/PA9`. Not sure if this applies to the S1 Pro as well, I guess it does but I don't want to commit anything I can't verify.
> Correct UART pins for Ender 3 S1 display cable

- docs/Config_Changes.md
- src/rp2040/usbserial.c
The rp2040 USB may not connect after a reset.  This PR implements the recommended workaround.
This is mostly @dalegaard's code from PR #4748 with some code reorganization.
This change should, hopefully, make the rp2040 USB startup a little more stable.
-Kevin
> Implement rp2040 workaround for USB errata "rp2040-e5"

- config/generic-duet3-mini.cfg
Hi.
Just add the pins for the onboard tacho reading pins.
Based on: https://github.com/Duet3D/RepRapFirmware/blob/3.3-dev/src/Duet3Mini/Pins_Duet3Mini.h
Lines 494-495. 
Tested and working.
> Update generic-duet3-mini.cfg to include Tacho pins 

- config/generic-th3d-ezboard-lite-v2.0.cfg
i don't have this board, but a user sent me a picture and also on the website this processor name is listed.
pic from Luissen#7248
[link to website](https://www.th3dstudio.com/product/ezboard-v2/)
> config: fix processor name in th3d ezboard lite v2.0 config

- src/Kconfig
- src/generic/canbus.c
- src/generic/canbus.h
- src/stm32/Kconfig
- src/stm32/Makefile
- src/stm32/can.c
- src/stm32/chipid.c
- src/stm32/fdcan.c
The existing canbus code has two mechanisms for reading messages - one for admin messages and one for data messages.  This PR changes the canbus code to use a single read mechanism.  This simplifies the low-level canbus code and should make it easier to port to new MCUs.
As part of this change, I've also extended the stm32g0 code to support canbus on PB8/PB9 pins.  I needed this to test the changes.
@bigtreetech - fyi.
-Kevin
> Rework CANbus code to use a single function for packet reading

- docs/Status_Reference.md
- klippy/configfile.py
Adds a save_config_pending_items to the status reported by
configfile reflecting the items and values that a future
SAVE_CONFIG would actually persist.
Signed-off-by: Kurt Haenen <kurt.haenen@gmail.com>
> config: Expose options awaiting to be saved

- docs/FAQ.md
The ToC at the beginning of FAQ is redundant for Mkdocs and makes FAQ harder to maintain (if you change a title you need to adjust the ToC manually.
Signed-off-by: Yifei Ding<yifeiding@protonmail.com>
> docs: remove FAQ ToC

- docs/Command_Templates.md
- docs/G-Codes.md
- klippy/extras/display_status.py
This is the alternative solution to #5527 as discussed in #5528.  The `SET_DISPLAY_TEXT` extended gcode may be used  to correctly set the message of an overridden M117 command when the message begins with a special character.
> display_status: add SET_DISPLAY_TEXT extended gcode

- klippy/klippy.py
The `logging.basicConfig` does not reconfigure default logger.
This results in printing only `warnings`/`errors` to stderr
instead of also `info` (or `debug`).
This fixes the issue by setting log level on root logger.
I use `systemd` journal logging (to memory) instead of logging to file.
Klipper would output only:
```
WARNING:root:No log file specified! Severe timing issues may result!
```
```
INFO:root:Starting Klippy...
WARNING:root:No log file specified! Severe timing issues may result!
INFO:root:Start printer at Fri Jun 24 13:20:41 2022 (1656069641.7 2579.4)
...
INFO:root:Configured MCU 'mcu' (1024 moves)
```
Signed-off-by: Kamil Trzciński <ayufan@ayufan.eu>
> klippy: properly set log level when logging to stderr

- scripts/flash_usb.py
- src/stm32/stm32g0.c
- src/stm32/stm32h7.c
As described in part `4.1 Bootloader activation` of [AN2606](https://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf) manual.  Before jumping to bootloader user must:
* Disable all peripheral clocks
* Disable used PLL
* Disable interrupts
* Clear pending interrupts
So `check_usb_dfu_bootloader();` of STM32G0 is moved behind Reset clock registers, and add Reset clock part for STM32H7 
`dfu-util: Error during download get_status` will appear after `make flash`. 
`sudo dfu-util -p 1-1.2 -R -a 0 -s 0x8020000 -D out/klipper.bin` No error message
`sudo dfu-util -p 1-1.2 -R -a 0 -s 0x8020000:leave -D out/klipper.bin` has error message, So the error  is reported in the …
> stm32: stm32g0/h7 dfu support

- config/sample-lcd.cfg
This adds an example of quite common in Anet world display (re)wiring configuration 
Tested on Anet A8 with SKR 1.4 Turbo board.
Signed-off-by: Vladimir Serov <cab404@mailbox.org>
> Added Anet alt-wiring display example

- README.md
- docs/FAQ.md
- docs/Sponsors.md
- docs/_klipper3d/mkdocs.yml
- docs/index.md
I'm planning to add a new "Sponsors" page to the documentation and to the klipper3d.org website.  There are two main goals for doing this: it gives a location to inform users of how they can donate to Klipper, and it provides a place to list prominent sponsors of Klipper.
This PR adds the page with some existing donation links for Klipper and lists some common Free Software that is often used with Klipper.
I've received interest from some hardware manufacturers interested in sponsoring Klipper.  This page is where I would look to add those sponsorships in the future.
Along with adding the page, I've added links to it from the main Klipper splash page and in the page site index.
-Kevin
> Add a new Sponsors.md file to the docs and website

- scripts/spi_flash/board_defs.py
Just a board configuration for Mellow FLY Gemini V2 to be able to flash via sd card.
> Add spi_flash board definition for Mellow FLY Gemini V2

- config/printer-creality-sermoonV1-2022.cfg
- test/klippy/printers.test
Sermoon V1 using CR-FDM-v2.4.S1.200 mother board with STM32F401.
I have literally tracked and traced each pin to the CPU to where it goes and document it.
After Z_ENDSTOP_CALIBRATE, my SermoonV1 works well.
In out of box SermoonV1, controller fan always on. There is no way to set speed or turn off the fan.
In order to access the controller fan, the controller fan needs to be plugged in PB4, see figure below.
The additional three pins can be used for filament detection and door status detector, see `PB14` `PC6` `PB15` in figure below.
> config: Integrate configuration file for Creality Sermoon V1.

- docs/Status_Reference.md
- klippy/extras/manual_probe.py
Exposes a `ManualProbe` status, that will be set by `ManualProbeHelper`.
When not running, status is:
```python
{
'is_active': False,
'z_position': None,
'z_position_lower': None,
'z_position_upper': None
}
```
When a manual probe is initiated, `ManualProbeHelper` will set `active` to `True` and the remaining values will update accordingly.
This will allow frontends like Fluidd and Mainsail to show an "assistant/wizard" type interface to help with these commands!
This PR is a follow up on this Discourse topic: https://klipper.discourse.group/t/exposing-calibration-testz-accept-abort-state/3511
> manual_probe: report status

- docs/Config_Reference.md
> docs: fixes typo on heater_bed

- docs/Status_Reference.md
- klippy/extras/bed_screws.py
Exposes the current status of `BED_SCREWS_ADJUST` under `bed_screws`:
When not running, status is:
```python
{
'is_active': False,
'state': None,
'current_screw': 0,
'accepted_screws': 0
}
```
When a `BED_SCREWS_ADJUST` command is initiated, it will set active to True and the remaining values will update accordingly.
I've decided not to expose the "calculated" screws data inside bed_screws.py as we can get that directly from the config.
This will allow frontends like Fluidd and Mainsail to show an "assistant/wizard" type interface to help with the `BED_SCREWS_ADJUST` command!
> bed_screws: report status

- config/printer-anycubic-4maxpro-2.0-2021.cfg
Hello there! I have added to klipper config for Anycubic 4 Max Pro 2.0 two internal stock systems. First one is internal beeper, and I created M300: "Play Tone" G-Code macro, according to Marlin G-Codes.
Second one, I added M81: "Power Off" G-Code macro, according to Marlin G-Codes. This command will be wait until hotend cool down, and then power off printer. Stock firmware do the same things. 
-- Signed-off-by: Usachev Alexander Valer'evich <int_0x21@protonmail.com>
> Anycubic 4 Max Pro 2.0: Added two internal systems (beeper and PSU control).

- docs/Status_Reference.md
- klippy/kinematics/delta.py
Added the possibility to get where the "cone shape" of the build volume starts from Macros
Signed-off-by: Martin Malmqvist Volcomosq@gmx.com
> Added the possibility to get where the "cone shape" of the build volume starts from Macros

- klippy/extras/palette2.py
Raised from issue #5645, UTF-8 encoded symbols or other unexpected symbols on the UART raise an exception which causes klipper to stop. This change support UTF-8 encoded characters (from file names) as well as ignoring unexpected bytes.
Signed-off-by: Clifford Roche <clifford.roche@gmail.com>
> palette2: Fix UART encoding

- src/rp2040/i2c.c
rp2040: Enables the hw pullups on the i2c pins to enable i2c communication without external pullups.
Tested on a custom rp2040 board with an i2c sensor on board and no external pullups with up to 800khz and with an external i2c sensor on a ~20cm cable with up to 400khz. Also works with external pullups to allow the external sensor to reach 1Mhz.
Signed-off-by: Adrian Joachim [adi.joachim12@gmail.com](mailto:adi.joachim12@gmail.com)
> rp2040: Enabled hw pullups for the I2C pins

- src/stm32/stm32h7_adc.c
module: stm32h7 ADC
Fix mcu temperature on SKR-3
Signed-off-by: Aaron DeLyser [bluwolf@gmail.com](mailto:bluwolf@gmail.com)
> Fix the STM32H743 mcu temp on SKR-3

- klippy/extras/save_variables.py
Prevents `Variable Saved` from being written to the console every time SAVE_VARIABLE is called.
> Do not write to console when variables are saved

- scripts/dump_mcu.py
This utility uses logic from the `DUMP` command in `console.py` to read out a section of the MCU's flash and save it to disk.  The motivation behind this was to make it a bit easier for users unfamiliar with `console.py` to backup their stock bootloader.  Usage is similar to console.py:
```
usage: dump_mcu.py [-h] [-b <baud rate>] [-c <canbus iface>]
[-i <canbus nodeid>] [-s <read start>] [-l <read length>]
<device> <outfile>
MCU Flash Dump Utility
positional arguments:
<device>              Device Serial Port
<outfile>             Path to output file
optional arguments:
-h, --help            show this help message and exit
-b <baud rate>, --baud <baud rate>
Baud Rate
-c <canbus iface>, --canbus_iface <canbus iface>
Use CAN bus interface; <device> is the chip UUID
-i <canbus nodeid>, …
```
> dump_mcu: helper script for mcu flash backup

- config/example-deltesian.cfg
- docs/Config_Reference.md
- klippy/chelper/__init__.py
- klippy/chelper/kin_deltesian.c
- klippy/kinematics/deltesian.py
- test/klippy/printers.test
Deltesian printers shares common points with both delta and cartesian printers.
The y axis is inherited from cartesian printers, bed-slingers in particular.
The x and z axis gantry is a flatten delta printer.
This addresses Leapo's feature request (issue #1440).
Original design on the creator's site: https://bornity.com
All tests and feedbacks are provided by Leapo and !cathulhu. 
Many thanks to these three active members of the deltesian community.
Signed-off-by: Fabrice GALLET tircown@gmail.com
> kinematics: Add deltesian printers

- config/generic-bigtreetech-skr-cr6-v1.0.cfg
As found on discord by user David Carey.
uart_address for y and z are swapped. Discovered while setting up sensorless homing.
Signed off by: James Hartley <james@hartleyns.com>
> Wrong uart_address assignment for Y and Z - BTT SKR CR6

- docs/Config_Reference.md
- klippy/extras/fan.py
Hi,
This adds a `power_pin` option to fans. When the fan PWM target is set to a non-zero value, the `power_pin` will be pulled high.
The intended use case is for fans with dedicated PWM inputs. Some of these don't support going to 0% (off) but stay on at some low value. To be able to turn fans like these off, the fan ground can be switched normally(via a standard fan port ground-switching FET), while the `pin` can be connected directly to the fan PWM input. Using the dedicated PWM pin is preferable to ground switched PWM as the fan controller can provide much more accurate and linear control over the fan speed.
With the rising popularity of 4028s, this I believe this will soon(if not already) be useful to >100 printers. Many of the 4028s people are using are intended as server fans, where …
> fan: add power_pin option

- src/Kconfig
- src/generic/serial_irq.c
- src/lpc176x/Kconfig
- src/lpc176x/internal.h
- src/lpc176x/main.c
- src/lpc176x/usbserial.c
- src/stm32/Kconfig
This PR adds a "side-channel" mechanism for entering the bootloader when using serial communication. This makes it easier to automate flashing scripts. USB and canbus have similar side-channel mechanisms - this PR extends the concept to UART.
The mechanism to enter the bootloader over serial is to send a special string on the serial port. For example:
`echo -e '~~~ \x1c Request Serial Bootloader!!!~~~' > /dev/ttyAMA0`
The string is specially crafted so that the Klipper message parser will not fragment it.
I have enabled this support on lpc176x and stm32 (as there is UART CanBoot support for these boards).
@Arksine - thoughts?
-Kevin
> Support requesting bootloader when using UART

- klippy/extras/virtual_sdcard.py
The existing code works perfectly under python2: the internal `open` function will open the file and allow reading of the data with unaltered line-endings (meaning that lines will be CRLF or LF ended)
But python3 has changed the behavior of the `open` function to be an alias of `io.open`. And that brings in the Universal Line Endings as default, meaning that any CRLF will be read as LF.
Context [here](https://docs.python.org/3/howto/pyporting.html):
> You should also use io.open() for opening files instead of the built-in open() function as the io module is consistent from Python 2 to 3 while the built-in open() function is not (in Python 3 it’s actually io.open()).
This changes the behavior by ensuring we read line-endings as-is (by using `io.open` and passing in `newline=''`)
From my …
> virtual_sdcard: read new lines as-is

- docs/SDCard_Updates.md
- scripts/flash-sdcard.sh
- scripts/spi_flash/board_defs.py
- scripts/spi_flash/spi_flash.py
This PR replaces #5715 (I didn't realize you had to reopen a PR on GitHub **before** force pushing updates to the branch or it won't let you reopen it).
This changes the `flash-sdcard.sh`/`spi_flash.py` scripts to allow for a split flash/verification session as required to program boards that use SDIO for their SD Cards in order to perform a manual reboot/power-cycle.
It also adds support for the BigTreeTech Octopus boards, which use SDIO.  Here's what this new SDIO procedure looks like from a user-perspective, where I reflashed my Octopus board from `ga709ba43` to `g9e4994cb` while testing these changes:
First, I ran the verify step to confirm it worked independently and verify the device matched my existing `ga709ba43` build:
```
$ ./scripts/flash-sdcard.sh -c /dev/ttyACM0 …
```
> scripts: Support SDIO in flash-sdcard using split verification step and add BTT Octopus

- klippy/extras/z_thermal_adjust.py
M105 expects a get_temp method for all sensors with a gcode_id defined. z_thermal_adjust crashes when the gcode_id parameter is set and M105 is called. 
Port get_temp and stats (for good measure?) methods from temperature_sensor.
Signed-off-by: Robert Pazdzior <robertp@norbital.com>
> z_thermal_adjust: hotfix for M105 internal error

- scripts/spi_flash/board_defs.py
As discussed with Arksine, he has created new working settings for the Creality 4.2.x boards as the original 4.2.7 entry did not work, plus addition of SKR2 and SKR3. Tested on 4.2.2 and SKR2 and SKR3EZ.
These are using the new skip_verify functionality that was recently merged due to them using SDIO
Also removed a double definition for `monster8` it was in main definitions and aliased.
> Add SKR2, SKR3 and Creality 4.2.2/7 to spi_flash

- docs/CONTRIBUTING.md
This adds a short blurb to the review guidelines to indicate that "bug fixes" should ideally identify the "root cause" of a bug and look to fix that root cause.  That is, we want to avoid "papering over bugs" and avoid "making random changes that seem to help".
-Kevin
> Add a note about fixing underlying bugs in CONTRIBUTING.md

- klippy/extras/adxl345.py
According to ADXL345/ADXL343 datasheets, at 3.3V supply voltage, which is most frequent in the various boards, the sensitivity of X and Y axes changes to 265 LSB/g from 256 LSB/g at 2.5V.
> adxl345: Apply correct scaling for X,Y and Z axes

- src/stm32/serial.c
- src/stm32/stm32f0_serial.c
- src/stm32/stm32h7_serial.c
If an USART RX overrun happened on a stm32g0/f0/h7, the ORE flag would get set by hardware. This flag would also trigger an interrupt. The problem was that this flag was never cleared on these 3 mcu families since the ORE flag clear sequence is different to all of the older chips. As a result, the MCU would get stuck in the USART ISR and trigger a watchdog reset instead of just causing a communication error that can be recovered from.
Since the ORE flag is not used in any meaningful way anyway, it was disabled during the init sequence for the STM32 G0/F0/H7.
Signed-off-by: Alex Voinea <voinea.dragos.alexandru@gmail.com>
> stm32: fix USART ORE status flag handling

- src/stm32/Kconfig
Since Klipper never uses more than about 16KiB of ram, there isn't a gain to using a different memory map on the stm32h743 chip.  Make that chip the same as stm32h750 and other stm32 chips.
@D4SK  @adelyser - fyi.
-Kevin
> Use consistent memory position/size on stm32h743

- klippy/extras/display/menu.cfg
This will hide features in the Klipper Display menu that isn't applicable for the machine, therefore we can add extra alignment tools in the Control menu as well.
Also conditionally displays Setup/Calibration options.
Signed-off-by: Nickolas Grigoriadis <nagrigoriadis@gmail.com>
> menu: Conditional display of common Control utils

- src/atsam/Kconfig
- src/atsamd/Kconfig
- src/atsamd/usbserial.c
- src/generic/armcm_reset.c
- src/lpc176x/Kconfig
- src/rp2040/Kconfig
- src/rp2040/Makefile
- src/rp2040/main.c
- src/rp2040/rp2040_link.lds.S
- src/stm32/Kconfig
This is an alternative to PR #5844 .
-Kevin
> Support CanBoot bootloader on rp2040

- src/linux/gpio.c
This replaces stale gpiod bias flags introduced in the original pull request, #2787.   According to [this comment](https://github.com/Klipper3d/klipper/pull/2787#issuecomment-623004661) the decision was made to remove the libgpiod dependency and use ioctl's directly, however the bias flags were not updated.
> linux_mcu:  use correct gpio bias flags

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/custom.md
- docs/Contact.md
The Klipper github issue tracker isn't really used for anything at this point.  The Klipper discourse tool (along with Klipper discord) seem to be much better tools in general for tracking topics.  This PR updates the Contact.md document to be a little more clear on that.
Comments?
-Kevin
> Update Contacts.md with improved github issue tracker description

- docs/Config_Changes.md
- klippy/extras/safe_z_home.py
After a G28 z-axis homing, there is a final z hop. It was hoping to height z_hop as an absolute z height rather than relative.
If the z-axis home leaves the head at a z height higher than z_hop, e.g. because you were using a probe to do z homing, this meant that it was z hopping in the negative z direction, which could result in crashing the toolhead.
Signed-off-by: Joshua Redstone <redstone@gmail.com>
> safe_z_home: Fix final z hop to use relative z coordinates

- config/printer-artillery-sidewinder-x2-2022.cfg
Minor fix. The screw labels "back left" and "back right" where swapped in [screws_tilt_adjust] section.
Signed-off-by: Frank Roth <developer@freakydu.de>
> config: printer-artillery-sidewinder-x2-2022.cfg

- src/linux/gpio.c
- src/linux/internal.h
Add the Klipper control of `GPIOI` port for BTT CB1 (H616). Theoretically, it will not have a negative impact on other SoC.
> linux process: add 'GPIOI' for linux process

- src/stm32/stm32g0.c
- src/stm32/stm32g4.c
Do not clear the DBG_SWEN bit for the MCU families that have it. This bit is by default set to 1 on reset, but the flash latency initialization code would overwrite that bit with 0, disabling the SWD interface.
The G4 can just use a simple mask for the bit, but on the G0 family it's a bit more complicated since not all MCUs have that bit present. In this particular case, the G0x1 family has this bit, but on the G0x0 family it is defined as "reserved". Unfortunately, even though it is reserved, it still might exist there and function correctly (as was the case with my board), so it might be better to follow the instructions from the datasheet in this case and keep reserved bits to the reset value.
@mattthebaker ping as requested by Kevin.
> STM32 G0 and G4 fix SWD debug

- docs/G-Codes.md
- klippy/extras/gcode_arcs.py
- test/klippy/gcode_arcs.test
add G17, G18 and G19 commands to select arc planes
enhance G2/G3 to support arc moves in XY, XZ and YZ planes
Signed-off-by: Andrew Mirsky <andrew@mirsky.net>
> gcode_arcs: support XY, XZ and YZ planes

- klippy/extras/save_variables.py
I've helped a number of people diagnose confusing `save_variable` errors because they copied the `filename` path in from a setup guide, but the copied path was actually invalid on their config. So, this just tries to create an empty file at `filename` if one is not already present. That way the user will get an error pointing to the bad path at startup, rather than a more confusing `'dict object' has no attribute` error sometime later while the printer is running.
> save_variables: Verify filename path is writeable at startup

- klippy/extras/gcode_arcs.py
- test/klippy/gcode_arcs.test
Implemented the suggested comments from @KevinOConnor and @ajmirsky in #5937 which I accidentally closed with a wrong force-push.
Signed-off-by: Wijnand Modderman-Lenstra <maze@pyth0n.org>
> Allow either one of I, J, K to be default-zero on G2/G3

- config/generic-bigtreetech-octopus.cfg
This adds information on some additional variants of the Octopus (and Octopus Pro) boards.  In particular, the crystal speeds are different on the various boards.
@bigtreetech - fyi.
-Kevin
> Update generic-bigtreetech-octopus.cfg for f429 and h723 chips

- src/stm32/stm32h7.c
I found that disabling d-cache and moving the dfu reboot flag to "axi sram" was sufficient for me to enter the bootloader on the stm32h723.  Without either of those changes, I was unable to enter the bootloader.
@bigtreetech - fyi.
-Kevin
> Rework usb_reboot_for_dfu_bootloader() so it works on stm32h723

- docs/Status_Reference.md
- klippy/extras/screws_tilt_adjust.py
_This is a resubmission of my earlier [PR #4634](https://github.com/Klipper3d/klipper/pull/4634) with additional work to fix the previously identified whitespace issues and to add the required documentation. Here's the explanation from the original PR:_
This adds a get_status() method to the screws_tilt_adjust.py module so that gcode macros and menu elements can read the results from the `screws_tilt_calculate` command. This creates a new `printer.screws_tilt_adjust` object with two properties:
`error`: False by default, but True if the `screws_tilt_calculate` command triggered the "bed level exceeds configured limits" error.
`results`: Until the `screws_tilt_calculate` command is run, this is an empty python list. But once `screws_tilt_calculate` has completed successfully, this is a …
> Add get_status() method to screws_tilt_adjust

- src/stm32/Kconfig
- src/stm32/Makefile
- src/stm32/dfu_reboot.c
- src/stm32/internal.h
- src/stm32/stm32f0.c
- src/stm32/stm32f4.c
- src/stm32/stm32g0.c
- src/stm32/stm32g4.c
- src/stm32/stm32h7.c
- src/stm32/stm32l4.c
Move the stm32 rom bootloader (DFU) entry code into a new dfu_reboot.c file.  This simplifies the chip specific code.
-Kevin
> Unify stm32 dfu reboot code

- klippy/extras/bed_mesh.py
With the advent of newer probes, meshing at 1mm may be something desired by the end user.
> Allow bedmeshing at 1mm spaced intervals.

- scripts/flash_usb.py
- src/rp2040/Makefile
Allows `make flash` to work successfully with an RP2040 running CanBoot instead of the stock bootloader.
> scripts: support CanBoot on RP2040 in `make flash`

- docs/Config_Reference.md
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc5160.py
Make all the tmc microstep lookup table registers configurable via the config file. It also loads the default values on startup if the parameters are not provided. TMC220x and TMC2660 do not support this feature (only TMC2130 and TMC5160 for now).
Without this PR these registers can't be configured at all (no fields defined, just the register address, so not even SET_TMC_FIELD works). Without this PR the default values are also not loaded, so it is possible to use an incorrect value in these registers if you switch from a firmware that uses them (eg, Prusa-Firmware for the MK3) and don't power cycle the printer.
And here is a request for this feature on the klipper forum: https://klipper.discourse.group/t/access-to-tmc-microstep-lookup-table-registers/2903?u=leptun. There are more, but …
> tmc: Configurable microstep lookup table

- docs/Config_Reference.md
Adding MPU-6515, replacing MPU-9255 duplicate
> docs: Fix typo in mpu9250 documentation

- klippy/extras/palette2.py
Issue specific to Python 3, NoneType is being used to compare heartbeat time (actually caused by invalid condition operator), and by returning NoneType in timer functions.
Resolves the issue documented here: https://klipper.discourse.group/t/palette-2-connection-giving-error/4923/9
Signed-off-by: Clifford Roche <clifford.roche@gmail.com>
> palette2: Fix errors with bad handling of NoneType in a few locations

- config/printer-creality-ender3-s1-2021.cfg
Added precise location of [bed_screws] for Ender-3-s1 config for better manual bed leveling. 
[bed_screws] locations points the tip of the nozzel above the location of the manual bed leveling scews for optimal leveling.
Signed-off-by: Stas Yakobov <stas@3os.org>
> Added precise location of [bed_screws] for Ender-3-s1 

- klippy/toolhead.py
The `note_kinematic_activity()` call had a subtle flaw that could result in the steps generated by manual_stepper not being properly flushed out (on a SYNC=0 move).  Not properly flushing out the step generation could result in "timer too close" errors.
-Kevin
> Motion queue flush fixes

- src/stm32/stm32g4.c
- src/stm32/stm32h7.c
- src/stm32/stm32h7_adc.c
- src/stm32/stm32l4.c
The stm32h7_adc.c code is used on a number of chips now - stm32g431, stm32l412, stm32h723, stm32h743, and stm32h750.  The adc code had a lot of ifdefs and slightly different behavior between chips.  Most of these differences were unnecessary.  This PR reworks the code to use less ifdefs.
I found and (hopefully) fixed a few bugs while doing this:
1. The stm32l412 should not use CKMODE=0.
2. On stm32h7 the adc actually runs at 25Mhz so the code should use BOOST=0b10.
3. The ISR clear of ADRDY should use explicit writes instead of read-modify-write.
I have also reworked the code to use explicit register writes where practical (instead of read-modify-write).
I have tested this on stm32h723.  I don't have stm32l4, stm32g4, stm32h743, nor stm32h750 chips to test.
@D4SK , @adelyser, …
> Simplify and unify stm32h7_adc code

- klippy/extras/replicape.py
The pca9685_pwm set_pwm() code can be called from a background thread (when the pin controls a heater).  Propagate updates to the main thread for enable tracking.
This should fix #369.  I don't have the replicape hardware to actually test this.
-Kevin
> replicape: Only call note_pwm_enable() in main thread

- config/printer-sunlu-t3-2022.cfg
- test/klippy/printers.test
printer-sunlu-t3-2022: Initial base config for the SUNLU T3 board
Pin outs mined from Marlin source code provided by SUNLU. In the Marlin source, the BTT SKR Mini E3 V2 is referenced. Almost all pin outs were identical to the BTT board. Changes being the use of a GigaDevice chip rather than a STM and running the TMC2209s in standalone mode rather than UART. Testing was done on my own printer for multiple prints before submitting the commit. Only submitted base config required to get the printer running, extra macros and advanced config options removed.
signed-off-by: Zachary Welvaert [zwelvaert@gmail.com]
> Added printer config for SUNLU T3

- docs/Bed_Mesh.md
- docs/Config_Changes.md
- klippy/extras/bed_mesh.py
This makes a couple minor changes to the profile behavior for `bed_mesh`:
1) Require that a profile name be specified for the `PROFILE` parameter in `BED_MESH_CALIBRATE` and all parameters in `BED_MESH_PROFILE`.  This resolves #5875.
2) Introduce an `initial_profile` option.  This allows users to specify which profile is loaded at startup, or to bypass loading a profile at startup by specifying a profile name that doesn't exist (my preference is to set this to none).
> bed_mesh: profile fixes

- config/printer-kingroon-kp3s-2020.cfg
- test/klippy/printers.test
A config that describes a Kingroon KP3S with the STM32F103 Robin Mini/Nano clone
Signed-Off-By: James Hartley <james@hartleyns.com>
> config: Add config for Kingroon KP3S

- docs/Config_Changes.md
- docs/Status_Reference.md
- klippy/extras/screws_tilt_adjust.py
Changes the format of the `printer.screws_tilt_adjust` status to a dictionary of screws with the resulting measurements.
Remaining values can easily be retrieved from active printer configuration.
This follows up on https://github.com/Klipper3d/klipper/pull/5921#issuecomment-1373749185 and replaces the PR #5974
> screws_tilt_adjust: status result as dictionary

- docs/Config_Reference.md
Config_Reference: Fixed 'screw_thread' explanation in 'screws_tilt_adjust' section.
Signed-off-by: Bassam Husain bassam.husain@gmail.com
> Config_Reference: Fixed 'screw_thread' explanation in 'screws_tilt_adjust' section.

- scripts/update_mks_robin.py
The recent PR to change this to say `#!/usr/bin/env python` instead of `#!/usr/bin/env python2` can cause issues on non rpi based OS's where `python` is not mapped to `python3`.
`#!/usr/bin/env python3` should work in both situations.
Thanks
James
> scripts: update_mks_robin.py python env version

- docs/Status_Reference.md
- klippy/kinematics/extruder.py
Adds a new `motion_queue` property to `ExtruderStepper` so we can store the current motion queue name and return on `get_status()`.
When no motion queue is set, this returns null:
This will allow frontends (Fluidd, Mainsail, ...) to show the current motion queue in sync on each extruder stepper, and for easy changes!
Follows up on [this Discourse topic](https://klipper.discourse.group/t/storing-the-current-extruder-from-sync-extruder-motion/6413)
> extruder: store currently sync'ed motion queue name

- klippy/configfile.py
The reason I needed this was for `[controller_fan]`'s `heater` option which defaults to `extruder`.
Unfortunately my machine does not have an extruder, or any heaters, causing a `Unknown heater 'extruder'` error.
Prior to this change, trying to specify an empty list of heaters causes a `Unknown heater ''` error because `getlists` returns a tuple of one empty string.
With this change I can now specify no heaters with:
`heater:`
Alternatively `controller_fan`'s default setting could be changed to handle the `extruder` heater not existing, but this seemed like a sensible change to deal with python's `''.split(',')` returning `['']`, which is silly.
> config: Make getlists return an empty list on empty string.

- docs/Status_Reference.md
- klippy/extras/stepper_enable.py
Adds status report to the `stepper_enable` module, so one can know what steppers are currently enabled and use that information in interfaces (Fluidd, Mainsail, ... ) or macros.
> stepper_enable: report status

- docs/Measuring_Resonances.md
refs https://github.com/Klipper3d/klipper/pull/6030#issuecomment-1416707228 by @Sineos
> doc: use correct mpu9250 i2c_bus on pico

- src/stm32/stm32h7.c
For example: the Octopus Max EZ bootloader has enabled SPI4
> stm32h7: Restore the RCC set in the bootloader to the default value

- docs/TMC_Drivers.md
- klippy/extras/tmc2208.py
- klippy/extras/tmc5160.py
Fixed the s2vs field formatters. So instead of the misleading `LowSideShort_A`, it's now `ShortToSupply_A` (and the same for the B coil). Also implemented this field formatter for TMC5160 since it was missing there.
Based on PR #6074.
> tmc: Fix s2vs field formatters

- docs/Config_Changes.md
- docs/G-Codes.md
- klippy/extras/tmc5160.py
Previously, the globalscaler was calculated during the config parsing and set to a fixed value. If the current was changed for any reason after the initialization, only IRUN and IHOLD would be changed. This however caused issues:
- If the new current was lower, then the resolution of the possible current values would be low since there are only 32 IRUN/IHOLD steps.
- If the new current was higher, it wouldn't actually work since IRUN and IHOLD are capped at 31, so it wouldn't be possible to increase the current without increasing globalscaler.
With this PR, the globalscaler is recalculated whenever necessary in order to ensure the correct range of IRUN/IHOLD is used.
Based on PR https://github.com/Klipper3d/klipper/pull/6074.
> tmc5160: allow changing the globalscaler at runtime

- config/printer-elegoo-neptune3-pro-2023.cfg
- test/klippy/printers.test
This is a config for the Neptune 3 Pro from Elegoo. I've kept the settings fairly conservative, based on mostly on `M503` output from the stock config and the references linked.
> Config for Neptune 3 Pro

- docs/G-Codes.md
- klippy/extras/probe.py
This adds the ability to override `horizontal_move_z` in gcode commands using the `ProbePointsHelper` utility. This includes Z tilt, QGL, Bed mesh, Bed tilt, Screws tilt adjust, and Delta calibration.
These currently always use a static `horizontal_move_z`. This patch allows overriding this per-call with a `MOVE_Z` gcode parameter. The configured value is always used unless `MOVE_Z` is given for a specific command(the value does not "stick around").
The main use case is the ability to perform a "two stage" QGL or Z tilt adjust. One can (e.g. from a macro) perform a high-z-move high-tolerance run first(to guard against a heavily misaligned bed), and then a low-move, low-tolerance run after. This can significantly speed up the process, especially when using a probe like Beacon.
Best …
> probe: allow overriding horizontal_move_z on gcode

- src/linux/gpio.h
- src/linux/i2c.c
Reading an I2C device from the Linux MCU process used a separate write(2) to select the target register & read(2) to get the content(s). This implementation uses ioctl(file, I2C_RDWR, ...) to skip a large bus idle period between the write() and read()
and an extra switch by combining them.
I2C_RDRW requires the I2C_FUNC_I2C feature flag in the I2C driver. I2C_FUNC_I2C is defined in:
BCM2835: Pi 1 Models A, A+, B, B+, the Raspberry Pi Zero, the
Raspberry Pi Zero W, and the Raspberry Pi Compute Module 1
BCM2836: Pi 2 Model B
Identical to BCM2835 except Cortex
BCM2837: Pi 3 Model B, later models of the Raspberry Pi 2 Model B,
and the Raspberry Pi Compute Module 3
BCM2837B0: Pi 3 Models A+, B+, and the Raspberry Pi Compute Module 3+ BCM2711: Pi 4 Model B, the Raspberry Pi 400, and the …
> linux/i2c: Fast(er) Linux MCU i2c_read() with I2C_RDRW

- config/printer-creality-ender3-v2-neo-2022.cfg
- test/klippy/printers.test
- Added Ender 3 v2 Neo config
Tested working with correct PINs, CR-Touch, Part Cooling, Bed levelling screws and buzzer.
Works with both SMT32 and D32F303 based 4.2.2 boards.
---
Reference schematics: [Creality.4.2.2.-.Schematic.28-5-22.pdf](https://github.com/Klipper3d/klipper/files/10929056/Creality.4.2.2.-.Schematic.28-5-22.pdf)
> config: Example config file for Creality Ender 3 v2 Neo

- docs/Status_Reference.md
- klippy/extras/probe.py
Adds the probe name to the probe status object.
I know one can infer this from the config file (check for "bltouch", "smart_effector" or "probe" sections), but seems to me easier to just expose it here.
> probe: expose name on status report

- docs/Bed_Mesh.md
In the docs, it said "If this profile exists it is automatically loaded when Klipper starts.". This was reffering to the "default" profile.
This is not true anymore as it was changed in #5877 (and mentioned in #5983).
> docs: Remove comment about default profile loading

- klippy/extras/tmc2240.py
- klippy/extras/tmc5160.py
`multistep_filt` was not configured at all on tmc2240 and tmc5160. As such, it would default to the value of 0 when the GCONF field was sent to the driver. However, that field has a default value of 1 in the driver, so klipper was overriding the defaults by accident. This field improves the stability of velocity based thresholds (it's effectively TSTEP filtering) and it also improves the current regulation stability in stealthchop2 (according to the datasheet). This field was already set to 1 correctly in the tmc2208/tmc2209 driver code.
It should not cause any breaking change. It should just improve StealthChop2 operation.
> tmc: Enable `multistep_filt` for drivers that support it

- klippy/extras/tmc.py
If tcoolthrs is configured (not the default 0), then do not force the value of tcoolthrs=0xfffff during homing. This way, tcoolthrs can be set to a custom value during homing.
`tpwmthrs` and `en_pwm_mode`/`en_spreadcycle` are now also correctly restored if they were changed after startup.
Without this change, it is not possible to use a value different than tcoolthrs=0xfffff during homing, which makes tmc homing less reliable than it can be. After this change, a delayed_gcode can be used at startup to set tcoolthrs to a specific velocity (eg 15mm/s) and make homing more reliable. Once I have finalized my homing macros, I'll make them available as well.
> tmc: Do not override tcoolthrs if it is configured

- docs/G-Codes.md
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2209.py
- klippy/extras/tmc2240.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
- klippy/extras/tmc_uart.py
This PR introduces the argument `VELOCITY` for `SET_TMC_FIELD`. It can be used instead of `VALUE` so that the velocity is automatically converted to the TSTEP based value of that velocity.
The aim of this change is to allow macros to change fields such as `TPWMTHRS`, `TCOOLTHRS` and `THIGH` at runtime without needing to hardcode values which might differ based on microstepping resolution and steps/mm of the axis.
To implement this change, I ported the TSTEP helper from my other PR (#6074).
Tested on TMC2240 on another branch of mine. TMC2660 needs to be tested since it's the odd one out.
> tmc: SET_TMC_FIELD set VELOCITY

- config/generic-fysetc-cheetah-v2.0.cfg
- test/klippy/printers.test
This adds support for the Cheetah v2.0 mainboard from Fysetc.
> config: Add Fysetc Cheetah V2.0

- docs/Config_Reference.md
- src/avr/i2c.c
Allows Klipper to set the I2C bus speed. Previously the bus was fixed to 100kHz regardless of configured parameters. Tested at 100kHz and 400kHz.
Signed-off-by: Matthew Swabey [matthew@swabey.org](mailto:matthew@swabey.org)
> avr/i2c: Allow I2C bus speed to be set by Klipper

- config/printer-anycubic-vyper-2021.cfg
Having the controller fan FAN1 on PA14 in the config is important for the stepper drivers not to overheat and skip steps.
After experiencing layer-shifts on the y-axis and some troubleshooting, i recognized that the controller fan would never spin.
Reasearch showed that FAN1 is controlled by PA14 and could be simply triggered when ever a stepper is active.
There seem to be even [mcu-temperature-controlled](https://forum.drucktipps3d.de/forum/thread/15171-vyper-klipper-mcu-mainboard-l%C3%BCfter-ansteuern/) configuration-options with klipper, but the simple two lines should prevent others from trouble and failed prints.
Signed-off-by: Robert Lilienthal <13837429+RobLil@users.noreply.github.com>
> config: printer-anycubic-vyper-2021.cfg added controller fan FAN1 on PA14 to the config

- scripts/install-ubuntu-22.04.sh
The python-dev package is not available on 22.04 Jammy, specifies the python3-dev package and python3 when creating a new virtualenv.
Signed-off-by: Jess Sullivan [jess@sulliwood.org](mailto:jess@sulliwood.org)
> scripts: add install script for Ubuntu 22.04 LTS 

- src/linux/main.c
Realtime programming best practice is to lock realtime code memory to prevent paging which will lead to unbounded latencies. The Linux MCU process has well bounded memory and small RAM footprint (or it would not run on real MCUs) so locking the entire process' RAM has no downsides and will improve behavior when the system comes under memory pressure. (See bootlin training and Linux Foundation documentation linked below.) RT process priority ranges from 0-99 (although POSIX only requires 32), boost MCU process priority to half the max/2 to improve robustness when the system comes under pressure from other RT Kernel or user processes.
I have run the Linux MCU with this patch while stress testing MPU I2C for over a week including 23+ hr I2C MPU reads from the RPi and it is very well behaved …
> src/linux/main: Lock Memory and Increase Priority

- config/printer-ratrig-v-minion-2021.cfg
- test/klippy/printers.test
This adds support for the stock configuration of the V-Minion printer from Ratrig, based on the Octopus v1.1 (STM32F446)
> config: Add Ratrig V-Minion

- docs/G-Codes.md
- klippy/extras/tmc.py
Add an optional REGISTER parameter to DUMP_TMC so that the output is more filtered/cleaner for manual TMC calibration.
This is a follow-up of #6136.
> tmc: DUMP_TMC optional REGISTER parameter

- docs/Measuring_Resonances.md
This PR updates the documentation on I2C Accelerometers to:
1. Document AVR support for MPU in general and add the ATmega328P Arduino Nano (I added AVR I2C *fast-mode* support in PR #6111)
2. Improve the technical information on connecting and wiring up the MPU accelerometers with I2C
3. Highlight some electrical requirements with the suggested I2C examples
4. Added example config file snippets for dual MPU on one I2C bus and AVR
5. [Added a few minor cleanups on spacing and English]
Ref PR #6115 , these docs have been split out from that oversized PR. 
Signed-off-by: Matthew Swabey [matthew@swabey.org](mailto:matthew@swabey.org)
> docs/Measuring_Resonances: Improved information on I2C accelerometers and AVR support

- scripts/flash-linux.sh
- src/linux/Makefile
flash-linux, linux/Makefile: fix flash when OUT argument provided
Configure for mcu with "Micro-controller Architecture (Linux process)"
Make failes when using "make flash" with "OUT=" argument provided.
Example:
make flash KCONFIG_CONFIG=klipper_mcu.cfg OUT=out_mcu/
Pathing through scripts OUT argument fixed it.
Signed-off-by: Ilya Vislotsky <write2ilya@gmail.com>
> Fix flash linux when OUT argument provided

- config/generic-bigtreetech-skr-3.cfg
As found on the discord by user Qtin, this board now ships with one of STM32H743 or STM32H723 Example config updated to reflect this. This has been tested on the users board. To note, the H743 bin will flash to the H723 chip, but will not work.
Thanks
James
signed-off-by: James Hartley <james@hartleyns.com>
> Config: SKR3, update for second chip choice

- klippy/extras/aht10.py
- klippy/extras/temperature_sensors.cfg
Added support for AHT10 ambient temperature sensor. Confirmed to work on BTT GTR 1.0 MCU, i2c port `i2c3`. 
Followed general implementation of other temperature sensors, being sure the sensor is not in busy state before reporting temperature/humidity.
Note, the AHT10 should come pre-calibrated and has limited I2C commands, so the interface is fairly simple. No RH/temp compensation is noted in the datasheet. 
If I can get ahold of AHT15/AHT20, I will add support for these as well. They should all be pretty similar, only needing to substitute some command bytes.
In order for the RH to be reported in Fluidd/Mainsail, it will need to also be added to their 'compatible' device list for RH reporting. Manually adding it to the compiled Fluidd js shows it works fine, however.
---
Squashed and …
> Added AHT10 I2C temperature sensor support

- docs/Config_Changes.md
- klippy/chelper/serialqueue.c
The `stalled_bytes` counter in the log refers to the number of bytes that are not yet eligible for transmission.  However, the naming leads to confusion as it could be interpretted as an inability to transmit data.  Rename to `upcoming_bytes` to try to avoid that confusion.
It's possible that some frontends may be impacted by this change (as the stat is also available over the api server).
-Kevin
EDIT: After further feedback, I'm now proposing the name `upcoming_bytes` instead of `unready_bytes`.
> Rename stalled_bytes stat to upcoming_bytes

- docs/Status_Reference.md
- klippy/extras/tmc.py
This is a proposal to report the tmc2240 driver temperature in a new "temperature" field in the "tmc2240 stepper_x" status.
The temperature reporting in the tmc2240 is a nice feature - it would be nice to be able to see this temperature on the common Klipper frontends.  So, in some sense it might be better to export this information using an existing "temperature_sensor" report.  However, the tmc drivers are a bit unique in that the information is only queried when the driver is "enabled".  (When the driver is not enabled, Klipper wont query the information because it is common for users to disable motor power, which disables communication with the driver.)  Exporting the information in the "tmc" status section makes this easier, but it would require front-end changes to display the …
> Export tmc2240 driver temperature

- docs/Config_Reference.md
- klippy/extras/tmc5160.py
In some condition ，“drvstrength 2” does not work. According to page 17, some mosfets need “drvstrength” set to 0 .
signed-off-by:  Albert Lin   <vcore85@gmail.com>
> tmc5160: add  DRV_CONF Register for TMC5160

- config/printer-anycubic-kobra-go-2022.cfg
- test/klippy/printers.test
This adds support for the Anycubic Kobra Go, based on the Huada HC32f460KCT6 microcontroller.
The configuration is mostly based on the [official Marlin firmware](https://github.com/ANYCUBIC-3D/Kobra_Go). 
You can find more information about this printer on [KobraGoNeoInsights](https://1coderookie.github.io/KobraGoNeoInsights/).
I posted this confi originally on this Reddit post [Install Klipper on Kobra Go or Neo](https://www.reddit.com/r/anycubic/comments/10cwm16/install_klipper_on_kobra_go_or_neo/).
There is a variant of this printer. It is Kobra Neo. They share the same mainboard model, so many of their configs are the same. But I only have Kobra Go home and it looks like the variant of a printer is treated in Klipprer for a new .cfg file. That's why this config is only labeled for …
> Add printer configuration for Anycubic Kobra Go

- src/stm32/Kconfig
- src/stm32/stm32f0_serial.c
- src/stm32/stm32g0.c
Hello!
I'm using an SKR mini E3 V3 board and I needed to access the USART5 pins which are on PD2, PD3.
Thought it would be as simple as extending that configuration in Kconfig with my combination of pins, but that didn't work.
Many headaches later, turns out that the bits to enable/reset USART5 & 6 do not follow the rule from `stm32g0.c` regarding the offset from APBPERIPH_BASE, but needed to be added as exceptions similar to the USB and others.
While I've fixed the RCC bits for USART6 as well, I was only able to test the configuration I needed, USART5 on PD2, PD3. That's why I only included this in the Kconfig.
Hoping this saves other people some time.
> Support for USART5 on STM32G0B1

- klippy/extras/gcode_macro.py
- klippy/webhooks.py
Json encoding errors currently force a shutdown with no context as to why. This can be verified by adding the following to a config, which triggers a silent TypeError:
```
[gcode_macro crasher]
variable_crash: {(1, 1): 1}
gcode:
```
This change just logs the error (including a console message) so it's easier to diagnose what went wrong. In the case of the above error, the message is:
```
json encoding error: keys must be str, int, float, bool or None, not tuple
```
_**Edit:** Also added code to prevent setting bad variables inside `gcode_macro.py`._
> Improve json encoding error handling

- klippy/extras/mpu9250.py
- src/sensor_mpu9250.c
Fixes common MPU-9250 accelerometer issues for RPi Linux MCU and improves reliability on all other architectures by adjusting the MPU-* reading algorithm to only read whole Klipper messages' worth of data from MPU-* and eliminating many unnecessary checks of the MPU FIFO fill-level that consumed bus bandwidth needed for data transfer. Improves intermittent "Lost communication with MCU 'rpi'" due to "Timer too close" and transposed / corrupted data due to FIFO overrun/data loss when using MPU-* accelerometers.
Minor: FIFO overrun checks are performed by testing the MPU interrupt flag vs. inferring from the FIFO fill level which can be unreliable, especially as different MPU chips have different FIFO sizes.
Stress tested for 13hrs with two MPU-6500 attached to one I2C bus on RPi
and one on …
> sensor_mpu9250: Improve reliability of MPU9250 accelerometers

- docs/Measuring_Resonances.md
Apologies for the mistake, it looked ok on GitHub but broken on mkdocs site.
Signed-off-by: Matthew Swabey matthew@swabey.org
> docs/Measuring_Resonances: Fix nested list, add nbsp to Raspberry Pi

- docs/Config_Reference.md
- klippy/extras/aht10.py
The control bytes for the AHT20 and AHT21 are identical to the AHT10, but I had not been able to test just yet to ensure the sensor code supported the other sensors. I've wrapped up testing and updated the comments/docs to reflect this additional support.
> aht10: update comments and docs for AHT20/AHT21 support

- src/generic/canserial.c
- src/generic/canserial.h
- src/generic/usb_canbus.c
The existing Klipper code repeatedly tries to drain the incoming canbus rx queue.  This can lead to higher task processing time and can lead to non-optimal USB bandwidth utilization when there are a large number of messages to be transmitted over the canbus.
This PR alters the prioritization - both to simplify the code and to improve handling in the tx case.
-Kevin
> Tweak prioritization in USB to canbus bridge mode

- klippy/klippy.py
- klippy/util.py
- scripts/make_version.py
Check for untracked files in the klippy/extras/ and klippy/kinematics/ directories and report those files in the log.  This helps identify code modifications when inspecting a log.
This does mean that users that have modified the Klipper code by manually adding an "extras" module will see a code version that reports "dirty".
Klipper does not have a "plugin" system.  The "extras" module system is an internal abstraction intended to facilitate long-term code maintenance.  Code in an "extras" module can easily alter the behavior of Klipper, including changing the behavior of other Klipper modules.  Thus introducing an "extras" module is a modification of the Klipper code.
-Kevin
> Report repo version as "dirty" if there are untracked python files

- config/printer-anycubic-kobra-go-2022.cfg
Also fixed the bed_mesh out-of-physical range issue.
The value is now tested on the original Kobra Go without any modification.
The previous [pr](https://github.com/Klipper3d/klipper/pull/6166)
> Change the position_max value of Kobra Go to the maximum allowed travel on the axis

- docs/Status_Reference.md
The Status Reference documentation is missing a section for gcode_button.
This PR just adds that section.
> Add gcode_button to the Status Reference docs

- klippy/extras/bme280.py
This PR supersedes #6221, fixing the BME680 issue by reporting every .8 seconds.  As before I have tested this change against a BME280, however it would be useful if someone would like to make sure the BME680 works as intended.
> bme280: use consistent report time for BME680

- config/printer-creality-ender3-v2-neo-2022.cfg
The header documentation currently shows the year the Creality Ender 3 V2 Neo as being the 2020 model. This is likely a copy/paste error from the header of the original Creality Ender 3 V2 config. The year the Creality Ender 3 V2 Neo came out was in 2022 as indicated by the name of this config file. This patch fixes the copy/paste typo by updating the year in the header documentation from 2020 to 2022.
> config: Correct year in documentation for ender 3 v2 neo

- src/hc32f460/Kconfig
- src/hc32f460/serial.c
Kconfig: adding serial port selection, 'choice' for flash app address and clock speed.
Signed-off-by: Steven Gotthardt <gotthardt@gmail.com>
> Kconfig: update for HC32F460 - clock, flash add, serial

- src/atsamd/adc.c
- src/atsamd/fdcan.c
The `O2` build flag was leading to broken CAN Tx code for the atsamc21.
> atsamd: Fix compiler optimization and ADC bugs

- config/printer-creality-ender3-s1-2021.cfg
- config/printer-creality-ender3-s1plus-2022.cfg
This PR is to remove `move_to_previous: true` from the Ender 3 S1 and S1 plus configs. This is a confusing option, it is not really useful on these type of printers and can cause issue to the end user
Thanks
James
Signed_off_by: James Hartley <james@hartleyns.com>
> Config: remove move_to_previous from Ender 3 S1 configs

- docs/Bed_Mesh.md
- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/bed_mesh.py
The current implementation of the `relative_reference_index` feature was initially added when the mesh configuration was static and could not be changed during runtime.  When runtime parameters were introduced it was also possible to change the `relative_reference_index` to accommodate a new mesh, however this puts restrictive requirements on where the new mesh is located as the new index must reference a coordinate near the original index.
With the forthcoming addition of "adaptive" mesh leveling it is necessary to rework how the reference coordinate is handled.  This pull request makes the following changes:
- The original points are no longer cached.  Points are generated each time `BED_MESH_CALIRBATE` is run to guarantee that
all attributes that depend on point generation are set.
- …
> bed_mesh: improve relative reference implementation

- src/hc32f460/main.c
- src/hc32f460/serial.c
I've tested every available UART pin config for the HC32F460 and can confirm they all work now. (HC32F460 devboard + `console.py`; and PH2/PB10 on my Anycubic Kobra via the LCD connector)
cc @SteveGotthardt
> hc32f460: Fix UART for pins PH2/PB10 and PA13/PA14

- klippy/extras/virtual_sdcard.py
This is a fix to a minor bug which results in the `get_status()` reporting floating point values for `file_position` and `file_size` after a reset or cancel.   Some API clients expect the values in these fields to be integers, as reported in arksine/moonraker#673.
> virtual_sdcard: reset file position and size to integer zero

- docs/Config_Reference.md
The reference to my_nozzle_fan is misleading and could cause people to skip over the [fan] definition and assume this is the parts/print cooling fan. Alias changed to reflect heatbreak_cooling_fan as used in most configs that have a controllable hotend fan.
Thanks
James
> Update Config_Reference.md - heater_fan wording

- config/generic-fysetc-f6.cfg
- config/generic-fysetc-s6-v2.cfg
- config/generic-fysetc-s6.cfg
- config/generic-fysetc-spider.cfg
- config/printer-tevo-flash-2018.cfg
The reference to `my_nozzle_fan` in these configs could be confusing and misleading, leading users to think it is the parts/print cooling fan, changed to heatbreak_cooling_fan as used in other configs.
Thanks
James
> Multiple config - change wording for heater fan

- scripts/spi_flash/board_defs.py
spi_flash: New flash-sdcard board definition for BTT SKRat V1.0
Adds the new BTT SKRat V1.0 controller board to the board_defs for the flash-sdcard.sh tool. The new board definition was tested by me without any errors.
>  New flash-sdcard Board Definition for BTT SKRat V1.0

- src/atsamd/Kconfig
Adds a menu entry in menuconfig, allowing you to select the SAMD21J18 as mcu.
> atsamd: Add support for SAMD21J18 (Minitronics v2)

- config/printer-creality-ender3-s1-2021.cfg
Existing `mesh_min` values start probing too far away from the edge.
Additionally `mesh_max` Y value of 197 is out of bed movement range (197 + `bltouch.y_offset` = 237.5) and causes Y stepper to overhit, which can potentially damage the printer in the long run.
Signed-off-by: Aleksandr Ivanov <aux@hexmode.org>
> Updated bed mesh configuration for Creality Ender 3 S1 and S1 Pro

- config/generic-bigtreetech-octopus-max-ez.cfg
It has been discovered on the discord by the user Pizn that the bltouch pins are swapped in this config and don't include the ^ pull on the sensor pin.
This has been tested and confirmed by the user.
Thanks
James
> Config: Update Octopus Max EZ for wrong bltouch pins

- lib/README
- lib/samc21/samc21.patch
- lib/samc21/samc21/include/instance/can0.h
- lib/samc21/samc21/include/instance/can1.h
Upstream header bug leads to clobbering of RXF0C and TXBC registers, causing severe memory corruption.
fdcan.c (and any other name applied to a Bosch M_CAN driver) on all targets should probably be modified to prevent such behaviour in future, but this will get SAM C21 up and running.
> samc21: Fix CAN RAM base address

- scripts/motan/analyzers.py
These two analyzers are useful, in my opinion, for various analyses of the motion data, e.g. as
- `["norm2(derivative(stepq(stepper_x)),derivative(stepq(stepper_y)))"]` to find the commanded toolhead velocity in XY plane from its X and Y steppers velocities;
- `["smooth(adxl345(hotend,x))","smooth(adxl345(bed,y))"]` to plot the smoothed accelerometer readings to eliminate high-frequency noise from the data.
> motan: Added norm2 and smooth analyzers

- scripts/logextract.py
This is an alternative to PR #6248.
- Open log files in text mode,
- Normalize the encoding of tmcuart messages: logs from klippy on python3 contains `tmcuart_send oid=0 write=b'\xea[...]`.  With python2, there is no `b''` string marker. The regular expression removes the marker if present. Then, a `b` is prepended to the literal-encoded string before parsing it with `ast.literal_eval`. This ensures interpretation as a byte-string on Python3, independently of the source of the log. It has no effect when running `logextract.py` on Python 2.
- Fix a [bug](https://github.com/Klipper3d/klipper/pull/6248#issuecomment-1587135735) where StatsStream.get_lines() would return None timestamps for lines before the first Stats line. Timestamps are now back-propagated.
I compared the outputs with `cat …
> scripts: logextract.py Python 3 compatibility

- lib/rp2040_flash/main.c
image->num_blocks is of type unsigned size_t thus unsigned int.
%lu specifies a type of long unsigned int. Thus resulting in compiler warning about type mismatch. Correct this by printing the value with a correct type.
> rp2040_flash: main.c: Fix the type when printing num_blocks

- klippy/webhooks.py
Adding these three pieces of information to the info endpoint allows the system that connects to the klippy.sock to simply ask klipper these details. This avoids having to resort to less accurate methods. 
For example moonraker is checking the process that generated the socket itself. This works for the most time. However when using a socket proxy this fails.
> Add process id, user id and group id to the info endpoint.

- docs/Axis_Twist_Compensation.md
- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Overview.md
- docs/_klipper3d/mkdocs.yml
- klippy/extras/axis_twist_compensation.py
- klippy/extras/probe.py
Hi,
This is a fork of the PR #6048. This is a feature I'd very like to see merged, so I took the liberty of taking the commits of @koonweee and fixing the comments made on his PR.
I can squash my commits if you prefer a cleaner history.
The changes include:
- A few bug fixes
- Some typos pointed out in the review
- Removal of the profile system, the rationale is that the twist only depends on the printer, not the temperature etc
- Rename of the module to axis_twist_compensation so that if we need some day to calibrate for another axis, there will be less changes to make to the user's configuration
On another note, I kept the recommended z offset feature from the original PR, which is also present in the Marlin implementation. This z offset has always been off in my tests. I also don't …
> Add X twist compensation module

- docs/Status_Reference.md
- klippy/extras/heaters.py
- klippy/extras/tmc.py
(This is a follow up on #6145 and discussion on PR #6205 and #6210)
This PR adds a new `available_monitors` entry to the `heaters` status object.
This allows the `TMC2240` to register itself as a temperature monitor so that Moonraker can then read the temperature and store the history data and provide it to the frontends.
> heaters: adds temperature monitors

- docs/Config_Changes.md
- scripts/spi_flash/board_defs.py
BigTreeTech is shipping the SKR-3 Controller Board now with the STM32H723 micro in addition to the existing STM32H743 version.
This adds the H723 target to the spi-flash script and renames the existing H743 variant to be consistent with other entries and disambiguate between the two.
> scripts: Support both H743 and H723 BTT SKR3 boards sdflash

- klippy/kinematics/cartesian.py
With the recent improvements to the dual_carriage support this was missed in the cartesian kinematics (where the y-axis can also be used for the dual_carriage).
@dmbutyugin
> cartesian.py: fix x-axis being hardcoded for dual_carriage

- scripts/flash_usb.py
Verified with an Monoprice Mini Select v2 using katapult.
> scripts: Added stm32f070 to mcus supported by flash_usb.py

- config/printer-creality-cr10s-pro-v2-2020.cfg
- config/printer-creality-cr10s-pro-v2.cfg
- test/klippy/printers.test
Created a base config for the Creality CR10s Pro v2 as described here: https://www.creality.com/products/cr-10s-pro-v2-3d-printer
This will allow users with this printer to more easily setup Klipper firmware.
> Add config for printer Creality CR10s Pro V2

- config/sample-duet3-1lc.cfg
- docs/Bootloaders.md
This adds an example config and a flashing script for the Duet3D Toolboard 1LC. 
@eamaclean please have a look at this when you get a chance, would like your thoughts.
> config: Add 1LC example configuration and accompanying flashing script

- scripts/spi_flash/board_defs.py
SDCard updates
Added alias for Octopus pro h723 v1.1 for sdcard update script.
Signed-off-by: David Bucek [bucek.david@gmail.com](mailto:bucek.david@gmail.com)
> SDCard updates: added alias for BTT Octopus pro h723 v1.1 

- docs/Config_Reference.md
- klippy/extras/tmc2240.py
Adding UART communication option for tmc2240 driver chips, which support both spi and uart. To achieve this a new config field has been added `interface` with the options `spi` (default/fallback) and `uart`.
The code is tested by atleast 3 users on a new upcoming board, which uses UART on the 2240 drivers to save mcu pins.
Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>
> tmc: Adding UART interface support to tmc2240

- klippy/extras/spi_temperature.py
Limit the maximum temperature in MAX31865.calc_adc() to the melting point of platinum. Above this temperature the Callendar-Van Dusen formula does not make sense. The default value for max_temp is 9999999.9 and at this temperature the result of this formula is negative. This sets max_sample_value to 0 which causes the mcu to shutdown.
Discourse topic: https://klipper.discourse.group/t/max31865-min-value-and-max-value-not-set/10029
> Limit maximum temperature in MAX31865.calc_adc() to melting point of platinum

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/kinematics/idex_modes.py
Previous version of the code assumed that dual carriages home away from each other. However, some users built a bit unusual setups where both carriages home in the same direction (one of them homes over the other one). This PR fixes kinematic ranges calculation for these setups.
Also, the PR fixes the homing order of the carriage on some setups. Basically, when the carriages home away from each other, the relative order of homing does not matter, so the carriage_0 is homed first, and carriage_1 afterwards. However, when the carriages home towards the same side, it is important to home the outermost carriage first. In some configurations that happens to be carriage_1, which is now correctly identified too and homed first.
The PR was tested by an owner of such hardware who confirmed that …
> idex_modes: Fixed the case when carriages home in the same direction

- src/stm32/usbfs.c
This adds support for "fast buffer switching" on the USB peripheral of stm32f1, stm32g0, and stm32f0 devices.
This feature can improve the USB transfer rates on these devices.  It's unlikely to be noticed on traditional emulated serial over USB setups, but it can have a notable impact when using USB to CANBUS bridge configurations.
When the micro-controller is configured to behave as a canbus adapter, the gs_usb linux kernel protocol requires many small USB packets to be transferred.  Optimizing the USB buffer handling can notably improve overall transfer rates.  In particular, I've found that, prior to these changes, the USB to CANBUS bridge setup was bottlenecked by USB transfers on some machines (such as the rpi3) - thus preventing those setups from utilizing the full bandwidth of …
> USB "fast buffer switching" on stm32 usbfs devices

- src/generic/usb_canbus.c
The current Klipper USB to CANbus bridge code will stop reading messages from the USB bus if it becomes busy sending messages on the USB bus.  This was implemented as a flow control system to prevent bandwidth generated from host messages swamping message traffic received from the physical canbus.
Unfortunately, this flow control system has a notable performance impact.  The low-level USB hardware layer will keep sending messages until the device acknowledges them.  So, if the CANbus bridge code does not read USB messages, the retransmits continue to consume bandwidth - bandwidth that would be better utilized in sending messages from the device to the host.
This PR adds a small USB message queue to the USB to CANbus bridge code.  The Linux gs_usb driver will only send 10 pending packets …
> Add a USB message queue to USB to CANbus bridge code

- config/printer-creality-ender5-2019.cfg
Recently tested on my ender 5 pro that came from creality with a v1.1.5 board. Works.
> Update printer-creality-ender5-2019.cfg to add instructions for silent boards

- src/atsam/Kconfig
- src/atsam/Makefile
- src/atsam/chipid.c
- src/atsam/fdcan.c
- src/atsam/main.c
- src/atsam/same70_sysinit.c
Add CAN to same70. Thanks to @eamaclean for the help.
Depends on [#6365](https://github.com/Klipper3d/klipper/pull/6365).
> same70: Add CAN

- docs/Bootloader_Entry.md
You always notice them after it's up there...
> docs: Fix a typo in serial bootloader entry docs

- docs/Config_checks.md
In the "Verify endstops" section there is an example of adding an exclamation point to the pin definition to invert its logic.  I believe the intention in the example is to keep the hardware pull-up ^ and follow it with ! to invert the pin logic, but the ! is missing.
> docs: In Configuration Checks doc, missing ! in pin inversion example in Verify endstops

- klippy/extras/input_shaper.py
- klippy/kinematics/extruder.py
- klippy/toolhead.py
Makes the API between toolhead and extruder, input shaper more robust, avoiding the need to track the old delay.
> Toolhead: Use dict for step generation flush times.

- klippy/extras/bed_screws.py
This is a follow up on [this issue](https://github.com/mainsail-crew/mainsail/issues/1624).
If the `stepper_x.position_max` or `stepper_y.position_max` values are smaller than those in the `bed_screws` entries, when one starts the `BED_SCREWS_ADJUST` tool, it will throw a "Move out of range" error, but the tool will be stuck in a running state, yet nothing works until we restart Klipper.
The fix here is to reset the state of the tool in case of error.
> bed_screws: Reset on move error

- config/printer-sovol-sv06-plus-2023.cfg
In testing with a user on Discord we discovered the sensorless homing thresholds were out of line with what Sovol ships with Marlin. Updated printer-sovol-sv06-plus-2023.cfg to align with their settings.
Signed-off-by: Herb McNew <herb.mcnew@gmail.com>
> config: Fix sensorless homing for SV06 Plus

- klippy/configfile.py
- klippy/extras/adc_temperature.py
- klippy/extras/htu21d.py
- klippy/extras/spi_temperature.py
- klippy/extras/thermistor.py
- klippy/serialhdl.py
the `logger.warn` alias will be removed in upcoming Python 3.13. Changes are compatible with Python >= 2.7.
> Replace deprecated logger.warn with logger.warning

- config/sample-pwm-tool.cfg
- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Status_Reference.md
- docs/Using_PWM_Tools.md
- klippy/chelper/__init__.py
- klippy/chelper/stepcompress.c
- klippy/chelper/stepcompress.h
- klippy/extras/pwm_tool.py
- test/klippy/pwm.cfg
- test/klippy/pwm.test
This is an alternative implementation for #4128.  The goal is to support fine grained control of spindles, lasers, and similar tools that are controlled by PWM input.  The current `output_pin` module requires that each pin update have a minimum duration of 100ms, which is often not sufficient for these tools.  This PR introduces a new `pwm_tool` module capable of queuing PWM updates in the micro-controller and is therefore capable of much higher update rates.
This differs from #4128 in the implementation.  I'm leery that some of the low-level changes in #4128 may introduce a regression.  This PR makes only a few changes outside of the new pwm_tool.py code.  That is, the implementation here is mostly isolated to the new module and is therefore unlikely to introduce a regression to any …
> New pwm_tool module that supports mcu queing of pwm updates

- src/stm32/Kconfig
Enables the 64KiB bootloader offset for the whole F4 family.
> stm32: enable 64KiB bootloader offset for all F4

- .gitignore
- docs/Config_Reference.md
- klippy/extras/bme280.py
Add support for the older BMP180 sensor into the BMxx80 sensor category. Sensors supports oversampling for pressure only. No additional changes required to Mainsail, as it integrates into the existing display of temperature and humidity.
> Add support for BMP180 sensor

- klippy/configfile.py
It seems python3.12 has removed support for readfp() - use read_file() instead.
-Kevin
> Improve support for python3.12 in configfile.py

- klippy/extras/tmc5160.py
It's possible to build and configure tmc5160 drivers with external mosfets that support more than 3 amps.  The actual maximum for tmc5160 drivers is dependent on how the board is wired and the mosfets used. Increase the error check to 10 amps.  This error checking is primarily intended to catch "obvious misconfigurations" (eg, specifying milli-amps instead of amps), and the new value of 10 amps should suffice for this task.
This is an alternative to #6381 (and #6093).
@bigtreetech - FYI.
-Kevin
> tmc5160: Increase maximum current error check

- klippy/extras/exclude_object.py
gcmd.respond_error() has been deprecated: https://github.com/Klipper3d/klipper/commit/61524542d20e50c4866836d6ed23ca03521ffb15
Signed-off-by: Andrei Ignat <andrei@ignat.se>
> exclude_object: Fix use of deprecated gcmd.respond_error()

- klippy/extras/tmc.py
The set_register() code may block, and it therefore may be possible that the loop in _init_registers() could occur in parallel with other updates.  That could result in a "OrderedDict mutated during iteration" error.
Avoid the error by querying the latest value during each iteration of the loop.
Error reported at https://klipper.discourse.group/t/unhandled-exception-during-run-z-hop/11580 and https://klipper.discourse.group/t/sensorless-homing-x-returns-unhandled-exception-during-run/9844
-Kevin
> tmc: Query latest value during _init_registers()

- src/avr/Kconfig
Enable low-level menuconfig options for 328 and 328p
Signed-off-by: Andrei Kozhevnikov <coderusinbox@gmail.com>
> avr: enable low-level menuconfig options for 328 and 328p

- config/generic-ldo-leviathan-v1.2.cfg
- test/klippy/printers.test
This PR contains a generic config for the LDO Leviathan mainboard. I added the temperature sensors at the end because of the 2K2 pullup resistor. If this is not wanted, I can remove them.
> config: Add LDO Leviathan v1.2 generic config

- klippy/chelper/serialqueue.c
- klippy/clocksync.py
- klippy/extras/adxl345.py
- klippy/extras/angle.py
- klippy/extras/buttons.py
- klippy/extras/lis2dw.py
- klippy/extras/mpu9250.py
Various parts of the host code will convert a 32bit (or 16bit or 4bit) counter from the mcu to an internal integer counter that does not overflow.  However, that code often implements that "upconversion" in slightly different ways.  That can be confusing.
This PR reworks the code to use the same general format for these conversions.  The general method often simplifies the code as well.
@garethky - fyi.
-Kevin
> Simplify integer "upconversion" host code

- docs/Status_Reference.md
- klippy/gcode.py
This exposes a new `gcode` status object, with a list of the currently available commands:
It currently exposes the `commands` (all currently available commands in Klipper), and for each command, if the help text is available, it will also be included.
I understand that we already have the [gcode/help](https://www.klipper3d.org/API_Server.html#gcodehelp) endpoint, but this works on a pull, whereas status updates are pushed to the client.
> gcode: expose status with available commands

- docs/Config_Reference.md
- klippy/extras/pwm_tool.py
- klippy/mcu.py
- klippy/toolhead.py
This adds support for `maximum_mcu_duration` to the pwm_tool.py module.  This is intended to allow users to configure a safety check within the mcu to check for lost communication between host and mcu while a power tool is enabled.  With the merge of #6410 it should now be possible to implement this check.
I've run some basic tests on this code, but I don't have hardware to test real world cases.
Once this support is added, I will look to deprecate the existing `maximum_mcu_duration` in the `[output_pin]` module.  (That module has been getting complex, and I think the code may be more maintainable going forward if we can move users that need maximum_mcu_duration to the pwm_tool module.)
@Cirromulus - FYI.
-Kevin
> Add maximum_mcu_duration support to pwm_tool

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/hall_filament_width_sensor.py
Add support for maximum filament diameter to hall filament width sensor. If the diameter of the filament diameter is larger than the limit, the virtual runout sensor will trigger. The default value is set to maximum flow adjustment threshold to prevent oversized filament from clogging.
> hall_filament_width_sensor: max filament diameter

- src/stm32/fdcan.c
- src/stm32/stm32g4.c
- src/stm32/stm32h7_adc.c
- src/stm32/usbfs.c
The STM32G4 support never had USB or CAN tested, and changes to the STM32H7 ADC code in the meantime revealed a timing issue seen only as a small footnote in the reference manual.
Thanks to @mattthebaker for finding the USB issue first
> Fixes for STM32G4 devices

- klippy/extras/adxl345.py
- klippy/extras/angle.py
- klippy/extras/bulk_sensor.py
- klippy/extras/lis2dw.py
- klippy/extras/motion_report.py
- klippy/extras/mpu9250.py
This PR introduces new klippy/extras/bulk_sensor.py code and is intended to simplify the existing adxl345.py, mpu9250.py, lis2dw.py, and angle.py code.  This PR is an internal rework and should not produce a user noticeable change.
The existing host "bulk sensor" modules have a lot of duplicate code.  This makes it harder to maintain these modules, and makes it harder to add new "bulk sensors".  The goal of this PR is to move much of the low-level message handling code to bulk_sensor.py and to keep the per-chip modules focused just on chip specific logic.  Ideally this will make it easier to add future "bulk sensors".
This PR will also facilitate refactoring of the mcu code.  MCU code changes will require users to reflash their MCUs, so I'll plan on introducing those changes in a separate …
> Simplification of host bulk sensor code

- klippy/chelper/__init__.py
- klippy/chelper/stepcompress.c
- klippy/chelper/stepcompress.h
- klippy/chelper/trapq.c
- klippy/chelper/trapq.h
- klippy/extras/force_move.py
- klippy/extras/manual_stepper.py
- klippy/kinematics/extruder.py
- klippy/mcu.py
- klippy/toolhead.py
Currently the stepcompress history is removed as soon as it's older than 30 seconds before the furthest move in the stepcompress queue. If the furthest move is long and will end more than 30 seconds in the future, then the stepcompress history will return a "future" stepper position rather than a past position.
I found this issue while trying to graph the output of `extruder.find_past_position(print_time)` with a 45mm move at 1.33mm/s, which puts it around 33.8 seconds, and it would give me a graph like this one:
Note the purple line (the expected extruder position) is constant for the first ~4 seconds of the move rather than providing the expected stepper position. With this fix applied, the graph is as expected:
This was reported, for example, in: …
> Keep stepcompress move history relative to current time

- klippy/extras/buttons.py
Invoke button callbacks directly from the background thread.  This ensures that button notifications are delivered and delivered in the correct order.  Previously, if a callback blocked, it was possible a new update could start before the previous update was completed, which could lead to lost events or out of order events.
This issue was reported at:
https://klipper.discourse.group/t/query-button-unreliable/11452
https://klipper.discourse.group/t/bug-found-with-gcode-button/11932
-Kevin
> Fix possible ordering issue if a callback blocks in button handler

- docs/Bed_Mesh.md
I found a typo in a document Bed_Mesh.md.
In the section Mesh Interpolation of Advanced Configuration, the meaning and the illustration shows 13x9 mesh however the text is 13x8.
> fix: a typo in a document Bed Mesh

- docs/Multi_MCU_Homing.md
- klippy/mcu.py
When homing involves multiple micro-controllers the Klipper code arranges for all the micro-controllers to generate "keep-alive" messages.  This is designed to avoid an endstop signal not propagating due to a communication outage.
However, the existing code scheduled all of the micro-controllers to send their keep-alive message at the same time.  It's a little more optimal to stagger the updates so as to reduce instantaneous bandwidth and processing load.  This PR also slightly increases the rate of keep-alive messages to better handle some "corner cases" with lost messages.
This was also discussed at https://klipper.discourse.group/t/configurable-timeout/12032
-Kevin
> Improve scheduling of multi-mcu homing "trsync" messages

- config/printer-creality-ender5-s1-2023.cfg
- test/klippy/printers.test
My first GitHub submission....
From the main commit:
> printer-creality-ender5-s1-2023: New default config file for the Creality Ender 5 S1.
> 
> Creality released the Ender 5 S1 model in November of 2022.  It
> has enough hardware differences from the previous models that
> that the existing Ender 5 configs are not compatible.  This
> configuration is based on one provided by Creality that was then
> tweaked and modified.  I have been using these values (plus some
> additional entries) for about 6 months with no issues.
> 
> I have tidied up the file per the Example_Configs document,
> although I admit I may have missed something.  I'm happy to make
> or accept any required changes.
> 
All IP rights assigned to the Klipper3D project and development team.
Signed-off-by: Brian Greenberg …
> config: Add Creality Ender 5 S1.

- src/stm32/stm32g0.c
According to https://www.st.com/resource/en/datasheet/stm32g0b1cb.pdf page 55.
> stm32g0: Disable internal pull-down resistors on UCPDx CCx pins, because klipper never uses UCPD

- src/stm32/Kconfig
This offset is used by Anycubic Kobra 2 Neo bootloader
> Add  36KiB bootloader offset option

- config/generic-mini-rambo.cfg
- config/generic-ultimaker-ultimainboard-v2.cfg
- config/printer-adimlab-2018.cfg
- config/printer-creality-cr30-2021.cfg
- config/printer-lulzbot-mini1-2016.cfg
- config/printer-wanhao-duplicator-6-2016.cfg
- config/sample-macros.cfg
- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Status_Reference.md
- klippy/extras/multi_pin.py
- klippy/extras/output_pin.py
- klippy/extras/pwm_cycle_time.py
- klippy/extras/replicape.py
- klippy/extras/static_digital_output.py
- klippy/extras/sx1509.py
- klippy/mcu.py
- test/klippy/pwm.cfg
- test/klippy/pwm.test
Over the last few years the `output_pin` module has gained a handful of options that have made it harder to maintain the the low-level backend code.  This PR simplifies the output_pin module.  The main changes are:
1. The `static_value` parameter is deprecated.  This option has little impact - it only saves a few bytes in the micro-controller.  Going forward it is simple enough to just not specify it.
2. The `maximum_mcu_duration` parameter is deprecated.  The `pwm_tool` module is a better choice for tools that require this capability.  It should be straight forward for users to change their configs from `[output_pin mypin]` to `[pwm_tool mypin]`.
3. The `SET_PIN CYCLE_TIME=x` g-code command for `[output_pin mypin]` config sections has been removed.  Users can convert to a new …
> Deprecate and remove support for uncommon options in output_pin

- src/generic/armcm_boot.c
- src/rp2040/Makefile
- src/rp2040/main.c
- src/rp2040/rp2040_link.lds.S
There have been a few reports of instability on the rp2040 in code with strict timing requirements (eg, neopixels and tmcuart).  It is possible that rp2040 flash accesses are causing some timing instability.  Typically, all the active parts of the code would be fully loaded into the cache, and thus timing should not be variable.  However, it is possible that the initial cache load, or sporadic cache misses could lead to an issue.
This PR loads all of the code (along with the static data and irq vectortable) into ram on the rp2040.  With this PR, there should be few (if any) flash accesses after the initial code initialization.
Loading the rp2040 code into ram was previously proposed in PR #5889.
-Kevin
> Load all code into ram on the rp2040

- src/rp2040/spi.c
The rp2040 code was not initializing the SCLK line prior to the first SPI transfer.
This issue is likely the cause of common reports of `Invalid adxl345 id (got xx vs e5)` error on the first (and only first) adxl345 query.
@Sineos, @buzztiaan - FYI.
-Kevin
> Fix initial rp2040 SPI transfers

- klippy/extras/bed_mesh.py
This includes two minor fixes to the behavior of bed_mesh.
1) Avoid probing additional points for the `zero_reference_position` and `faulty_regions` when the user chooses the "manual" method.  Those options aren't useful when probing manually.
2) Fix a reporting regression introduced by the adaptive mesh change.  Since we avoid saving the mesh, the value reported in the `profile_name` field will be whatever was previously stored in `ProfileManger.current_profile`.   This is often an empty string, which is leading some frontends to believe that no mesh is loaded.  This patch moves profile name tracking to the ZMesh class and generates a placeholder name for adaptive meshes.
Kevin, this is likely going to cause a merge conflict with #6459, so if you would like we can hold this PR until its …
> bed_mesh: behavior fixes

- docs/Measuring_Resonances.md
When installing klipper using python3, I hit an issue when setting up numpy. Following the provided documentation leads to the following error when running `TEST_RESONANCES AXIS=X`
> Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details).
Attempting to import numpy through the virtualenv leads to the error:
```
~/klippy-env/bin/python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
File "/home/brujoand/klippy-env/lib/python3.9/site-packages/numpy/core/__init__.py", line 24, in <module>
from . import multiarray
File …
```
> doc: Add required dependency to run numpy with python3 on RPI

- docs/Bed_Mesh.md
- docs/G-Codes.md
- klippy/extras/bed_mesh.py
This adds a "Z" parameter to `BED_MESH_OFFSET` that is used to account for changes in `gcode offset` on the Z axis when calculating fade.  Without this, changing a tool that is offset on Z will cause jumps in the fade calculation.  This likely makes fade unusable for multi-tool printers.
This addition does not add any additional adjustment on the z-axis, so it cannot be used to replace `SET_GCODE_OFFSET`, and instead must be used to complement it.  Like `X` and `Y`, the `Z` offset should be relative to the primary extruder.  If a secondary extruder's nozzle is higher than the primary extruder by .2mm, then `BED_MESH_OFFSET Z=.2` is the correct setting.  Presumably this would come after `SET_GCODE_OFFSET Z=-.2`.   I believe this is consistent across all axes, but if it isn't I am open to …
> bed_mesh: support for Z in BED_MESH_OFFSET

- config/printer-geeetech-301-2019.cfg
- config/printer-modix-big60-2020.cfg
- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/extras/bed_mesh.py
- klippy/extras/heaters.py
- klippy/extras/temperature_sensors.cfg
- klippy/kinematics/extruder.py
This PR removes features that we have previously deprecated.  I'll look to make this change in about a month.  Details are in the PR:
Several deprecated features have been removed. Using "NTC 100K beta 3950" as a thermistor name has been removed (deprecated on 20211110). The `SYNC_STEPPER_TO_EXTRUDER` and `SET_EXTRUDER_STEP_DISTANCE` commands have been removed, and the extruder `shared_heater` config option has been removed (deprecated on 20220210). The bed_mesh `relative_reference_index` option has been removed (deprecated on 20230619).
-Kevin
> Remove previously deprecated features

- docs/Measuring_Resonances.md
- klippy/extras/resonance_tester.py
- klippy/extras/shaper_calibrate.py
- scripts/calibrate_shaper.py
The added parameters include square_corner_velocity, shaper frequencies to optimize, input shapers to test, input shaper damping ratio and damping ratios to test. All these options can be useful for fine-tuning the input shapers when the default suggestions generated by the tuning script are not optimal.
Also the `SHAPER_CALIBRATE` command was modified to pass some of these parameters to the shaper tuning routine. Specifically, square corner velocity and the maximum tested frequency are used to adjust shaper tuning and maximum acceleration recommendations.
I think the possibility to specify the `square_corner_velocity` is most useful. Some people change it against the recommendations, but may use the same maximum acceleration recommendations from the script without realizing that they …
> scripts: Added shaper tuning parameters to calibrate_shaper script

- klippy/extras/resonance_tester.py
- klippy/extras/shaper_calibrate.py
Fixed crashes due to wrong parameter passed to the shaper selection function and when the custom FREQ_END is specified.
> shaper_calibrate: Fixed crashes in SHAPER_CALIBRATE and TEST_RESONANCES

- docs/G-Codes.md
Adds the ADAPTIVE and ADAPTIVE_MARGIN parameters to the documentation.
> docs: updates BED_MESH_CALIBRATE description

- src/avr/Kconfig
Enable support for disabling optional features on atmega32u4 because size with all features enable is to big.
> avr: enable small code size options for atmega32u4

- config/printer-anycubic-kobra-go-2022.cfg
As the title says, "static_value" is deprecated, so I removed it and replaced it with "value".
> "static_value" in [output_pin enable_pin] is deprecated

- config/printer-anycubic-4maxpro-2.0-2021.cfg
- config/printer-sovol-sv05-2022.cfg
- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Kinematics.md
- docs/Resonance_Compensation.md
- docs/Status_Reference.md
- klippy/extras/resonance_tester.py
- klippy/toolhead.py
This is a proposal to remove the existing `max_accel_to_decel` parameter and replace it with a new `minimum_cruise_ratio` parameter.  This was proposed by Piezo at https://klipper.discourse.group/t/proportional-acceleration-control/3970 .
This doesn't change the underlying "accel to decel" system.  Instead, it renames the user-facing parameter to make it easier to describe and easier to understand.
It can be painful to make changes like this due to the possibility of breaking existing configs, but I think there are good reasons to pursue a change.
The `max_accel_to_decel` system was designed to avoid moves that immediate go from acceleration to deceleration by enforcing a minimum amount of movement at cruising speed between that acceleration and deceleration.  It does this by reducing the …
> Replace max_accel_to_decel with minimum_cruise_ratio

- klippy/extras/heaters.py
- klippy/extras/pid_calibrate.py
Make sure the SAVE_CONFIG command saves the calculated PID parameters to the correct config name.
This issue was reported at https://klipper.discourse.group/t/issue-with-pid-calibrate-heater-generic-save-config/14349 .
-Kevin
> Fix PID_CALIBRATE command when used with heater_generic

- klippy/extras/heaters.py
The pid logic can continue after a shutdown, even though the pin commands sent to the mcu are ignored.  However, this behavior can result in confusing "stats" messages in the log.  Explicitly disable updates after a shutdown event so that the log statistics are more clear.  This makes it more likely that the stats will show "pwm=0.00" instead of the last commanded pwm value.
-Kevin
> Clarify reported heater "pwm" stat after a shutdown

- klippy/configfile.py
- klippy/mcu.py
Several micro-controllers require a clock speed (or clock reference) to be configured in "make menuconfig".  Normally if this value is not configured correctly then the host will be unable to communicate with the micro-controller.  However, on a few boards, it is possible to establish communication with the mcu even if it has been incorrectly configured.  Unfortunately, when this happens the connection is often unstable, unexpected errors can occur, or confusing printer motion can result.
This PR updates the host code to check if the detected mcu frequency is notably different from the configured mcu frequency.  If there is a large difference then it will report a warning in the log and via the `printer.configfile.warnings` API server object.
@pedrolamas , @meteyou , @Arksine - as part of …
> Check and warn if mcu frequency differs from configured frequency

- scripts/buildcommands.py
For identification purposes it can be useful to extract a flash image and scan its contents.  The binwalk tool (eg, https://manpages.org/binwalk ) can already rapidly locate and extract the Klipper data dictionary from a flash image.  However, the data dictionary doesn't actually state that the image is Klipper.  This PR changes the build scripts to put the "Klipper" name and its license (GNU GPLv3) in the image so that that information is rapidly available.
-Kevin
> Add Klipper app name and license to mcu data dictionary

- src/stm32/stm32f0_i2c.c
> stm32: Add i2c3_PC0_PC1 for stm32g0

- klippy/extras/tmc2240.py
ADC values will be shown in Volts.
Output sample:
```
// ADC_VSUPPLY_AIN: 02d709b7 adc_vsupply=0x09b7(24.203V) adc_ain=0x02d7(221.880mV)
```
> tmc2240: add ADC voltage formatters

- src/linux/i2c.c
Similar to commit df79893, this allows klipper to use up to /dev/i2c-14. Similar to before, this limit is arbitrary.
This is required for some other SoCs, which have even more i2c buses available, e.g. the rk3399:
```
$ ls -1 /dev/i2c-*
/dev/i2c-0
/dev/i2c-3
/dev/i2c-7
```
> linux: Allow for more i2c buses

- klippy/extras/motion_report.py
When querying the stepper motion queue, the resulting "interval", "count", and "add" are already normalized to the correct direction. That is, the "count" field will be positive if moving in a positive axis direction and negative if moving in the reverse direction.  So, negating the step_distance field just complicates the readers.
-Kevin
> motion_report: Don't negate step_distance on steppers with inverted dir pin

- klippy/toolhead.py
The default minimum_cruise_ratio setting does not get populated to the printer.configfile.settings information due to the way the max_accel_to_decel backwards compatibility support was implemented. Slightly rework the config reading so that the default for minimum_cruise_ratio is populated there.
Reported by @ReXT3D.
-Kevin
> Populate minimum_cruise_ratio to printer.configfile.settings

- klippy/extras/virtual_sdcard.py
PR #6472 fixed unicode handling on Python3, but broke Python2 support.  
This could lead to error messages like `UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)` on Python2.
Use an alternate fix that should work for both Python3 and Python2.
@zxy16305, @CODeRUS - fyi.
-Kevin
> Fix virtual_sdcard handling of unicode characters on Python2

- src/stm32/stm32f0_i2c.c
Adds the 3rd hardware I2C bus for H7 based mainboards like the BTT Octopus Pro or the Manta M8P v2.0. 
Been running this commit for 2 weeks now on my Manta M8P v2.0 with a BME280 connected to it with no issues.
Signed-off-by: Balanuta Simion <contact@cybersnets.com>
> Add i2c3_PA8_PC9 bus to STM32H7

- Makefile
When building, a warning message appears at the end of the build output:
```
...
Version: ?-20240326_165244-67c86037cf03
Preprocessing out/src/generic/armcm_link.ld
Linking out/klipper.elf
lto-wrapper: warning: using serial compilation of 4 LTRANS jobs
lto-wrapper: note: see the '-flto' option documentation for more information
Creating hex file out/klipper.bin
...
```
To avoid this non-erroneous output, we set `CFLAGS` LTO flag with `-flto=auto` in the `Makefile`.
Signed-off-by: John Unland <junland.foss@gmail.com>
> makefile: fix warning about lto serial compilation

- klippy/configfile.py
- klippy/extras/dotstar.py
- klippy/extras/endstop_phase.py
- klippy/extras/idle_timeout.py
- klippy/extras/input_shaper.py
- klippy/kinematics/hybrid_corexy.py
- klippy/kinematics/hybrid_corexz.py
- klippy/mcu.py
- klippy/toolhead.py
- removes unused param 'eventtime' from heater.check_busy(  )
- removes a few unused assignments that are likely remnants of removed code
> remove dead code

- klippy/extras/homing_override.py
The `[homing_override]` has a gcode template that allows usage of the `params` but not `rawparams`.
This PR adds `rawparams` support to it thus making it consistent with the https://github.com/Klipper3d/klipper/blob/master/docs/Command_Templates.md#the-rawparams-variable information.
> homing_override: Adds rawparams support

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/virtual_sdcard.py
The `on_gcode_error` parameter allows one to run a set of g-code commands if an error is found while running a print using the virtual_sdcard system.  (Which is very common, as all the Klipper graphical frontends use this system to print.)
There is currently no default for this parameter.  That's not ideal, as an error that occurs during a print could result in the toolhead stopping with the heaters enabled and the nozzle directly over a partial print.
This PR adds a default - if the parameter is not specified it will default to `TURN_OFF_HEATERS`.  I think this is likely an improvement over the existing behavior.
Arguably, it would be even better to also raise the Z a few millimeters on a host detected command error.  Unfortunately, it's difficult to do that reliably, and I fear it may …
> Define a default for virtual_sdcard on_gcode_error

- klippy/extras/adxl345.py
- klippy/extras/angle.py
- klippy/extras/bulk_sensor.py
- klippy/extras/ldc1612.py
- klippy/extras/lis2dw.py
- klippy/extras/mpu9250.py
The code to calculate a timestamp for each sample in a bulk_sensor report is complex, and every sensor implementation was performing the calculation.  This PR moves that calculation into the generic ChipClockUpdater class.  This simplifies the sensor specific code.
@garethky - fyi.
-Kevin
> Refactor bulksensor timestamp calculation code

- docs/Config_Reference.md
- docs/Status_Reference.md
- klippy/extras/sht3x.py
- klippy/extras/temperature_sensors.cfg
I don't know why no one added this before, because Klipper already has an SHT2x family
So I got one and implemented support.
Hope it will be useful.
Thanks!
---
My current motivation:
I have BME* family for the chamber and SHT because wider temperature support will be used for the filament hot box/dryer, I can and will heat it to 110 C, and support for humidity will help in that case.
/* And SHT3x/SHT4x are easier to get nowadays */
[Datasheet](https://sensirion.com/media/documents/213E6A3B/63A5A569/Datasheet_SHT3x_DIS.pdf)
> sensors: add sht31 support

- docs/Bed_Mesh.md
Fixed a typo and reformatted the `mesh_max` section in `Bed_Mesh.md`
> Fix docs typo

- docs/Config_Reference.md
- klippy/extras/bme280.py
Extends the BMxx80 category with support for the BMP388 sensor, providing temperature and pressure output similar to the existing BMxx80 class of sensors.
> bme280: Add BMP388 sensor support to BMxx80

- src/rp2040/Kconfig
- src/rp2040/serial.c
Current implementation only supports UART0 on Pin0 and 1. 
This change brings in all the possible UART 0 and 1 pin combinations for the RP2040.
Has been tested on a custom board with UART1 on 24,25
> Add kconfig options for rp2040 uart

- klippy/configfile.py
- klippy/serialhdl.py
logging.warn is an alias to logging.warning since Python 3.3 and will be removed in Python 3.13.
> Replace logging.warn usage with logging.warning

- src/stm32/spi.c
This is an update to the pasren89 patch for the naming convention of new spi pin sets.
modified:   src/stm32/spi.c
> Add new pin set for spi2 on stm32g0 chips

- config/printer-creality-cr6se-2020.cfg
- config/printer-creality-cr6se-2021.cfg
The Creality CR-6 SE has a strain gauge on its hotend, which is used for z-probing and homing. Currently, running G28 to home all axes puts the hotend just outside of the print bed and thus assumes a wrong homing point for the Z axis.
This pull request aims to address this issue by setting a safe Z-homing point (in the middle of the print bed) into the Creality CR-6 SE 2020 and 2021-revision config files.
> config: Set safe Z-homing point in Creality CR-6 SE configuration

- klippy/extras/bed_mesh.py
Round beds require an odd number of probe points in order to prevent erroneously truncating the mesh.
The adaptive mesh algorithm did not consider that and as a result, it was possible to generate adaptive
meshes with even number of probe points.
This change fixes this by increasing the probe point count by 1 in cases where the adaptive probe points are even.
> Fix adaptive probe count on delta printers

- klippy/kinematics/cartesian.py
- klippy/kinematics/hybrid_corexy.py
- klippy/kinematics/hybrid_corexz.py
- klippy/kinematics/idex_modes.py
idex_mode would swap the X and dual-carriage rail in some cases (homing), but not in others. As such, the position calculation was correct while homing, but incorrect for the second carriage during normal moves. This commit fixes homing to work without swapped rails, removes the swapping of rails while homing, and removes the ability to swap rails (as it is now no longer used). Fix has been tested in a Hybrid_CoreXY IDEX printer (Voron Double Dragon). Hybrid_CoreXZ has identical changes and is similar enough that I am confident it will work as intended. Changes to cartesion seem simple enough, but would benefit from someone running a couple of tests.
> idex_modes: Bugfix for kinematic position calculation.

- docs/Config_Reference.md
- klippy/extras/tmc.py
- klippy/stepper.py
A couple of minor enhancements that I noticed after the merge of #6139 .
1. Simplify the `TMCtstepHelper()` code.
2. There is no need to warn the user about setting `high_velocity_threshold` when using sensorless homing as the sensorless homing can save/restore `thigh`.
@leptun - it would be great if you could take a look at these changes.
-Kevin
> Minor tmc driver improvements

- scripts/motan/readlog.py
The mcu_phase_offset should be added not subtracted.
@nefelim4ag - fyi.
-Kevin
> Fix motan logic error resulting in incorrect stepper phase graphing

- klippy/extras/axis_twist_compensation.py
- klippy/extras/bltouch.py
- klippy/extras/probe.py
- klippy/extras/probe_eddy_current.py
- klippy/extras/smart_effector.py
This is an internal refactoring of the probe.py PrinterProbe class.  Basically the goal is to split up the functionality in that class into a series of more manageable classes (ProbeCommandHelper, ProbeSessionHelper, HomingViaProbeHelper, and ProbeOffsetsHelper).  The goal is to separate functionality so that it is easier to add features in the future.  There should be no user visible changes as part of this PR.
@Arksine - fyi.
-Kevin
> Internal rework of PrinterProbe class

- klippy/extras/bulk_sensor.py
- klippy/extras/ldc1612.py
- klippy/mcu.py
- klippy/msgproto.py
- scripts/buildcommands.py
- src/command.c
- src/command.h
- src/pru/pru0.c
- src/sensor_bulk.h
- src/sensor_ldc1612.c
Currently the message protocol only supports 128 possible message ids.  However, some microcontroller builds need up to ~125 messages today and some proposed code additions are exceeding the limit.
This PR increases the limit from 128 message ids to 16384 ids.  It does this by adding support for either 1 or 2 byte message ids in the low-level message parsing code.
This does mean that the bulk sensor code should use no more than 51 bytes of data when reporting results back to the host.  (A message can be up to 64 bytes long: 5 bytes for the headers, 2 bytes for the response id, 2 bytes for oid, 3 bytes for the sequence number, 1 byte for data length, 51 bytes of data.)  This is a breaking change for the ldc1612 sensor support - users with this sensor will need to recompile and reflash …
> Support 2-byte message ids in host/mcu protocol

- klippy/extras/probe.py
- klippy/extras/probe_eddy_current.py
This is an alternate implementation to the "scan" mode introduced in PR #6558 .  The main difference is that this PR refactors the internal probe classes with a goal to "flatten" some of those interactions between classes.
This PR is on top of PR #6605 .
@Arksine - the main goal of this PR is to demonstrate a possible internal interface between the classes for the "detailed scan" mode.  That is, the toolhead movements still go through ProbePointsHelper, but now `PrinterEddyProbe` can detect a "scan" request and substitute a different probe implementation.  Also, the same sample gathering code is used for both "descend until trigger" and "scan probing" modes.  I understand your PR had improved user options, improved documentation, and other improvements.  Happy to change this PR further, …
> Add ldc1612 support for "METHOD=scan" probing

- src/atsam/Makefile
- src/atsamd/Makefile
- src/generic/armcm_link.lds.S
- src/hc32f460/Makefile
- src/lpc176x/Makefile
- src/rp2040/Makefile
- src/rp2040/rp2040_link.lds.S
- src/stm32/Makefile
It seems recent arm gcc versions no longer build correctly using the `--specs=nano.specs --specs=nosys.specs` linker flags.  Replace those linker flags with `-nostdlib -lgcc -lc_nano`.
This seems to fix the build on recent gcc versions, it eliminates some build time warnings, and does not increase the size of the resulting binary.
-Kevin
> Fix build on recent arm gcc/newlibc versions

- docs/API_Server.md
- docs/Bed_Mesh.md
- docs/Config_Reference.md
- klippy/extras/bed_mesh.py
- klippy/extras/probe_eddy_current.py
- scripts/graph_mesh.py
This pull request builds on #6610, adding support for optimized travel paths when a `rapid_scan` is requested.   In addition, the `probe_finalize()` method no longer depends on on the XY coordinates received from the probing procedure to populate the Z matrix.
The final commit in this series updates `gnupru` to the latest release in `ci-install.sh`.  It appears that version `2023.1` fails due to a missing dependency.
> bed_mesh: add support for "rapid" scanning

- klippy/extras/adc_scaled.py
- klippy/extras/adc_temperature.py
- klippy/extras/buttons.py
- klippy/extras/error_mcu.py
- klippy/extras/hall_filament_width_sensor.py
- klippy/extras/temperature_mcu.py
- klippy/extras/tsl1401cl_filament_width_sensor.py
- klippy/klippy.py
- klippy/mcu.py
This PR adds a new error_mcu host module to facilitate error formatting.  It also attempts to report which ADC sensor is out of range on an "ADC out of range" mcu error.
Handling micro-controller errors is challenging because we really want the heaters to be disabled if an unexpected error occurs.  That means we don't want a lot of code complexity to analyze the source of the error in the code that needs to immediately handle that error.  This can lead to crytpic mcu error reports.
This PR creates a new error_mcu host module that can analyze the low-level error reports after the main shutdown processing has completed.  Thus, the error_mcu code is no longer on the "critical shutdown path" and can take more time and resources to format a more user friendly error message.
With this PR, the …
> New error_mcu module; report sensor on "ADC out of range"

- config/printer-tronxy-crux1-2022.cfg
- test/klippy/printers.test
Adds a basic config for the Tronxy Crux1 3D printer for the newest currently sold variant with the Tronxy CXY-V10.1-220921 mainboard with either the GD32F4XX or STM32F446 MCU (firmware works for both versions).
Fully tested, working on an otherwise completely stock machine.
Config contains instructions on how to build and flash the firmware as well.
> Adds support for the Tronxy Crux1 printer

- klippy/extras/bus.py
- klippy/extras/sht3x.py
SHT3X supports periodic mode, which allows us to completely skip the "write" phase and wait, and just read data in one command.
Also, I corrected reactor pauses to the right numeric order (they are also wrong in htu21.py).
Thanks.
> sht3x: use periodic report mode

- docs/Config_Reference.md
- docs/Eddy_Probe.md
- docs/G-Codes.md
- klippy/extras/probe_eddy_current.py
- klippy/extras/temperature_probe.py
This adds a `temperature_probe` module that supports configuring a temperature sensor for use with inductive probes.  This module implements the smoothing algorithm present in heaters and provides a temperature drift calibration procedure.  The module is intended to be generic, it can be used with any kind of inductive probe, where the calibration logic is farmed out to the probe specific implementation.  Also included in this PR is an implementation for the `probe_eddy_current` module.
The calibration procedure works by using the bed to heat the probe and requesting a manual probe before each sample.  This is intended to filter out thermal expansion.  Samples are taken at a specified temperature interval, by default this is set to every 2C.  The best calibration is achieved by taking …
> temperature_probe: probe thermal drift compensation

- klippy/kinematics/idex_modes.py
- test/klippy/dual_carriage.cfg
- test/klippy/dual_carriage.test
Previous implementation could crash the idex carriages into each other. The new code moves the idex carriages together, eliminating this risk and decreasing the time needed to restore the carriages positions.
> idex_modes: Improved restoring position in RESTORE_DUAL_CARRIAGE_STATE

- klippy/extras/servo.py
This change follows the same approach as implemented for fan control. The change removes the move queue flushing when changing servo position, which does not appear to be necessary. This can be beneficial, for example, for WS7040-based cooling on IDEX setups where the servo can be used to control the air flow between the toolheads, with this change eliminating micro-stutters of the toolhead on servo position adjustment.
> servo: Asynchronous adjustments of servo position

- docs/Installation.md
- docs/OctoPrint.md
- docs/Overview.md
- docs/_klipper3d/mkdocs.yml
This is an attempt to update the installation documents to reflect the changes in the Klipper ecosystem over the last few years.
The current documentation references OctoPrint as being the only way to install Klipper, whereas this has not been the case for quite a long time now.
I have attempted to keep the OctoPrint instructions and have created a secondary file that references this way to install as I still believe this is still valid and promotes choice.
Please feel free to make comments changes spelling mistakes and the usual.
Thanks
James
> docs: Update Installation.md

- src/stm32/stm32h7_adc.c
I built my own 3D printer board with STM32G431 and flashed klipper firmware. I connected PA0 to heater bed sensor but always get random value. Finally I found that in array "adc_pins", the first element is 0 but GPIO('A', 0) equals 0, too. This causes the "gpio_adc_setup" functoin will get the wrong ADC channel of PA0. Here I changed it to 0xFF and it works fine.
> Fix getting wrong ADC value on PA0 of STM32G431

- klippy/extras/gcode_arcs.py
TLDR:
On doing arcs klipper can spend a 'lot' of time locked in planArc creating segments.
5..30ms depends on host performance and arc length, segments count/length.
Performance-wise, this change is marginal +1% in normal circumstances - this is more like suggestion.
In the limit it will be better, the more segments we have.
Thanks.
_For profiling, I used perf/py-spy, which is not perfectly accurate. So, long sampling durations, fixed CPU freq, and high sampling count._
---
For context:
I sometimes heard and experienced strange CPU spikes when using arcs.
So, I was curious.
Real usage is beneath in C code, at itersolve_gen_steps_range, pa_range_integrate & etc.
Because a lot of segments generate a lot of small moves & etc.
This is a different topic.
> gcode_arc: use arc generator - reduce blocking time

- src/sensor_ads1220.c
- src/sensor_hx71x.c
- src/sensor_ldc1612.c
As the input values are uint8_t types, any shift may result in value loss.
Explicit promotion to the output type (uint32_t) keeps things safe.
Have also changed the int32_t in ads1220_read_adc to uint32_t, type promotion and bit manipulation are a bit 'weird' on signed integers, so keep it as an unsigned to align with following function call parameter type.
Have retained the prior explicit sign extension logic however.
> Warning Fix: Current code produces warnings for possible value overflows.

- docs/API_Server.md
- klippy/extras/ads1220.py
- klippy/extras/hx71x.py
- src/sensor_hx71x.c
Hi @garethky,
I noticed a few minor things in the recent bulk_adc merge.
1. The bulk adc report includes the adc value as a float, but the header and docs weren't updated to reflect that.
2. I think it would be a little better to check for hx71x timing overflows via the timer handler.  This check should be a little more accurate as it includes the time needed to wake up the query task.  It should also be a little more efficient to check.
3. I wonder if we could automatically restart hx71x samples after an error if the code receives 4 valid looking samples.  The idea here is: In the event of a read overrun, it's likely the sample is bad and it should be discarded; the following sample is also likely bad as some leading bits may have been erroneously read in the previous sample; the next …
> Assorted minor hx71x changes

- docs/Config_Reference.md
- docs/Eddy_Probe.md
- klippy/extras/temperature_probe.py
This pull request addresses an issue with users unable to calibrate across a wide coil temperature range.  Specifically, unenclosed printers commonly achieve a maximum temperature between 50-55C.  The result is a calibration with polynomials that intersect at higher temperatures.  The `temperature_probe` module checks for this condition post-calibration, and said users are experiencing failures.
This patch introduces the `max_valid_temp` config option, which replaces the hard coded maximum validation temperature of 120C.  This option will not impact current calibrations.
> temperature_probe: add 'max_valid_temp' option

- scripts/spi_flash/board_defs.py
- scripts/spi_flash/spi_flash.py
Add flashsd configuration for Tronxy x5sa and other printers based on Chitu v6 board.
These boards should support sdio (this is what the schematic details), however I couldn't get this working from a quick try.
<details><summary>Edit: Add sequence demo</summary>
</details>
> flashsd: Add support for chitu-v6

- klippy/extras/ads1220.py
- klippy/extras/hx71x.py
- test/klippy/load_cell.cfg
- test/klippy/load_cell.test
This minor code change should fix the hx71x support on python2 installations.  It also adds a load_cell regression test case.
@garethky , @alchemyEngine - fyi.
-Kevin
> Fix hx71x on python2

- docs/Config_Changes.md
- klippy/extras/fan.py
- klippy/extras/output_pin.py
- klippy/extras/servo.py
This PR adds a new mechanism for queuing of fan updates.  (It also applies to output_pin and servo objects.)  Due to the low-level mechanism used to transmit updates to the mcus, it is necessary for each update to apply for a minimum amount of time - typically 100ms.  Previously, if one were to send many fan updates in rapid succession, the code would batch up those updates and apply them in succession.  (With each update running for at least 100ms.)  This could result in the fan updates becoming out of sync with the toolhead.
This PR adds new code to collect fan updates in the host and only send the latest fan update to the mcu.  For example, in the following sequence:
```
G4 P2000
M106 S100
M106 S101
M106 S102
M106 S103
M106 S104
G1 X100
```
The old code would apply four fan speed …
> Queue and collate fan requests (and output_pin and servo)

- klippy/extras/bus.py
- klippy/extras/sx1509.py
- src/i2ccmds.c
i2c_modify_bits is tricky and used only in one place where it actually seems overcomplicated.
We do not modify registers in other places, they are reset before setting new bits.
So they can be simplified to i2c_write.
Datasheet: https://cdn.sparkfun.com/datasheets/BreakoutBoards/sx1509.pdf
Thanks.
---
#6674
> SX1509: drop i2c modify bits

- scripts/flash_usb.py
This solves an issue where the USB directory could exist, but the busnum file itself may not exist immediately. This was encountered when flashing a Pico connected to a Raspberry Pi 5.
> flash_usb: Wait for busnum file to exist when flashing with picoboot

- docs/G-Codes.md
- klippy/extras/controller_fan.py
- klippy/extras/dotstar.py
- klippy/extras/fan.py
- klippy/extras/fan_generic.py
- klippy/extras/heater_fan.py
- klippy/extras/led.py
- klippy/extras/neopixel.py
- klippy/extras/output_pin.py
- klippy/extras/pca9533.py
- klippy/extras/pca9632.py
- klippy/extras/temperature_fan.py
This PR adds support for specifying a math formula for output_pin and fan_generic objects.  This works similarly to the "led template" support - one can specify a `[display_template my_template]` config section that contains a Jinja2 macro providing a formula, and that formula will then be evaluated periodically to determine the pin/fan setting to apply.
The settings from the formula do not pass through the g-code command queue, so the updates are applied even during homing and other long running commands.
This should make it possible to define more flexible pin and fan control schemes.
-Kevin
> Add support for output_pin and fan templates

- docs/Config_Reference.md
- src/stm32/stm32f0_i2c.c
Right now i2c frequency is hardcoded, I think for stm32f0.
STM32f0 pclk is 48Mhz.
My STM32H7 has 400Mhz -> 100Mhz pclk.
it runs faster at around 200kHz
https://klipper.discourse.group/t/stm32h7-wrong-i2c-timings-200khz/18676
```
>>> 44 / 9
4.88
>>> 1 / 0.0000048
208333.33
>>> 208333.33 / 100 * 48
99999.99
```
I added some actual timing calculations, but I can't get them precise.
100kHz, 1 / 0.0000085= 117647 
400kHz, 1 / 0.0000025 = 400000
1000kHz, 1 / 0.0000013 = 769230
This is as close, as I can get to target values.
> stm32f0/i2c.c: calculate correct bus frequency

- docs/Benchmarks.md
- docs/Features.md
- src/atsam/Kconfig
- src/atsam/Makefile
- src/atsam/fdcan.c
- src/atsam/sam3_usb.c
- src/atsam/same70_link.lds.S
- src/atsam/same70_sysinit.c
Currently, this MCU is _slow_. Much slower than a 300MHz chip should be. This is due to the bus speeds being half the core clock, and the high number of wait states required to retrieve instructions from flash. This MCU can avoid these wait states by locating part of the code in Instruction Tightly Coupled Memory (ITCM). Klipper is currently less than one quarter of the size of the ITCM when enabled (USB build, slightly larger for USBCANBUS). These commits do the following:
1. If Tightly Coupled Memory (TCM) is not configured, sets it.
2. Relocates all of Klipper into ITCM after boot via Direct Memory Access (DMA), then enables ITCM.
a. This avoids large changes, especially to the linker script.
b. This is possible because ARM Cortex M7 MCUs remap access to the ITCM region to flash memory …
> Increase speeds of same70 by using Tightly Coupled Memory and DCache

- docs/OctoPrint.md
This PR corrects a simple mistake where I gave the Unix socket not the serial pts.
Thanks
James
> Update OctoPrint.md - wrong serial address

- docs/Config_Reference.md
- klippy/extras/ads1220.py
* fix type comparison bug that stopped the sensor from initializing (no one could actually use it)
* correct mismatch between docs and code for `sample_rate` (fixed to work same as hx71x)
* add `input_mux`, `pga_bypass` and `vref` options
* update configuration reference & fix typos
> Add input_mux and vref options to ADS1220 sensor

- src/atsam/gpio.h
- src/atsam/i2c.c
- src/atsamd/gpio.h
- src/atsamd/i2c.c
- src/avr/gpio.h
- src/avr/i2c.c
- src/hc32f460/gpio.h
- src/i2c_software.c
- src/i2c_software.h
- src/i2ccmds.c
- src/i2ccmds.h
- src/linux/gpio.h
- src/linux/i2c.c
- src/lpc176x/gpio.h
- src/lpc176x/i2c.c
- src/rp2040/gpio.h
- src/rp2040/i2c.c
- src/sensor_ldc1612.c
- src/sensor_mpu9250.c
- src/stm32/gpio.h
- src/stm32/i2c.c
- src/stm32/stm32f0_i2c.c
As mentioned: https://github.com/Klipper3d/klipper/pull/6674#issuecomment-2344669008
That would be nice to handle I2C errors, instead of the current shutdown approach.
There is a refactoring part to make things more obvious, where is the dev and where is the bus.
Errors handling works, but:
- Some MCUs do not clearly state what happens underneath.
- ~~There should be a better way to define & pass errors to Klippy. I think it would be possible to reuse static_stings_id for that.~~
-  ~~When klippy inits and I2C returns an error, it is an unhandled exception, so it only appears in logs. There should be a fix actually to show it to frontends as before with shutdown msg.~~
- ~~Missing handling for~~ ldc1612 - used in homing sequence, there is no reason or way to handle errors.
- mpu9250 - …
> I2C Error handling

- klippy/mcu.py
This reduces the chance of spurious MCU clock configuration warnings.
So, if an MCU is configured for 400Mhz, a warning will only be issued if an actual clock >404Mhz or <396Mhz is found.
-Kevin
> Only warn about mcu clock frequency if drift is more than 1%

- src/avr/timer.c
- src/generic/armcm_timer.c
- src/generic/timer_irq.c
- src/linux/timer.c
- src/sched.c
- src/sched.h
Rename `sched_tasks_busy()` to `sched_check_set_tasks_busy()` and change it to only return true if tasks are active (running or requested) for two consecutive calls.  This makes it less likely that timers will yield to tasks except when tasks really are notably backlogged.
This also makes it less likely that multiple steppers controlling the same rail will be interrupted by tasks mid-step.  This should slightly improve the timing, and make it less likely that a halt during homing/probing will occur with these steppers taking a different number of total steps.
This was discussed at: https://klipper.discourse.group/t/z-stepper-microstep-shift-on-multi-mcu-homing-loadcell-ldc1612/19524/
-Kevin
> Improve timer vs task priority check

- klippy/extras/homing.py
- klippy/stepper.py
- src/trsync.c
During a probe attempt, the internal tracking of positions should not change.  Verify this after each probe and log a warning if the post-probe position tracking does not match the pre-probe position tracking.
Also, fix an error in the ldc1612 probe trigger notification - it should have called `trsync_do_trigger()` with irqs disabled.  Fix by changing `trsync_do_trigger()` to internally disable irqs to avoid issues like this in the future.
-Kevin
EDIT: This was discussed at: https://klipper.discourse.group/t/z-stepper-microstep-shift-on-multi-mcu-homing-loadcell-ldc1612/19524/
> Probe position skew warning and ldc1612 irq fix

- klippy/configfile.py
This change reworks and simplifies the configfile.py code.  Most of the work involves splitting the main `PrinterConfig` class into multiple sub-classes.
One possible user facing change is improved detection of a corrupt auto-save config section.  Previously, the code might end up writing out multiple auto-save config sections, which could be confusing.  With this branch, if the auto-save config section is corrupt, an error will be reported if a new SAVE_CONFIG command is issued.
-Kevin
> Config file reading internal code cleanup

- klippy/extras/fan_generic.py
At the moment, using `SET_FAN_SPEED` with a display template that does not resolve to a string that can get converted to a valid float will cause a crash as the `import logging` is missing.
> fan_generic: fixes missing logging import

- config/sample-duet3-1lc.cfg
- docs/Config_Reference.md
- klippy/extras/lis2dw.py
- klippy/extras/lis3dh.py
- src/Kconfig
- src/ar100/gpio.h
- src/atsamd/i2c.c
- src/generic/gpio.h
- src/sensor_lis2dw.c
This adds the LIS3DH accelerometer, and brings support for I2C to the LIS2DW. This branch also contains a documentation commit for these changes, a commit allowing the hardware I2C speed on atsamd chips to achieve fast-mode, and an addition to the sample configuration for the Duet3D 1LC. I am personally only able to test the LIS3DH over I2C.
Actions required:
Previous PRs related to this functionality: #6638 #6477
Tagging @KevinOConnor for possible LIS2DW regression testing, @dmbutyugin for possible LIS3DH SPI testing, and @eamaclean for the atsamd change.
> Add LIS3DH and I2C support to LIS2DW

- docs/Config_Changes.md
- docs/G-Codes.md
- klippy/extras/resonance_tester.py
-The current code does not have the option to "live" select a non-adxl345 `chips` when running `TEST_RESONANCES`, since it adds the adxl prefix by default.
-Added the ability to "live" select `accel_per_hz` when running `TEST_RESONANCES`.
-Minor fixes in the documentation.
Signed-off-by: Maksim Bolgov maksim8024@gmail.com
> resonance_tester: Fix chips selection, add accel_per_hz selection

- src/rp2040/spi.c
I purchased the fysetc PITB v2 board, which is not functioning via software spi, and I'm not 100% sure why.  
The issue with hardware spi, is that this board is wired such that:
SCK: gpio2
MOSI: gpio3
MISO: gpio4
however, the spi0 configuration currently in the klipper codebase, only allows an spi permutation of:
SCK: 2
MOSI: 3
MISO: 0
However, that said, I've seen a few cases around the internet in troubleshooting this, that show people using the rp2040 spi bus configured this way, as well as the PITB v2 board.  The rp2040 datasheet (page 13: [here](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf)) shows it as a supported configuration, so I added spi0e as an option, and everything now started up and works.   
I'd almost suggest perhaps a more configurable way of managing …
> Add spi0e bus for rp2040, used on pitb v2 by fysetc

- docs/Config_Changes.md
- klippy/gcode.py
The g-code command parser did not allow three characters to be passed as parameters to commands (asterisk, semicolon, pound sign).  Rework the parsing code to better leverage the python shlex package so that these characters can be supported.
In particular, this should allow better support for printing g-code files that have unusual characters in the filename.
-Kevin
> gcode: Improve handling of extended g-code commands with '*;#' characters

- docs/Config_Reference.md
- klippy/extras/display/aip31068_spi.py
- klippy/extras/display/display.py
Adds support for `YHCB2004` display used in `Geeetech A10/M/T` printers. 
The display is based on `AIP31068` controller and uses 9-bit SPI commands. 
The details were found in Marlin FW that supports this display (see https://github.com/MarlinFirmware/Marlin/issues/25196).
~~This PR depends on merging of https://github.com/Klipper3d/klipper/pull/6633 to enable 9-bit SPI.~~
UPD: implemented proposed fix of sending 8 commands (9 bit each) = 9 bytes (8 bit each)
> display: Add support for `AIP31068` based displays

- klippy/extras/tmc2240.py
There are 3 address pins on this device, allowing a maximum address of 7.
> Correct maximum TMC2240 UART address.

- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/Measuring_Resonances.md
- klippy/extras/resonance_tester.py
- klippy/extras/shaper_calibrate.py
- klippy/toolhead.py
This adds a new resonance test method that can help if a user has some mechanical problems with the printer. The new method is not enabled by default and can be activated via a config option.
> resonance_tester: Added a new sweeping_vibrations resonance test method

- lib/rp2040_flash/main.c
`model_t` is a enum value [here](https://github.com/Klipper3d/klipper/blob/master/lib/rp2040_flash/picoboot_connection.h#L44)
It should be `rp2040` (actual value is 0, `rp2350` is 1, and `unknown` is 2)
> lib: fix rp2040_flash

- klippy/extras/z_tilt.py
- Set `printer.z_tilt.applied = True` when max_retries is 0
- and then raises error when `[z_tilt] retry_tolerance = 0` 
[Discourse Link](https://klipper.discourse.group/t/possible-bug-printer-z-tilt-applied-not-true-if-no-retries-in-config/20584/2)
> z_tilt: return done when max retries is 0

- klippy/extras/heaters.py
Update the heating code to periodically check that the main thread is operating properly.  This is a mitigation for some rare cases where the main thread may lockup while the background heater updating code continues to run.  The goal is to detect these rare failures and disable future heater updates.
This was discussed at https://klipper.discourse.group/t/bug-klipper-does-not-properly-turn-off-heaters-on-host-crash/20015
-Kevin
> Disable heater if it appears main thread has stopped updating

- klippy/extras/force_move.py
- klippy/extras/homing.py
- klippy/extras/homing_override.py
- klippy/extras/manual_stepper.py
- klippy/extras/safe_z_home.py
- klippy/extras/stepper_enable.py
- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/corexz.py
- klippy/kinematics/delta.py
- klippy/kinematics/deltesian.py
- klippy/kinematics/hybrid_corexy.py
- klippy/kinematics/hybrid_corexz.py
- klippy/kinematics/none.py
- klippy/kinematics/polar.py
- klippy/kinematics/rotary_delta.py
- klippy/kinematics/winch.py
- klippy/toolhead.py
Now that clear_homing_state() has been implemented, there is no longer a need for each kinematic class to manually register for the "motor_off" event, as the stepper_enable class can directly call clear_homing_state().
Also this changes the homing_axes and clear_axes parameters of the set_position() and clear_homing_state() to pass strings (eg, "xyz") instead of a list of numbers.
@twelho - fyi.
-Kevin
> Simplify kinematic set_position() and clear_homing_state() calls

- docs/Config_Reference.md
- klippy/extras/ads1x1x.py
- klippy/extras/temperature_sensors.cfg
Added support for ADC chips ADS1103, ADS1104, ADS1105, ADS1113, ADS1114 and ADS1115.
The PR is rougly based on https://github.com/Klipper3d/klipper/pull/5618 but with a different architecture.
I've tested it with an ADS1115 and a linux mcu host.
> ads1x1x: added support for ADC chip

- klippy/extras/screws_tilt_adjust.py
On [my previous PR](https://github.com/Klipper3d/klipper/pull/5992) to make this an object I forgot to correctly initialize `results` as an object; this PR fixed that.
> screws_tilt_adjust: initialize status result as a dictionary

- klippy/extras/garbage_collection.py
- klippy/toolhead.py
This is my attempt to address Timer Too Close errors on some slower machines. Through some debugging that started with something @KevinOConnor pointed out in #6784, I observed a correlation between generation 2 collection happening at the same time as homing moves (in particular during happy hare drip/homing moves...with happy hare the user will experience many more "homing" moves than a standard non-mmu enabled printer because it "homes" filament to various sensors each time filament is swapped. I found that on my Orange Pi CM4, the generation 2 garbage collection takes between ~150-300ms depending on whether I have the shake and tune module enabled. Based on the discussion in #6784, those homing moves require low latency (<100ms) communication. So having gc that takes longer than this …
> fix(gc): freeze gc objects after startup 

- docs/Status_Reference.md
- klippy/extras/canbus_stats.py
- klippy/mcu.py
- src/atsam/fdcan.c
- src/atsamd/fdcan.c
- src/generic/canbus.h
- src/generic/canserial.c
- src/generic/usb_canbus.c
- src/rp2040/can.c
- src/stm32/can.c
- src/stm32/fdcan.c
This PR adds support for reporting the micro-controller canbus receive and transmit error status.
The low-level canbus hardware will generally automatically retransmit messages that don't transmit correctly (eg, due to line noise).  Unfortunately, this system may hide wiring problems - wiring problems that could cause hard to debug failures in the middle of a print.
The new code here will report the low-level interface statistics in the log statistics messages.  For example, one might see messages like: `Stats 815.9: ... canstat_mcu: rx_error=0 tx_error=0 bus_state=active ... canstat_corexy_rear_left: rx_error=0 tx_error=0 bus_state=active`
In addition to the additional logging, the "usb to canbus bridge mode" has also been extended to detect canbus stalls.  Previously, if the canbus were …
> Improved canbus diagnostics

- docs/Config_Changes.md
- docs/G-Codes.md
- klippy/extras/save_variables.py
This is a follow up on [this Discorse topic](https://klipper.discourse.group/t/save-variable-only-works-with-lower-case-variable-names/21032), ensuring the variable name is converted to lowercase before saving and documenting this change to fix the incorrect behavior.
> save_variables: Check lowercase variable names

- docs/Installation.md
The documentation install page has a link to the old mainsail OS site, which is no longer available
> docs: Fix broken link to MainsailOS

- src/stm32/gpio.h
- src/stm32/stm32h7_spi.c
Currently, there is an issue with spi bus frequency and possibly mode.
If several different devices are present on the bus because of the logical `OR` gate on CFG registers, mode and div will be merged.
So, if they share mode speed will be lower, in my specific case 4Mhz TMC (MBR 6) + 10Mhz encoder (MBR 5), causes div to be 6|5 = 7.
So, this is a simple fix to allow a proper reload of CFG registers.
STM32H7 (at 480Mhz) so expected frequencies:
- 480_000_000 >> (5 + 1) = 7500000
- 480_000_000 >> (6 + 1) = 3750000
There are oscilloscope probes, while both are running:
Thanks.
> stm32: h7 spi support reload mode & frequency

- scripts/spi_flash/board_defs.py
Addition to the board_defs file for the BTT Octopus Max EZ, written and confirmed by discord user Nikki @winningfaith81
Thanks
James
> Update board_defs.py - BTT Octopus Max EZ

- docs/Config_Reference.md
module: Fixed incorrect spelling in Config_Reference.md
changed spelling of "remo" to "remove", assuming it was a simple mistype and should say "remove".
Signed-off-by: Nicholas Parry <rounded-gully-5r@icloud.com>
> Fixed incorrect spelling in Config_Reference.md

- docs/CANBUS_Troubleshooting.md
Reword the section on "incrementing bytes_invalid" to hopefully be more clear on steps that need to be taken if the issue is encountered.
I did some research on the known cases of reordered canbus packets and I think we can make some simple recommendations (Linux kernel >v6.5.0 and candlelight_fw >v2.0).
This was also discussed at https://klipper.discourse.group/t/canbus-missed-scheduling-of-next-digital-out-event/21757
@meteyou - FYI there are reports that the mainsail OS images are using Linux kernels <v6.5.0 and that those installations can show the reordered canbus packet problem.
-Kevin
> Improve suggestions on bytes_invalid in CANBUS_Troubleshooting.md

- src/generic/usb_cdc.c
- src/generic/usb_cdc.h
- src/generic/usb_cdc_ep.h
- src/lpc176x/usb_cdc_ep.h
It seems the Linux kernel will consider a maximum size usb packet to be a transaction that will continue into the next usb packet.  It will thus hold on to the traffic from the first packet until it gets the next packet.  However, if the mcu has no further data to send after the first packet then the data could get delayed for an extended period of time.
To avoid this, check for transmissions that could end on a maximum sized packet and send that data in two packets instead.  This avoids this unusual corner case.
It's very rare for this exact sequence to occur (ending a series of messages on a 64 byte usb packet), which is why this has probably not been noticed before.
-Kevin
> Avoid ending a transmission with a max size usb packet

- src/stm32/Kconfig
- src/stm32/stm32f0.c
This mcu has smaller memory and may require remapping of PA11/PA12.
This was discussed at: https://klipper.discourse.group/t/trying-to-build-firmware-for-stm32f070x6/21614/
@mykepredko fyi.
-Kevin
> Add support for stm32f070x6 mcus

- klippy/extras/lis2dw.py
I was recently looking at this file to see how I might expose the temperature sensor in the LIS3DH, and noticed I left a line of dead code commented last time I worked on it. This is a trivial change to make this file prettier, because the current state was annoying me! :laughing:
> sensor_lis2dw: remove commented code and fix formatting

- src/rp2040/main.c
RP2040 is now certified to run at 200Mhz clock instead of 133Mhz (125Mhz from SDK was used).
https://github.com/raspberrypi/pico-sdk/releases/tag/2.1.1
So, if no one minds, this is an overclock to the new allowed ones.
New perf values:
`arm-none-eabi-gcc (Arch Repository) 14.2.0`
```
rp2040	  ticks
1 stepper 3  ~ 4000K
3 stepper 14 ~ 2571K
```
Which allows us to place it aside with STM32F446 on the benchmark page.
This patch has been only tested on the development board.
> RFC RP2040: set clock to 200Mhz

- src/generic/usb_canbus.c
There was a small race condition that could allow transmit "echo" frames to become briefly stalled when in USB to CAN bridge mode.  This would likely only effect some controllers - potentially the stm32 usbotg (stm32f4 and stm32h7 devices).
The PR also contains a couple of commits intended to better organize the usb_canbus.c code.
-Kevin
> Fix minor transmit stall race when in USB to CAN bridge mode

- docs/Axis_Twist_Compensation.md
There's a broken (markdown) link; and various cleanups.
> fix markup in Axis_Twist_Compensation.md

- src/stm32/Kconfig
- src/stm32/serial.c
STM32F401 has USART6 on PA12/PA11 and PC7/PC6 with alternate function mapping AF08. This can be used, for example, to connect to the Elegoo Neptune 3 without soldering to the main board or even opening the case, where PA12/PA11 are wired to a convenient RJ10 plug going to the stock screen.
See the datasheet (Page 45, Table 9. Alternate function mapping):
https://www.st.com/resource/en/datasheet/stm32f401re.pdf
See the Neptune 3's schematic:
https://github.com/TheFeralEngineer/Elegoo-Neptune-board-schematics/blob/main/ZNP%20Robin%20Nano_DW%20V21_001%20SCH_加水印pdf%20·%20version%201_230115_223844.pdf
I only tested this on my Neptune 3. It might work for other STM32s that have USART6, if there are any others, but I only added a Kconfig entry for STM32F401, since that's what I have access to …
> stm32: Add support for USART6 on STM32F401

- klippy/extras/gcode_macro.py
Sometimes, writing macros is painful because jinja does not show adequate errors.
I tried to fix it, so now template syntax errors show that manner:
```
Internal error during connect: Error loading template 'temperature_fan octopus'
line 4: {%- set tmax = tt + 1. -%} # expected name or number
```
Thanks.
---
_Errors made me implement that fix while I was working on https://github.com/Klipper3d/klipper/pull/6837 and https://github.com/Klipper3d/klipper/pull/6840_
> jinja2: Expand template syntax errors

- klippy/extras/axis_twist_compensation.py
Restores the behavior before #6739 since people seemed to rely on it, even if the math is not exact.
> axis_twist_compensation: allow compensating both axis at once

- docs/API_Server.md
- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Load_Cell.md
- docs/Overview.md
- docs/Status_Reference.md
- docs/_klipper3d/mkdocs.yml
- klippy/extras/ads1220.py
- klippy/extras/hx71x.py
- klippy/extras/load_cell.py
This PR adds the features needed to make a load cell actually work as a gram scale. This PR will let you weight filament or measure a force in grams. (no homing or probing yet!)
* Convert raw sensor `counts` to grams and make this force data available via unix socket and printer object status
* Track sensor calibration state and allow sensors to go from un-calibrated to calibrated at runtime
* Add basic GCodes for tearing and reading the load cell
* Add a guided calibration tool so users can calibrate a load cell with a known mass or measured force.
* Add diagnostic GCode to check the health and performance of the load cell and sensor
This code has been tested by several people in the community and some last minute bug fixes and changes were landed:
* The `reverse` option allows the …
> Load cell gram scale

- docs/Config_Reference.md
- klippy/extras/buttons.py
- klippy/extras/filament_motion_sensor.py
- klippy/extras/filament_switch_sensor.py
- klippy/extras/gcode_button.py
- klippy/extras/hall_filament_width_sensor.py
This change adds a `debounce_delay` option to both `filament_switch_sensor` and `gcode_button`. This allows for much longer, user controllable, debouncing. Event cycles (off->on->off) that happen during the delay will be ignored. At the end of the delay, if the state transition is singular and maintained the event fires.
This is based on a request from a user that had issues with a fickle filament switch: https://klipper.discourse.group/t/proposal-button-debounce/22212
This allows printer owners to solve issues with less than optimal physical filament switch design. It also allows for ideas like "push and hold to execute" e.g. push and hold a button for 200ms to run `M112` so we know the user **_really_** meant it. Debouncing at this sort of timescale is widely used to add polish to user …
> Debounce gcode_button and filament_switch_sensor

- src/stm32/can.c
It seems both ERRIE and LECIE must be enabled to get hardware error interrupts.  Without this, the rx_error and tx_error reports are likely to always be zero.
-Kevin
> stm32: Turn on can.c error interrupts

- docs/Config_Reference.md
- klippy/extras/adxl345.py
- klippy/extras/icm20948.py
-The accelerometer remained (by default) in accels scale 2g mode with a sampling rate of +-1125/s instead of setting the 8g and 4500 rate, since we did not switch to registers bank 2 before the 'accel config' configuration. Because of which it 'choked', and also incorrectly calculated its accels in ffreader.
I did some comparative experiments between adxl345 and Icm20948 (2g mode):
<div style="display: flex; gap: 10px;">
</div>
Measured the acceleration at idle on Icm20948:
Сomparative experiments between adxl345 and Icm20948 (8g mode) after correcting the accelerometer configuration:
<div style="display: flex; gap: 10px;">
</div>
Measured the acceleration at idle on Icm20948:
The results have returned to normal, but it still seems like the accelerometer is reached the maximum …
> Icm20948: Fix accelerometer readings, some changes

- klippy/extras/temperature_combined.py
There are 2 patches:
1. Duct tape fix for race conditions with temperature combined sensor and other sensors during klippy initialization, where sensors can return 0. This may be by design, but it currently limits the minimum possible deviation between sensors.  Like there, it is adc + i2c: ![image](https://github.com/user-attachments/assets/1fa25fd9-1d7b-4822-be67-756d7db45e7d)
2. Temperature combined allows us to set "any" object in the sensor list, but with tmc2240, there is a corner case, it has a method `get_status()` and `temperature` field, but it has no value. So, it will crash Klippy cause max/min can't handle `None`. 
---
Should close: https://github.com/Klipper3d/klipper/pull/6675
> Temperature combined: handle temp monitors and I2C sensors

- klippy/extras/axis_twist_compensation.py
axis_twist_compensation on klippy:connect state checks for the presence of the 'probe' object, but if it is missing, it causes an error in the 'PrinterConfig' object, which does not have such an attribute.
> axis_twist_compensation: Fix AttributeError on klippy connect state

- docs/G-Codes.md
- klippy/extras/force_move.py
PR #6262 added support for clearing the homing state in SET_KINEMATIC_POSITION commands.  However, it can be difficult to use that support as the default for SET_KINEMATIC_POSITION is to set all axes as homed.
Add a new SET_HOMED parameter to allow one to explicitly request which axes to consider in a homed state.  So, for example, one can issue `SET_KINEMATIC_POSITION SET_HOMED= CLEAR_HOMED=Z` to just clear the Z homing state (and not set the X and Y homing state).
This also introduces a CLEAR_HOMED parameter and the documentation is updated to prefer that to the existing CLEAR parameter.
Finally, the documentation in G-Codes.md has been expanded to give more clarity on how the command operates.
-Kevin
> Support a SET_HOMED parameter to SET_KINEMATIC_POSITION

- scripts/ci-build.sh
- scripts/ci-install.sh
The PRU compile is time intensive and error prone - avoid it by using the prebuilt binaries.
-Kevin
> Use prebuilt pru gcc binaries during github build checks

- klippy/extras/lis2dw.py
- src/rp2040/spi.c
- src/spi_software.c
- src/stm32/stm32h7_spi.c
For some unknown reason, LIS2DW refuses to work if the time between the SCK polarity change and CS goes down is too short.
This problem is at least specific to RP2040 + LIS2DW boards, like: Fly SHT36v3, BTT LIS2DW.
The problem worsens if there are other devices on the bus with different SCK polarity, ex. MAX31865.
Possible workarounds and outcomes:
- Double reading of chip_id. It hides the issue if the second read arrives fast enough.
- Disable the I2C mode support if it is connected by SPI. Does not help.
- MAX31865 actually has support for mode 3. So, simply switching it on, makes everything work.
It seems that introducing a delay between the SCK polarity change and the CS toggle fixes the issue.
Because this problem happens if the time is too short, it is only implemented for RP2040 …
> LIS2DW: make it work when spi bus polarity is switching

- klippy/extras/resonance_tester.py
After the: f8da8099d5e5cdec
The cmd_M204 was migrated to a helper class. I'm not sure how to get it or why there is a G-code command translation.
So, this is just a fast fix that I can come up with.
```
TEST_RESONANCES AXIS=x
```
```
Disabled [input_shaper] for resonance testing
Internal error on command:"TEST_RESONANCES"
File "/home/user/klipper/klippy/gcode.py", line 212, in _process_commands
handler(gcmd)
~~~~~~~^^^^^^
File "/home/user/klipper/klippy/gcode.py", line 140, in <lambda>
func = lambda params: origfunc(self._get_extended_params(params))
~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/klipper/klippy/extras/resonance_tester.py", line 337, in cmd_TEST_RESONANCES
data = self._run_test(
~~~~~~~~~~~~~~^
gcmd, [axis], helper, …
```
> resonance_tester: replace missing M204 call

- klippy/extras/bme280.py
- klippy/extras/bus.py
- klippy/extras/sht3x.py
When `i2c_writes` would start to return the NACK status, it would become blocking and would wait for the response.
That could affect callers.
Make the migration preliminary.
From my brief recheck of callers, it seems to me that most of them do not care about actual timing or write blocking.
The only possible exceptions are:
- PCA9632, which could notice small lags of LED status updates (it does support auto increment register write)
- Maybe the SX1509. Because of the update of the PWM pin, the code path would be blocked. If there is a high frequency of changes, the next one could probably be late. (It also supports the auto increment, btw).
Thanks.
---
Depends on: #7012
Child of: #7013
> Make I2c writes synchronous

- docs/Config_Changes.md
- klippy/extras/shaper_defs.py
This pull requests updates the definitions of EI, 2HUMP_EI, and 3HUMP_EI input shapers to their canonical variants. These variants typically offer somewhat better shaper performance (stronger reduction of the vibrations) at the ends of the interval where they reduce vibrations, and that interval itself is typically larger for the same shaper duration. All this means that the new shaper definitions typically offer better vibration reduction and higher attainable accelerations. The improvements are not very significant, but are still typically quite noticeable:
|Old version|New version|
|:-----:|:------:|
| <img width="800" height="600" alt="y_ei_old" src="https://github.com/user-attachments/assets/07c2338f-2ab9-40d3-9d98-8e701c330f31" />| <img width="800" height="600" alt="y_ei_new" …
> input_shaper: Updated definitions of *EI input shapers

- klippy/toolhead.py
The current lookahead calculation code has a complicated system for managing an internal `delayed` queue.  Replace that with an explicit second pass through the pending move queue.
This is only intended to make the code a little easier to understand.  There should be no user visible changes.
@dmbutyugin - fyi.
-Kevin
> toolhead: Simplify LookAheadQueue.flush() code

- klippy/klippy.py
- klippy/util.py
It looks like there is less respect for the `/proc/cpuinfo` in recent days.
So, in the log, there would often be: `CPU: 4 core ?`
This is somewhat limiting in a sense to get an idea what we are working with.
From my point of view, the current code prints it, to give people who are reading the log,
the idea of what sort of hardware Klippy is running on.
From my sparse check of some SBCs in different chats, it seems `cpuinfo` lacks of any info.
Even on the Rasbian on Raspberry PI 5 (which I would expect to have good compliance and support):
```
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x4
CPU part        : 0xd0b …
```
> klippy: track the device model

- klippy/klippy.py
- klippy/util.py
It's useful to have the OS Kernel version reported in the log - in particular when diagnosing issues with canbus.
@nefelim4ag - fyi.
-Kevin
> Report OS version in log

- docs/Config_Changes.md
- klippy/mcu.py
- klippy/stepper.py
The main `MCU` class has grown to be very complex.  This PR splits up its functionality into multiple internal "helper" classes - one each for stats, initial configuration tracking, low-level connection handling, and restart handling.  The goal is to make it easier to maintain this logic.
There shouldn't be any user facing changes with this PR.
-Kevin
> Split internal mcu class into multiple helper classes

- klippy/chelper/kin_shaper.c
The commit caf7accf2d7b4d3c810bbb16f4ff7d4be80b043c broke shaper initialization for hybrid_corexy and other complex generic_cartesian kinematics with dual_carriage. This PR fixes the bug. An owner of a such hybrid_corexy confirmed that the fix is working as expected.
> input_shaper: Fixed initialization for dual_carriage

- klippy/extras/bus.py
- klippy/extras/pca9533.py
- klippy/extras/pca9632.py
- klippy/extras/sx1509.py
Currently, the LEDHelper() and GCodeRequestQueue() helper classes require that their callbacks do not block.  As a result, the pca9533, pca9632, and sx1509 devices need to use non-blocking i2c write calls.
@nefelim4ag - I noticed this while reviewing the flushing logic.  Basically, `toolhead.register_lookahead_callback()` and `motion_queuing.register_fush_callback()` are both expecting that the callbacks wont pause in the reactor - if a callback did, it could delay flushing and/or lead to situations where the flushing code gets called reentrant.
It's possible we could fix this another way - for example, the LEDHelper code could launch a new reactor task to handle updates.  Handling the flush callbacks is a little more tricky though.
Not sure if this would alter the plan for improving i2c …
> Additional devices require i2c_write_noack()
