Klipper3d/klipper

config/example-extras.cfg
klippy/extras/temperature_fan.py
klippy/heater.py

I think @w1ebr has something equivalent to merge so perhaps preference should be given to him, but here's my code anyway. Seems to work, though I can't say I've tested it very thoroughly.
Signed-off-by: Michael Barbour <barbour.michael.0@gmail.com>

Add support for temperature-triggered fan.

---

klippy/extras/display.py

Record M73 progress, display on ST7920 LCD, as well as linear estimate for time remaining.

Support M73-indicated progress as an extra

---

klippy/mcu.py

mcu: config_reset_cmd typo fixed

---

klippy/gcode.py

Signed-off-by: cruwaller <cruwaller@gmail.com>

gcode: mux command is already registered error print fixed

---

klippy/extras/temperature_fan.py

Signed-off-by Douglas Hammond  <wizhippo@gmail.com>

Fix issue 403 use max_speed

---

scripts/install-centos.sh

There's a few minor differences in the install script for CentOS, which I've included. I can't seem to find the right package names for any of the packages used in the ARM firmware compilers, so that's currently just commented out.
Tested on Centos 7

Add installation script for CentOS

---

docs/stm32f1.md

stm32f1: add port documentation

---

klippy/extras/display/uc1701.py

Fixes my oversight in not using SPI's built in CS pin.  Also increases SPI speed to 10mhz.

display: uc1701 spi fix

---

klippy/extras/display/display.py

Right justify fan speed and feed rate, keep progress centered.

display: fix for 128 x 64 pixel displays

---

klippy/extras/buttons.py

More details in https://github.com/brianlow/Rotary

Improve buttons RotaryEncoder by using Ben Buxton state machine.

---

klippy/gcode.py

gcode: M117 fix

---

config/printer-creality-ender3-2018.cfg

- now that menus are a thing, here's the pins to be able to use them.
Signed-off-by: Gonzalo Ramírez <controla@gmail.com>

config: Added pins for LCD encoder and button click on Creality Ender 3

---

klippy/extras/bed_mesh.py

bed_mesh: Cache last position when get_position() is called.

---

config/example-extras.cfg
klippy/extras/gantry_level.py
klippy/extras/quad_gantry_level.py

module: QUAD_GANTRY_LEVEL
Adds gantry level routine that conforms a moving gantry to the stationary bed plane. Corrects both tilt and twist using simplified representation of ruled hyperbolic parabola to calculate individual Z actuator corrections.
Requires 4 Z motors.
Signed-off-by: Maks Zolin - mzolin@vorondesign.com

Add gantry leveling (ruled hyperbolic parabola correction)

---

klippy/extras/quad_gantry_level.py

Signed-off-by: Maks Zolin <mzolin@vorondesign.com>

quad_gantry_level: Fix typo, add floating point error protection

---

config/printer-creality-cr10mini-2017.cfg

Signed-off-by: Nikolai Ugelvik <nikolaiu@gmail.com>

config: Add encoder and click pins for CR-10 mini

---

klippy/extras/bed_mesh.py

After BED_MESH_CALIBRATE has been executed the mesh state will be saved to a default profile.  The default profile will be updated each time a new calibration has been completed, however no changes are made to printer.cfg until a SAVE_CONFIG gcode has been applied.  If a default profile exists in printer.cfg, it will be loaded at startup.
BED_MESH_PROFILE may be used to load the default profile, however it cannot be used to overwrite or remove it.

bed_mesh: save mesh state to 'default' profile after calibration

---

klippy/extras/display/icons.py

Just noticed that lower blade was missing one pixel. And copyright string now contains my contacts.

Corrected Fan icon graphics

---

config/printer-anycubic-kossel-2016.cfg
config/printer-anycubic-kossel-plus-2017.cfg

Signed-off-by: Peter Ruevski <dpr@ruevs.com>

config: Make the Anycubic delta configurations as similar as possible

---

config/printer-creality-cr20-2018.cfg

Tested this configuration with my printer and successfully completed a test print with good results.
I couldn't get the LCD to work yet, but other than that the printer seems to be completely functional.

Add printer config for the CR-20 by Creality3D

---

config/printer-creality-cr20-2018.cfg

config: Fix CR-20 click pin polarity

---

klippy/extras/tmc2208.py
klippy/extras/tmc2660.py

unresolved references fixed in TMC2208 and TMC2660.

unresolved references in tmc drivers

---

config/generic-radds.cfg

Signed-off-by: Graham Ambrose <graham.ambrose@gmail.com>

config: Added encoder pins to radds example config

---

klippy/extras/display/menu.cfg

Signed-off-by: Paulo Drugos paulodrugos@gmail.com

Display: Correction in the resume print option, it was not showing when the print is paused

---

klippy/extras/z_tilt.py

z_tilt: unresolved reference fixed

---

docs/FAQ.md

module: FAQ
Added an answer about detecting lost steps (#1220)
Signed-off-by: christian mock <cm@tahina.priv.at>

FAQ: added an answer about detecting lost steps

---

klippy/extras/probe.py

"PROBE_ACCURACY" Set z min value in to z_offset.
Signed-off by: Rui Caridade ([rui.mcbc@gmail.com](mailto:rui.mcbc@gmail.com))

PROBE_ACCURACY: Set z min value to z_offset.

---

config/example-extras.cfg
klippy/extras/verify_heater.py

This series implements some tweaks to the default heater verification checks.  This should reduce the amount of "false positive" errors during heatup.
-Kevin

Minor improvements to verify_heater

---

klippy/extras/quad_gantry_level.py

Signed-off-by: Maks Zolin <mzolin@vorondesign.com>

Fixing Quad Gantry logic to use probed Z values correctly

---

klippy/extras/tmc2660.py

This PR automates the computation of VSENSE in the same way as it is done for the tmc2130 and tmc2208. 
I further fixed some overlong lines, removed the CS restriction from SET_TMC_FIELD (also to align with the other driver implementations).
Finally, When I converted the code from my own register access to the tmc2130's helper functions, I screwed up the HEND default. It is in line with what it used to be now.

tmc2660: Automate VSENSE computation

---

src/stm32f0/i2c.c

stm32fo/i2c.c: minor bugfix

---

src/stm32f0/gpio.c

Signed-off-by: Eugene Krashtan <eug.krashtan@gmail.com>

Wrong port definition for GPIOF

---

config/example-extras.cfg
klippy/extras/display/display.py
klippy/extras/display/uc1701.py

Add ST7567 display support

---

klippy/extras/temperature_fan.py

module: TEMPERATURE_FAN.PY
I added a gcode command for setting the target temperature of temperature_fan.
Example gcode: SET_TEMPERATURE_FAN_TARGET temperature_fan=chamber target=35.0
Signed-off-by: Martin Nowroth madnoth@gmail.com

Add gcode command for temperature_fan.py

---

config/example-extras.cfg
klippy/extras/tmc5160.py

Thanks for all the helpers. @FHeilmann @mattthebaker @KevinOConnor @teemuatlut

Adding support for TMC5160 steppers, provided by Watterott

---

klippy/extras/endstop_phase.py
klippy/extras/tmc.py
klippy/mcu.py
klippy/stepper.py

I think this should fix the issue reported in #1585.  It also enables endstop_phase support on the tmc5160.
-Kevin

Fixes for endstop phases

---

config/generic-bigtreetech-skr-mini-e3.cfg

As per https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/commit/18e67720106962a8a49930e9ff5e65a34687baec

Lower driver voltage

---

klippy/extras/controller_fan.py

This PR updates my controller_fan-module and applies some Python conventions as well as some readability improvements. It should still work as expected.
Signed-off-by: Nils Friedchen <Nils.Friedchen@googlemail.com>

controller_fan refactoring

---

config/example-extras.cfg

This PR fixes the grammar for the newly added arc configuration.

Fix grammar and typos for the new arc config

---

klippy/extras/gcode_arcs.py

This PR removes the unused variables from the arcs code.

Remove unused variables

---

klippy/extras/z_tilt.py

z-tilt: Unresolved symbol fixed

---

docs/G-Codes.md
docs/Sensorless_Homing.md

Changes to Documentation to also include the new TMCs like the 2209.
Signed-off-by: Nils Schulte git@nilsschulte.de

doc update with new TMCs

---

klippy/extras/temperature_fan.py

Add status reporting for template usage.  Resolves #2089.

temperature_fan: add get_status() function

---

config/printer-lulzbot-taz6-dual-v3-2017.cfg

module: LULZBOT TAZ6 DUAL V3 CONFIG FILE SUPPORT
Detailed config file for supporting all features of Lulzbot TAZ6 with dual v3 toolhead.
Signed-off-by: Ryan Densberger <magshooterz@gmail.com>

Lulzbot TAZ6 w/ Dual v3 Toolhead Config

---

config/printer-creality-cr20-pro-2019.cfg

I just got started with Klipper on my Creality CR20 Pro. It's a delight! The only tricky thing for me was getting the BLtouch pins right. Therefore, I'd like to share my config.
This is my first pull request; thank you for any feedback.

Added config for Creality CR-20 Pro

---

klippy/klippy.py
klippy/mcu.py

This should hopefully fix #1013.
@vladbabii - fyi
-Kevin

Fix for multi-mcu FIRMWARE_RESTART bug

---

klippy/msgproto.py

msgproto: unresolved symbol fixed

---

config/example.cfg
docs/Config_Changes.md
docs/G-Codes.md
docs/Pressure_Advance.md
klippy/chelper/__init__.py
klippy/chelper/itersolve.c
klippy/chelper/itersolve.h
klippy/chelper/kin_extruder.c
klippy/chelper/trapq.c
klippy/chelper/trapq.h
klippy/extras/bltouch.py
klippy/extras/force_move.py
klippy/extras/manual_probe.py
klippy/extras/z_tilt.py
klippy/homing.py
klippy/kinematics/cartesian.py
klippy/kinematics/extruder.py
klippy/toolhead.py

This PR significantly changes the internals of pressure advance in the hope that it will make it more flexible and scalable.  It also adds support for the extruder to make "instantaneous velocity" changes during cornering between moves.  This allows Klipper to perform lookahead between moves with different extrusion ratios.
The code is still a "work in progress".  The main goal at this point is to enable testing and to "prove the concept".  To test with this new code, run:
cd ~/klipper ; git fetch ; git checkout origin/work-smoothpa-20190920 ; sudo service klipper restart
It may be necessary to recalibrate pressure advance.  See the [updated guide on the new branch](https://github.com/KevinOConnor/klipper/blob/work-smoothpa-20190920/docs/Pressure_Advance.md).  This guide also introduces a …

Smoothed pressure advance and extruder cornering support

---

config/example-extras.cfg
klippy/extras/display/display.py
klippy/extras/display/uc1701.py

uc1701: add config option for sh1106 type with up to 132 columns.

---

config/printer-wanhao-duplicator-i3-mini-2017.cfg

Thought this might be useful to people getting started with Klipper on a Wanhao Duplicator i3 Mini

Config: Basic config for Wanhao Duplicator i3 mini

---

klippy/extras/tmc5160.py

tmc5160: PWMCONF is write only

---

config/generic-printrboard.cfg

Verified to work on my printrboard.

Flash instructions for printrboard

---

docs/beaglebone.md
scripts/install-beaglebone.sh
scripts/install-debian.sh
scripts/klipper-pru-start.sh

Updates BBB/Replicape install scripts as it is known BBB kernels have a habit of breaking pru,s 
This update works with 4.14.108-ti kernel unfortunately the 4.19 kernels are broken and I don't know why.
This may help the redeem community changing to klipper.
First pull request so excuse me If I get it wrong
Signed-off-by: Trevor Wilson altocoey@hotmail.com

Replicape pru update start scripts

---

klippy/extras/gcode_arcs.py

gcode_arcs: use correct current position from gcode

---

config/generic-bigtreetech-skr-pro.cfg

#2389 
signed of Martin Malmqvist hywelmartin@gmail.com

as suggested in #2389

---

config/printer-monoprice-mini-delta-2017.cfg

LCD support is going to require a separate PR, but this should get the MPMD community playing with Klipper!

Adding a config file for the monoprice mini delta

---

klippy/extras/bme280.py

This fixes an issue where an unhandled i2c timeout exception propagates back to the reactor, killing the dispatch loop.
Specifically, this could be reproduced by issuing an M112 gcode.  The result is the inability to communicate with the host until the service is restarted.

bme280:  handle read timeout exceptions inside the timer

---

klippy/extras/bltouch.py
klippy/extras/endstop_phase.py
klippy/extras/homing_heaters.py
klippy/extras/manual_stepper.py
klippy/extras/probe.py
klippy/extras/tmc.py
klippy/gcode.py
klippy/homing.py
klippy/mcu.py

This series of changes is intended to simplify Klipper's internal interface to homing.  There should be no external user visible changes.  It is part of the discussion on PR #2493 .
@FanDjango - FYI.
-Kevin

Simplify homing notification callbacks

---

klippy/extras/filament_switch_sensor.py

Hi @Arksine - I noticed a couple of minor things in the filament_switch_sensor.py code while reviewing #2518 and #2505.  I don't have a good way of testing these, but figured I'd point them out.  If you don't think any of these patches are worthwhile then we wont go forward with them.
-Kevin

Minor changes to filament_switch_sensor

---

config/example-extras.cfg
docs/HallFilamentWidthSensor.md
klippy/extras/hall_filament_width_sensor.py

module: hall_filament_width_sensor
added virtual runout sensor

hall_filament_width_sensor, added virtual runout sensor

---

config/sample-mmu2s-diy.cfg

This is the configuration file for the MMU2S DIY multi-material 
More info on how to build it on : https://www.thingiverse.com/thing:3910546
I now use it since some month, and with the last update of klipper, it now works without special patch
Have fun ;)
Signed-off-by: Jeremy Briffaut <kakou@kakou.org>

Configuration file for MMU2S DIY

---

config/example-extras.cfg
klippy/extras/display/__init__.py
klippy/extras/display/display.py

Add multi-display support to #2581.

display:  Add support for multiple displays

---

klippy/extras/tmc5160.py

The tmc5160 has the ability to fine tune the current selection using the "GLOBALSCALER" register.  If I understand it correctly, tuning stepper current via GLOBALSCALER has the ability to select low currents without adversely impacting the tmc5160s ability to implement micro-stepping.
I have no way to test this change.  If interested, please test and report your results here (success or failure).
`cd ~/klipper ; git fetch ; git checkout origin/work-tmc5160-20200218 ; sudo service klipper restart`
-Kevin

Support setting GLOBALSCALER on tmc5160 to fine tune current selection

---

docs/G-Codes.md

See issue #2492 
Signed-off-by: Garth Snyder <garth@garthsnyder.com>

module: docs, clarify behavior of M204 with only one of P or T

---

klippy/extras/manual_stepper.py

Signed-off-by: Jeremy Briffaut <kakou@kakou.org>

TMC2209 sensorless endstop for manual_stepper

---

docs/G-Codes.md

Clarify that Probe_Calibrate uses the speed variable for XY as well
Signed Off: Dushyant Ahuja <dusht.ahuja@gmail.com>

Clarify that Probe_Calibrate uses the speed variable for XY as well

---

src/stm32/i2c.c

This implementation is a compromise of "method 1" outlined in the STM32F1 reference manual (RM0041, Page 579), where critical sections are protected by disabling IRQs.  Method 2 is indicated for polling, however it seems unnecessary and overly complex with code paths for 1, 2 and 3+ bytes read.
Tested working on both the STM32F1 (BTT SKR Mini E3) and STM32F4 (SKR Pro).

stm32: add support for i2c read

---

scripts/avrsim.py

Signed-off-by: Georgios Karnas <kargeor@gmail.com>

update avrsim pty attr

---

klippy/extras/bed_mesh.py

Signed-off-by: Nate Plamondon <nplamondon@gmail.com>

bed_mesh.py: Fix typo

---

klippy/extras/z_tilt.py

- fix bug in error comparison resulting in extra retries. 
- issue status before increasing errors message.

Z_tilt Retries fixups

---

klippy/extras/hall_filament_width_sensor.py

module: hall_filament_width_sensor
Increasing measure stability

Increasing measure stability

---

klippy/extras/hall_filament_width_sensor.py

module: hall_filament_width_sensor
Increasing measure stability

fix  overflow  issue on 12 bit adc

---

config/example-extras.cfg
klippy/extras/controller_fan.py

This gives it parity with heater_fan.  Also change the default speed from
max_power to 1.0, since it is already scaled by max_power in set_speed.

controller_fan: Add fan_speed parameter.

---

scripts/install-arch.sh

Automate installation for Arch Linux based systems

scripts: add arch linux installation

---

config/example-extras.cfg
docs/G-Codes.md
klippy/extras/extruder_stepper.py

Add support for syncing to active extruder and changing synced extruder via extended gcode
Signed-off-by: Christopher Meredith <chmeredith@gmail.com>

extruder_stepper: Support changing synced extruder on the fly

---

Makefile

Signed-off-by: Boleslaw Ciesielski <combolek@users.noreply.github.com>

Makefile: fixed missing dependency on autoconf.h

---

klippy/extras/display/menu.py
klippy/extras/display/menu_keys.py

This is an internal update to the menu code - it should have no user visible changes.  It separates out the low-level button handling to a new source code file.
@mcmatrix - fyi.
-Kevin

Separate out menu key handling to new menu_keys.py file

---

config/example-extras.cfg
docs/HallFilamentWidthSensor.md
klippy/extras/hall_filament_width_sensor.py

module: hall_filament_width_sensor
added width logging

Added width logging

---

config/example-extras.cfg
klippy/extras/heaters.py
klippy/extras/lm75.py

Signed-off-by: Boleslaw Ciesielski <combolek@users.noreply.github.com>

sensors: Added support for LM75/LM75A I2C connected temperature sensors

---

scripts/graph_motion.py
scripts/graph_shaper.py

A couple of scripts that may be useful to simulate input shaper responses at different frequencies
and estimate their positional errors as well as how much they reduce vibrations.

input_shaper: scripts to simulate shaper response and toolhead movement

---

klippy/extras/filament_switch_sensor.py
klippy/extras/temperature_sensor.py
klippy/toolhead.py

This reports the following additional information via calls `get_status`:
- toolhead: `max_velocity`, `max_accel`, `max_accel_to_decel`, `square_corner_velocity`
- filament_switch_sensor:  `enabled`
- temperature_sensor:  ` measured_min_temp`, `measured_max_temp`

Report additional information via get_status

---

docs/FAQ.md

I wanted to know how to uninstall and came across https://github.com/KevinOConnor/klipper/issues/1084 . Thought it would be good to add the comments from there to the `FAQ.md`. Please let me know if there are issues with where it's placed or the prose.

docs: add uninstall notes to faq

---

klippy/gcode.py
klippy/klippy.py
klippy/webhooks.py

This is an change to some of the low-level gcode and webhook internal processing.  The goal is to make it easier for the webhooks module to capture the gcode command output.  This is the result of discussion in PR #3149 .
@Arksine - FYI.  I also went ahead and split out the low-level gcode IO handling form the gcode command dispatch.
-Kevin

Minor gcode & webhooks rework

---

klippy/extras/hall_filament_width_sensor.py

Fix for issue #3181 `hall_filament_width_sensor.py` attribute error in `get_status` method.

hall_filament_width_sensor: fix error

---

klippy/extras/display/display.py
klippy/extras/display/menu.py

@mcmatrix - FYI, this change should allow the menu code to redraw less while still responding quickly to keyboard events.  I mentioned it earlier at: https://github.com/KevinOConnor/klipper/issues/3176#issuecomment-675006459
-Kevin

Support requesting a screen redraw on a menu key press

---

klippy/extras/display/menu.py

Improve menu rendering so that it'll only render visible (on-screen) items.
It will also encapsulate list rendering inside the menu element.

Only render visible menu list items

---

klippy/chelper/kin_shaper.c

@dmbutyugin - FYI, I made a couple of changes to kin_shaper.c that made the code a little easier to understand for me.  Mostly minor code movement and data movement.
I also added in the fix for corexz.
Thoughts?
-Kevin

Minor code changes to kin_shaper.c

---

klippy/extras/quad_gantry_level.py

This was an old branch I had where I added some comments to help me understand how quad_gantry_level works.  It's just comments and some variable renames - no code changes.  I figured I'd post it in case it is useful to others.
@VoronDesign , @fessyfoo - FYI.
-Kevin

Add additional comments on how leveling works in quad_gantry_level

---

config/printer-tronxy-x5sa-v6-2019.cfg

configs/tronxy-x5sa: fixed update file extension

---

klippy/configfile.py

This allows connected clients to prompt the user when the configuration is modified internally.

configfile:  report "config_changed" via get_status

---

klippy/toolhead.py

toolhead: Fixed reporting of the kinematic limits

---

docs/API_Server.md
docs/Overview.md

As part of the upcoming release I wanted to add some documentation on Klipper's new "webhooks" api interface.
@Arksine - it would be great if you could review this.
Thanks,
-Kevin

Add initial API_Server.md document

---

config/example-extras.cfg
docs/Config_Changes.md
docs/G-Codes.md
klippy/extras/dotstar.py
klippy/extras/neopixel.py
klippy/mcu.py
klippy/serialhdl.py
src/neopixel.c

Increase maximum neopixel chain length from 18 to 85.
I don't have a good way to test this on long LED chains, so please report success (or failure) here.
`cd ~/klipper ; git fetch ; git checkout origin/work-neopixel-20200928 ; sudo service klipper stop ; make ; make flash ; sudo service klipper start`
-Kevin

Add neopixel support for up to 85 LEDs in a single chain

---

klippy/chelper/itersolve.c

The existing code calculates each step time via an "exponential search" followed by a "false position with Illinois algorithm" search.  This PR replaces that algorithm with a "secant method" with "bounds checks" search.  The "[secant method](https://en.wikipedia.org/wiki/Secant_method)" by itself can sometimes make poor guesses (which leads to the possibility it may never find the correct step time), so a series of "bounds checks" are implemented to catch questionable guesses - it'll fall back to a bisection search or exponential search in this case.
There are a few advantages to this new code:
1. The code is a bit simpler.  The previous system had two separate stages (the "exponential search" and "false position search").  The new code has just a single loop to find each step time.
2. …

Convert iterative solver to use the "secant method"

---

klippy/extras/controller_fan.py

i only added the get_status function in the controller_fan.py to read speed over api (moonraker)
Signed-off-by: Stefan Dej <meteyou@gmail.com>

add get_status to controller_fan.py

---

docs/Command_Templates.md
klippy/extras/heaters.py

added the pwm value to the heater.get_status function and in the Command_Templates.md

add last pwm value to heater.get_status

---

scripts/calibrate_shaper.py
scripts/graph_accelerometer.py

scripts: Small improvements for input shaper and accelerometer scripts

---

docs/G-Codes.md
klippy/extras/heaters.py

heaters: Add MAXIMUM option to TEMPERATURE_WAIT command

---

docs/G-Codes.md
klippy/extras/heaters.py

heaters: Make MINIMUM optional for TEMPERATURE_WAIT command

---

src/stm32/Kconfig
src/stm32/adc.c
src/stm32/stm32f4.c

This PR adds support for the STM32F401 microcontrollers for an upcoming board we are developing

Support for STM32F401

---

docs/Config_Changes.md
docs/G-Codes.md
docs/Measuring_Resonances.md
klippy/extras/adxl345.py
klippy/extras/resonance_tester.py

[adxl345] Small adxl345 and resonance testing improvments

---

docs/Sensorless_Homing.md

docs: Fix typo.

---

config/generic-mks-rumba32-v1.0.cfg

module: Generic config for the MKS Rumba32
Contains sample of TMC2209 configuration and display mappings
Signed-off-by: Lars R. Hansen popshansen@hotmail.com

Generic config for the MKS Rumba32

---

config/printer-creality-ender6-2020.cfg

Corrected the offset direction, added screw levelling and fixed bed mesh limits to account for offset (this would otherwise cause an error when trying ABL)

Fix ender 6 config

---

klippy/extras/idle_timeout.py

Signed-off-by: Arjan Mels <github@mels.email>

idle_timeout: Add help to SET_IDLE_TIMEOUT

---

config/printer-flsun-q5-2020.cfg

in cooperation with chaosdrucker
Signed-off-by:  Christoph Frei <fryakatkop@gmail.com>

config: add Flsun Q5 config

---

config/printer-creality-ender5plus-2019.cfg

module: EXAMPLE CONFIGS ENDER 5 PLUS
Added filament sensor with pin I have used successfully.
Bob90 rgarford@gmail.com

Ender5Plus add filament sensor

---

.github/ISSUE_TEMPLATE/config.yml
docs/Contact.md

This is a proposal to introduce a Discourse server dedicated to Klipper.  The goal would be to use it as a "Community forum".  This is a follow up to PR #3762 - in that PR the Contact.md document was updated to point users from github to a Discord chat server.  This PR would update the Contact.md file to point users at either the new "community forum" or the "discord chat" server.
The new Discourse server is at: https://community.klipper3d.org/ .  Feel free to use that server now.  This is an experiment though - it may not work out over the long term.  The proposed Contact.md file is at: https://github.com/KevinOConnor/klipper/blob/work-contact-20210320/docs/Contact.md
My impression on the results of PR #3762 is generally positive.  I feel it has helped notably with reducing the amount of …

New Discourse server as Klipper community forum

---

klippy/extras/hall_filament_width_sensor.py

fix range check error

---

config/printer-robo3d-r2-2017.cfg

Improvements and fixes based on feedback:
* Make speeds and limits more conservative
* Fix Y endstop position
* Improve IR bed leveling
* Fix filament runout pin

config: Update printer-robo3d-r2-2017.cfg

---

klippy/extras/resonance_tester.py
klippy/extras/shaper_calibrate.py
scripts/calibrate_shaper.py
scripts/graph_accelerometer.py

resonance_tester: Fixed multi-point resonance testing

---

config/generic-bigtreetech-skr-2.cfg

module: Generic config for the BigTreeTech SKR 2 config file
Contains sample of TMC2209 configuration.
Signed-off-by: Lars R. Hansen popshansen@hotmail.com

config: Add example generic-bigtreetech-skr-2.cfg config

---

config/printer-flashforge-creator-pro-2018.cfg

Signed-off-by: Marc-André Denis marcadenis@msn.com

Config for the flashforge-creator-pro

---

docs/G-Codes.md
klippy/extras/adxl345.py

adxl345: Verify the register writes, added debug adxl345 commands

---

.gitignore
docs/Config_Reference.md
klippy/extras/probe.py

I'm used to using this param with BlTouch clone, and i implemented it for generic probe ( BfpTouch micro)
Signed-off-by: Nick Lefskiy n.lefskiy@yandex.ru

Add stow_on_each_sample param for Probe

---

src/lpc176x/i2c.c

This adds the i2c_read command to the lp176x MCU.
Signed-off-by: Michael Kurz <michi.kurz@gmail.com>

lpc176x: Add i2c_read functionality

---

klippy/extras/resonance_tester.py

resonance_tester: Refactored the testing code

---

docs/RPi_microcontroller.md

Just a small adjustment, to improve the clarity of the rPi mcu compilation instructions
Signed-off-by: Ben Eastep <shifting@shifting.ca>

docs: a slight clarity improvement for the rPi mcu

---

config/printer-twotrees-sapphire-plus-2020.cfg

config: Fix rotation_distance for Sapphire Plus

---

config/generic-fysetc-cheetah-v1.2.cfg

Added second CNC fan, PB0
Signed-off-by: Jericho Adler jericho.adler@gmail.com

Added second CNC fan to generic-fysetc-cheetah-v1.2.cfg

---

klippy/extras/firmware_retraction.py
klippy/extras/gcode_move.py
klippy/extras/pause_resume.py
klippy/extras/resonance_tester.py
klippy/extras/respond.py
klippy/gcode.py

This is necessary, that the gcodes are displayed in the HELP response and that they are forwarded to the GUIs via the API.

Update gcode descriptions

---

config/printer-tronxy-x5sa-pro-2020.cfg

Correct filament sensor behaviour by inverting filament_switch_sensor switch_pin
Signed-off-by: Morgan Barresi <morganfw@gmail.com>

Modify printer-tronxy-x5sa-pro-2020.cfg

---

docs/Measuring_Resonances.md
klippy/extras/resonance_tester.py

resonance_tester: Set max_accel ignoring the limit from the config

---

config/generic-th3d-ezboard-lite-v1.2.cfg

Signed-off-by: Clark Tomlinson <fallen013@gmail.com>

Add ezboard configuration

---

config/generic-creality-v4.2.7.cfg

Signed-off-by: James Churchill <pelrun@gmail.com>

config: Add pin aliases to generic-creality-v4.2.7.cfg

---

docs/G-Codes.md

add CANCEL_PRINT to gcode.md to solve #3895
Signed-off-by: Alex Zellner alexander.zellner@googlemail.com

docs: add CANCEL_PRINT

---

config/printer-prusa-mini-plus-2020.cfg

Signed-off-by: Matthew Lloyd <github@matthewlloyd.net>

config: Update gear_ratio for Prusa Mini+ extruder based on counting teeth

---

docs/Measuring_Resonances.md

Signed-off-by: Ben Eastep shifting@shifting.ca

docs: added an apt update to measuring_resonance

---

docs/G-Codes.md
docs/Measuring_Resonances.md
klippy/extras/resonance_tester.py

resonance_tester: Arbitrary AXIS in TEST_RESONANCES command

---

config/generic-bigtreetech-octopus.cfg
test/klippy/printers.test

Information and some lines verbatim were sourced from the official BigTreeTech Octopus
GitHub repository to make this configuration as well as existing configurations in the same
folder as this one
All commits before this pull request was opened were...
Signed-off-by: Charles Pickering <charles.pickering@live.com>

config: Create config for BigTreeTech Octopus

---

docs/RPi_microcontroller.md

This addition explains how to enable and use hardware pwm support on a Raspberry Pi using the Linux host mcu.

Add hardware PWM documentation

---

docs/G-Codes.md

Just a quick cleanup to where I flubbed the Z_OFFSET_APPLY_ENDSTOP and  Z_OFFSET_APPLY_PROBE documentation
Signed-off-by: Ben Eastep <shifting@shifting.ca>

Docs: fixed babystepping patch

---

klippy/webhooks.py

This dumps a log of of requests for each connected client when Klippy enters the shutdown state.  The dump is modeled after the gcode log for consistency.  I chose to store 20 requests in the deque, however I can easily change that if necessary.

webhooks: log client requests on shutdown

---

docs/API_Server.md
docs/Debugging.md
klippy/extras/motion_report.py
klippy/kinematics/extruder.py
klippy/stepper.py
klippy/webhooks.py
scripts/motan/analyzers.py
scripts/motan/data_logger.py
scripts/motan/motan_graph.py
scripts/motan/readlog.py

This PR is a follow up to PR #4504 - it extends the motion_report.py module to support dumping Klipper's internal motion queues over the Klipper API Server.  This PR also adds a new `data_logger.py` tool for capturing and compressing that data, along with a new `motan_graph.py` tool for performing motion analysis on the captured data.
There are some brief usage docs on the new system in the docs/Debugging.md file on this PR - https://github.com/KevinOConnor/klipper/blob/work-motan-20210801/docs/Debugging.md#motion-analysis-and-data-logging .
The support here was inspired by the `scripts/graph_motion.py` (and similar) tool.  The main advantage of this system is that it can analyze printer data from real prints.  The `data_logger.py` tool is intended to be flexible enough that it could run …

Data logging and motion analysis

---

src/lpc176x/hard_pwm.c

This fixes a PWM going to full scale output when a initial value != 0 was
given. The output was on 100% until another update occurred.
This change enables the PWM counter before setting the channel values.
This fixes #4559

lpc176x: Fix wrong inital value at PWM setup

---

klippy/toolhead.py

Returns only the current values if no new ones have been passed.
This PR is for splitting all modules from https://github.com/KevinOConnor/klipper/pull/4477

toolhead: change SET_VELOCITY_LIMIT respond behavior

---

docs/API_Server.md
docs/Config_Changes.md
docs/Debugging.md
docs/G-Codes.md
klippy/extras/adxl345.py
klippy/extras/motion_report.py
klippy/extras/resonance_tester.py
scripts/motan/analyzers.py
scripts/motan/data_logger.py
scripts/motan/motan_graph.py
scripts/motan/readlog.py
src/generic/usb_cdc.c
src/sensor_adxl345.c

This PR updates the adxl345 code to support logging of accelerometer data via the new "motion report" system.  This is based on top of PR #4555 .
The main advantages of this support are:
1. The new data logging should scale to very large captures.  It should be possible to capture data from real prints and to build captures lasting many hours.
2. The data log includes other useful information on Klipper's motion (such as requested movement).
This change does require a recompile of the micro-controller.  New timing messages were added to the micro-controller code so that the host software can calculate accurate accelerometer timestamps.  Previously, the code would calculate timestamps at the end of a capture.  The new code queries the buffer/fifo state every 100ms and reconstructs …

Update adxl345 to use new motion reporting system

---

klippy/toolhead.py

fixed the issue from PR https://github.com/KevinOConnor/klipper/pull/4615
Returns only the current values if no new ones have been passed.

toolhead: change SET_VELOCITY_LIMIT respond (fixed)

---

config/generic-mellow-super-infinty-hv.cfg

This adds a reference configuration file for the Mellow Super 8 High-Voltage board.

config: Added the Mellow Super Infinity HV board

---

config/printer-eryone-thinker-series-v2-2020.cfg
test/klippy/printers.test

Sorry about the first 2 commits descriptions, it's what I had to do to fix my fork...hopefully this make it easier to merge in.

Minor Eryone Thinker S config fixes.

---

config/generic-duet3-mini.cfg

Signed-off-by: Joao Barros <joao.barros@gmail.com>

config: Fix LCDBeep pin on generic-duet3-mini.cfg

---

scripts/spi_flash/spi_flash.py

Update config response string to match new version from d4aee4f.

spi_flash: Fix MCU handshake protocol

---

scripts/spi_flash/spi_flash.py

Support a set of known past config responses. This is just a more graceful follow-up to 76bfc32, which will support forward and backward MCU compatibility (I manually tested rolling forward and rolling back).
@Arksine, I'd really appreciate your thoughts on this.

spi_flash: Better fallback on MCU protocol change

---

config/sample-bigtreetech-hermit-crab-canbus.cfg

config: Add HermitCrab board

---

docs/FAQ.md

Signed-off-by: Yifei Ding <yifeiding@protonmail.com>

docs: Update raspberrypi.com Links in FAQ

---

config/generic-bigtreetech-skr-mini-e3-v3.0.cfg

config: Add BigTreeTech SKR mini E3 V3.0 board

---

docs/Bed_Level.md

Thickness is not width.
Signed-off-by: Yifei Ding <yifeiding@protonmail.com>

docs: Clarify the Thickness of Paper

---

config/generic-bigtreetech-skr-pico-v1.0.cfg

config: Add BigTreeTech SKR Pico V1.0 board

---

klippy/toolhead.py

This fixes issue #5050
Signed-off-by: Stephen Hurd <deuce@synchro.net>

toolhead: Fix toolhead stop on SET_VELOCITY_LIMIT

---

docs/CANBUS.md
docs/Command_Templates.md
docs/Config_Reference.md
docs/Config_checks.md
docs/FAQ.md
docs/Hall_Filament_Width_Sensor.md
docs/Measuring_Resonances.md
docs/RPi_microcontroller.md

Signed-off-by: Yifei Ding<yifeiding@protonmail.com

docs: Cumulative Fix

---

docs/Debugging.md

docs: Updated simulavr building instructions

---

docs/Manual_Level.md

Just a small commit fixing a tiny typo i noticed

Manual_Level.md: Fix typo. read to rear

---

docs/_klipper3d/fetch-translations.sh

Signed-off-by: Yifei Ding<yifeiding@protonmail.com>

docs: Fix Translation Support Script

---

scripts/check_whitespace.py

Modified strings used in pattern matching to b-strings as are expected
with python3.
Signed-off-by: Miklos Tusz <miklos@aon3d.com>

scripts: Migrate `check_whitespace.py` to python3

---

scripts/spi_flash/spi_flash.py

This patch adds support for the latest `spi_config` command, while retaining support for the previous version.
While the patch worked as expected in my testing, there was a peculiar behavior that I noticed.  If Klipper (or `spi_flash`) attempts to configure the MCU with the incorrect spi command, the board requires a power cycle to flash correctly with `spi_flash`.  As long as this condition does not occur I can freely flash between older and newer versions of Klipper.
This may be an issue with the bootloader for the SKR Mini E3 v1.2, I plan to test some other boards to see if I can reproduce.  I don't believe that this was introduced with this change or by 77937846402f011c4c49a97027606902acea7a12.

spi_flash: support spi protocol changes

---

docs/G-Codes.md

Closes #4980 
Signed-off-by: Kevin Nguyen <ngynkvn@gmail.com>

docs: Add documentation on MAX_DEVIATION parameter

---

config/generic-bigtreetech-skr-3.cfg
config/sample-bigtreetech-ebb-canbus-v1.0.cfg
config/sample-bigtreetech-ebb-canbus-v1.1.cfg

config: Add BTT SKR 3 & EBB CAN V1.0 & V1.1 board cfg

---

docs/Exclude_Object.md

Signed-off-by: Stefan Dej <meteyou@gmail.com>

docs: fix typo in Exclude_Object.md

---

docs/_klipper3d/build-translations.sh

Signed-off-by: Yifei Ding<yifeiding@protonmail.com>

mkdocs: Replace TOC in Translations

---

klippy/extras/bed_mesh.py

Cache the mesh status dict, only updating it when a mesh is loaded, cleared, or if there is a profile change.  This should resolve #5580.

bed_mesh: cache mesh status

---

scripts/spi_flash/board_defs.py

sd update tested and working mks_monster8
Signed-off-by Andreas Fröhlke boandy1985@googlemail.com

spi_flash_add mks_monster8,robin_v3

---

docs/Measuring_Resonances.md
docs/RPi_microcontroller.md

docs: Updated accelerometer instructions

---

docs/Config_Reference.md
docs/G-Codes.md
klippy/extras/respond.py

#4737 with the requested changes after close.
Should be fine now.
Signed-off-by: Adrian Joachim adi.joachim12@gmail.com

Respond: No forced spaces

---

docs/Status_Reference.md
klippy/extras/extruder_stepper.py
klippy/kinematics/extruder.py

Also added status report for extruder_stepper objects with the
current pressure advance parameters values.

extruder_stepper: Support configuring pressure advance from config

---

src/stm32/stm32f0_i2c.c

stm32f0: implement i2c_read endpoint

---

src/atsamd/i2c.c

samd21: fix erroneous register bit reference.

---

config/generic-bigtreetech-manta-m4p.cfg
config/generic-bigtreetech-manta-m8p.cfg

config: Add BigTreeTech Manta M4P & M8P board

---

src/stm32/fdcan.c

In porting the fdcan code to the atsame51 chips, I noticed a few areas where the stm32 fdcan.c code could be simplified.
@bigtreetech - fyi.
-Kevin

Minor rework to stm32 fdcan code

---

scripts/spi_flash/board_defs.py

it seems I made an error with my code for the SKR 3, and I copied the code from the wrong host , this PR fixes that. I have just retested with the right code and works as expected, this is confirmed by @adelyser who brought the issue to my attention.

board_defs.py Update to fix SKR-3 config

---

klippy/toolhead.py

If a maximum acceleration is changed between two consecutive moves, this allows to correctly compute the junction velocity between them.

toolhead: Capture current junction_deviation in a Move class

---

src/stm32/stm32h7_adc.c

Improve handling of race conditions with hardware updates.  This is the same changes applied to stm32f0_adc.c in commit 88325b6c.
This is an alternate implementation of PR #5911 .
@adelyser , @mattthebaker , @D4SK - fyi.
-Kevin

Apply race fixes to stm32h7_adc.c

---

src/stm32/Kconfig
src/stm32/stm32f0_serial.c
src/stm32/stm32f0_timer.c
src/stm32/stm32g0.c

stm32g0: add stm32g0b0 support

---

klippy/extras/manual_probe.py

Current Z_OFFSET_APPLY_ENDSTOP command only works for printers with cartesian architecture which have separate Z axis defined. But this functionality (persisting Z babystep value to endstops) is exactly as convinient for delta printers, therefore this PR implements it.

Add delta implementation of Z_OFFSET_APPLY_ENDSTOP

---

klippy/kinematics/delta.py

Existing code uses very restrictive build volume constraint checking with just narrow cone on top of fully cylinder for delta printers.
Code here implements more permissive and still safe build volume constraint checks.
To avoid calling expensive math.sqrt function in check_move method linear interpolation is used instead.
Tested on our small SpaceDelta3D printer which has radius of ~113mm, arm length of 240.7mm and build radius of 103mm.
Limit Z height at the edge of the build radius is a bit above 181mm (slightly improved over current klipper Implementation, since it takes build radius smaller than true radius into account).
With current implementation, the narrow cone on top of the full build volume cylinder has radius of only ~27mm, which means that even at 40-50mm from center, build …

Better delta build volume constraint checking

---

scripts/spi_flash/board_defs.py

As discussed with user HiitsameAsh on discord, he has confirmed this addition will flash a Fysetc Cheetah V2
Thanks
James
Signed-off-by: James Hartley james@hartleyns.com

board_defs.py: Add Fysetc Cheetah V2 to spi_flash

---

src/stm32/can.c

Using the CAN2 interface still requires that the CAN1 be enabled, and the filtering hardware is always on the CAN1 hardware block.
-Kevin

stm32: Fix CAN2 handling in can.c

---

klippy/kinematics/extruder.py

Signed-off-by: Andrei Kozhevnikov <coderusinbox@gmail.com>

Add extruder name to extruder_stepper respond message

---

docs/Bed_Mesh.md

Bed_Mesh: Fixed sentence structure in fade_target section.
Signed-off-by: Bassam Husain <bassam.husain@gmail.com>

Bed_Mesh: Fixed sentence structure in fade_target section.  Signed-off-by: Bassam Husain <bassam.husain@gmail.com>

---

scripts/update_chitu.py

Change script to use Python 3 instead of Python 2, in line with changes to update_mks_robin.py
Thanks
James

scripts: update_chitu.py python env version

---

scripts/flash-linux.sh

This is an update to the script that looks for the new systemd service and restarts it if appropriate.
Thanks
James

scripts: Update flash-linux.sh to restart new systemd service

---

klippy/reactor.py

My IDE caught this so i thought id make a quick pr.

reactor: Fix typo

---

docs/Config_Reference.md
klippy/extras/tmc2240.py

tmc: Enable sg_angle_offset for smooth switching from Stealthchop to Spreadcycle

---

docs/Slicers.md

docs/Slicers.md: Add missing code block indicators

---

docs/Measuring_Resonances.md

Removed a duplicated section in Measuring_Resonances.md. 
Also fixed its header level.
Signed-off-by: Nathan Chiu nhchiu2009@gmail.com

docs: Fix duplicate section

---

src/rp2040/usbserial.c

On a USB bus reset the controller address needs to be reset to zero. Otherwise, the device becomes unresponsive after a USB reset and will remain unresponsive until a power cycle.  This often shows up in the Linux system logs as "device descriptor read/64, error -32" messages.
Make sure USB_INTE_BUS_RESET_BITS is enabled and clear the USB address on a bus reset.

Handle USB resets on rp2040

---

klippy/klippy.py
klippy/util.py
scripts/make_version.py

This Pull Request builds on #6184, logging additional repo info useful for determining if a user is running modified code.

klippy: report git branch, remote, and tracking URL

---

docs/G-Codes.md
klippy/extras/resonance_tester.py

resonance_tester: Support CHIPS= parameter in SHAPER_CALIBRATE command

---

klippy/extras/bed_mesh.py

This resolves a regression introduced in #6242, where the average Z value of the mesh is calculated before the mesh is offset and never updated.  When fade is enabled the default value of `fade_target` is set to the average z, resulting in parts that are stretched vertically.

bed_mesh: fix fade regression

---

docs/Config_checks.md

I am endeavoring to rewrite some of the docs to be more front end agnostic to reflect the different front ends available since these docs were written. I am starting with this one, as it quite often used. Please can I have some feedback on the wording.
Thanks
James

Docs: Update Config_checks.md

---

klippy/kinematics/idex_modes.py

idex_modes: A small fix for MOVE_SPEED param

---

.github/workflows/build-test.yaml
.github/workflows/klipper3d-deploy.yaml
.github/workflows/stale-issue-bot.yaml

Signed-off-by: Thijs Triemstra <info@collab.nl>

ci: update dependencies

---

docs/RPi_microcontroller.md

Added a more detailed explanation for pwm-2chan.

Update RPi_microcontroller.md (pwm-2chan)

---

config/generic-mks-monster8.cfg
test/klippy/printers.test

Adding MKS Monster 8 generic configuration
Signed-off-by: Allen Cox <Bomberski420@gmail.com>

Add MKS Monster 8 generic config

---

docs/RPi_microcontroller.md

docs: fix typo in RPi_microcontroller.md

---

src/rp2040/usbserial.c

The rp2040 USB peripheral has support for USB packet "double buffering".  This PR adds support for that hardware feature.  It can improve the performance of USB transfers and improve USB bus utilization.
As with PR #6352, this enhancement is unlikely to be noticed on regular "emulated serial over USB" configurations, but can notably improve performance when using "USB to CANBUS bridge".
-Kevin

Support USB "double buffering" on rp2040 chips

---

config/generic-bigtreetech-octopus-pro-v1.0.cfg
config/generic-bigtreetech-octopus-pro-v1.1.cfg
config/generic-bigtreetech-octopus-v1.1.cfg
test/klippy/printers.test

This is an alternative to #6380 - it introduces 3 configs instead of adding comments to the one existing config.
FYI - @bigtreetech 
-Kevin

Split BTT Octopus configs into 3 new configs

---

config/printer-sovol-sv06-2022.cfg

config: Update printer-sovol-sv06-2022.cfg x_offset
Signed-off-by: Bassam Husain bassamanator.2cj4t@simplelogin.com

config: Update printer-sovol-sv06-2022.cfg x_offset

---

docs/Config_Reference.md

Small change, came up in a discord thread and I wanted to add it since the skr pico is so popular
Signed-off-by: Levi Szabo <iamrazorshark@gmail.com>

Add rp2040 to MCUs with internal temp sensors

---

klippy/extras/mpu9250.py
src/sensor_mpu9250.c

I noticed a couple of errors in the mpu9250 code.
The first is the use of `time.sleep()` in the host code, which isn't valid - it can causes glitches in the host code processing and doesn't actually guarantee a pause at the mcu.
The second is incorrect timing in the command_query_mpu9250_status() implementation.  To get good measurement timing, that function needs to report the number of samples in the mpu9250 chip at the time of the call - so it should not use a cached value of the fifo level.
I don't have an actual mpu9250 (nor similar) so I can't test these changes directly.
@mattaw , @bluesforte - fyi.
-Kevin

Fixes to mpu9250

---

klippy/extras/virtual_sdcard.py

https://github.com/Klipper3d/klipper/pull/6469

fix virtual SD file position count

---

config/printer-anycubic-kobra-plus-2022.cfg

- Need to specify clock speed when building more recent versions of Klipper
- Improve behavior of controller fan

config: update Kobra Plus build instructions and fan settings

---

docs/Resonance_Compensation.md

Fix typo in Resonance_Compensation.md

 docs: Fix typo in Resonance_Compensation.md

---

docs/Config_Reference.md
klippy/extras/tmc.py
klippy/extras/tmc2130.py
klippy/extras/tmc2209.py
klippy/extras/tmc2240.py
klippy/extras/tmc5160.py

This PR adds the necessary changes in order to get CoolStep working on all TMC drivers that support it. All parameters for CoolStep can be defined in the config file. In a followup PR I am planning on writing in the docs instructions for how to get CoolStep configured and calibrated. I've tried to keep the commits as split as possible for ease of reviewing.
CoolStep has these main fields. These fields are supported by all drivers that implement CoolStep:
- `SEMIN`
- `SEUP`
- `SEMAX`
- `SEDN`
- `SEIMIN`
There is an additional field which can be helpful for CoolStep: `SFILT`. This one is not supported by tmc2209. It adds a filter on top of the StallGuard output that is used by CoolStep internally.
There are also velocity based thresholds that can be used with CoolStep. There can be set both …

TMC: CoolStep support

---

klippy/extras/fan.py
klippy/extras/output_pin.py
klippy/extras/servo.py

PR #6670 had an error causing timing problems with heater_fan, temperature_fan, and controller_fan modules.  The fan queuing changes of that PR were reverted in commit 900bf2be.  
This PR adds fan queuing for g-code commands while preserving the previous behaviour for asynchronous updates from the heater_fan, temperature_fan, and controller_fan modules.  This should, hopefully, fix the issues with the previous PR.
-Kevin

Queue and collate fan requests (fixed PR)

---

src/rp2040/i2c.c

For now, RP2040 silently ignores any kind of errors, and we only try to catch them by timeout condition.
I did some tests, write can't be timeouted actually, at least with a disconnected device.
So, these are specific checks for NACK.
I did reproduce Start NACK/Start Read NACK by disconnecting SDA line from the device.
Write NACK has not been tested, I'm a little puzzled about how to reproduce write NACK.
Thanks.

rp2040/i2c.c: Check for NACK/Start NACK

---

lib/README
lib/can2040/can2040.c

This provides improved support on rp2350 chips.
-Kevin

Update can2040 to v1.7.0

---

klippy/extras/bed_mesh.py

This pull request addresses issues with `bed_mesh` generated points overwhelming the log and/or the pty.  Its common for users with "scanning" probes to configure dense meshes which may contain thousands of points.  The following changes have been made to mitigate this issue:
1) Initial points are truncated to 50.
2) Points are no longer printed when the mesh configuration changes.

bed_mesh: reduce generated point logging

---

klippy/chelper/kin_shaper.c

This PR fixes stepcompress errors when using input shaper with polar kinematics.

input_shaper: Fix for polar kinematics

---

klippy/extras/buttons.py

Fixes incorrect code that causes potential startup crash caused by changes in #6848

buttons: fixes incorrect parameters

---

docs/Installation.md

Fixed typos, hyphenation, and minor phrasing for better readability.

docs: Fix typos in installation.md

---

docs/Status_Reference.md
docs/_klipper3d/README

Signed-off-by: Russell Cloran <rcloran@gmail.com>

docs: Minor typo fixes

---

klippy/extras/output_pin.py

The output_pin template code has a cache to speed up duplicate rendering of templates.  However, this cache doesn't work if one of the parameters is a Python list or dictionary.  Just disable the cache in this case.
-Kevin

output_pin: Make it possible to assign dicts/lists as template parameters

---

src/i2c_software.c

The i2c_delay() function did not properly handle counter rollovers. It also performed an expensive run-time divide.
-Kevin

Fix i2c_delay() in i2c_software
